### ISSUE TITLE
Host File change not saving with balenaCloud

### ISSUE THREAD

**Issue by CrazyBoySnp** [Screenly/screenly-ose#1003]

**Comment by CrazyBoySnp** [comment]
Issue : 

When I modify the Host File for OSE in the balenaCloud through their shell it does not keep the settings after a reboot.

Details :

I log into my balenaCloud and modify my Raspberry PI that has OSE installed and working fine I modify the /etc/host/ file with Sudo Nano to add my local internal domain adding the IP and the DNS name and then saving it, it works fine until I reboot and that setting removes itself from the Host File and then I have to go add it again.

This works to show our internal website which is NOT accessible outside our domain. After reboot it breaks again.

Environment :

Raspberry PI : 2,+ 3b, 3b+
Corporate Environment

**Comment by vpetersson** [comment]
@CrazyBoySnp That sounds like a balenaCloud issue. I'd suggest you create a post on the [balena forum](https://forums.balena.io).
