### ISSUE TITLE
add images via script

### ISSUE THREAD

**Issue by HunterZeroSix** [Screenly/screenly-ose#1005]
Hey guys I need your help
I´m desperate
I wrote a bash script to add images into the database
because I download my images from a server and store it local on the SD-Card

After that, i sort the images based on the folder where the images are
then i write the files into the database with some sql commads
but by creating my own asset_id i get this Problem

> Server Error: 'ascii' codec can't encode character u'\xfc' in position 77: ordinal not in range(128)

I create the asset_id with this comand
`cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 32 | head -n 1`

I don´t can programm Python but I will learn 
First of all I need your help to fix this Problem

### Environment
* Raspberry Pi Hardware Version: 3B+
* Screenly OSE Version: any

PS
I know my english is not good
And I start programming in september last year
Please have indulgence with me

**Comment by HunterZeroSix** [comment]
OK now i fix the problem that 

> Server Error: 'ascii' codec can't encode character u'\xfc' in position 77: ordinal not in range(128)
by configure the right CODEC with
`dpkg-reconfigure locales `
and showing th right speach with 
`locale`

but screenly don't wanna show me some image...

**Comment by rusko124** [comment]
Hi @HunterZeroSix !
I would advise you to use API which provides Screenly-OSE
Full list of endpoints you can look at your_url/api/docs/

**Comment by rusko124** [comment]
Glad to help, good luck!
