### ISSUE TITLE
It gives me a 502 bad gateway error.

### ISSUE THREAD

**Issue by menarcarlos** [Screenly/screenly-ose#1006]
Hi folks, following the tutorial: https://www.youtube.com/watch?v=-P_OZRBZN74
I Have a issue to open the url: Error 502 Bad Gateway

**Comment by rusko124** [comment]
Hi @menarcarlos !
Could you provide more information or write your actions step by step, please?

**Comment by menarcarlos** [comment]
Hi rusko.

I'm using raspberry pi3 b+ (ARM7), I'm using balena.io to upload the project.

The steps followed to develop the application were taken from: https://www.balena.io/docs/learn/getting-started/raspberrypi3/python/

I using microSDXC 10 class formated with Etcher over Windows 10.

**Comment by rusko124** [comment]
@menarcarlos 
`git push balena master` passes without error?
Then you should see something like this.
![balena_update](https://user-images.githubusercontent.com/17593028/50830381-d490c380-1371-11e9-9acd-93e5d1587917.png)
Have you reached this point?

**Comment by ealmonte32** [comment]
@menarcarlos could you pls upload a screenshot of the bad gateway error exactly as you see it?

**Comment by menarcarlos** [comment]
Hi to all.
I start to clone the repo :  git clone https://github.com/Screenly/screenly-ose.git

then...
c:\>balena login 		( Success )
c:\>balena push screenlyose 	 ( Success )
Unicorn printed			 ( Success )
Balena cloud (Updating)          ( Success )
https://5e3e0dc237e046cbb3359ff2ffbf8b5f.balena-devices.com/       - Unsuccess


So i went to the source code of the project and i found in the code of:
screenly-ose/settings.py

This lines:

`PORT = int(getenv('PORT', 8080))`
`LISTEN = getenv('LISTEN', '127.0.0.1')`

**Comment by ealmonte32** [comment]
> Hi to all.
> I start to clone the repo : git clone https://github.com/Screenly/screenly-ose.git
> 
> then...
> c:>balena login ( Success )
> c:>balena push screenlyose ( Success )
> Unicorn printed	( Success )
> Balena cloud (Updating) ( Success )
> https://5e3e0dc237e046cbb3359ff2ffbf8b5f.balena-devices.com/ - Unsuccess
> 
> So i went to the source code of the project and i found in the code of:
> screenly-ose/settings.py
> 
> This lines:
> 
> `PORT = int(getenv('PORT', 8080))`
> `LISTEN = getenv('LISTEN', '127.0.0.1')`

@menarcarlos Do you have physical access to the raspberry pi device? If so, can you pls paste the outcome of the following command:

sudo netstat -pln | grep :80

Thanks.

**Comment by vpetersson** [comment]
Closing out issue due to lack of response.
