### ISSUE TITLE
Experimental browser, web components

### ISSUE THREAD

**Issue by dauledk** [Screenly/screenly-ose#1016]
#### Overview of the Issue
I can't load a webpage with [web components](https://caniuse.com/#search=shadow%20dom%20v1), I am running the experimental version of Screenly.

#### Reproduction Steps

Steps to reproduce this issue, eg:
* Update to experimental
* Press Add Asset
* Enter the Asset URL ...
* Press "On"
* Wait for the asset to show up on the screen

### Environment

* Raspberry Pi Hardware Version: 3
* Screenly OSE Version: (I am not sure where I can find this info)

**Comment by ealmonte32** [comment]
@dauledk 
I just tested this in non experimental and it works fine.

**Comment by dauledk** [comment]
Hi @ealmonte32 Sorry for the confusing link. This link just show support for Shadow DOM v1 on different browsers. Can you maybe check [this link](https://jernbanecafeen.dk/arkiv/)? 
 
This part of the page is a web component.

![screenshot 2019-01-10 at 21 52 20](https://user-images.githubusercontent.com/9967422/50996406-1496a880-1522-11e9-9cec-40dfc4d2640b.png)

**Comment by ealmonte32** [comment]
Forgot to mention, the experimental branch does not come with uzbl but instead with alternative browser, as mentioned here:
https://github.com/Screenly/screenly-ose/issues/527

and here:
https://github.com/Screenly/screenly-ose/issues/824

Therefore, if the experimental branch browser does not render the component/elements on that page, i'm afraid at this moment that's the only option to at least have a newer browser than the one that comes with the regular version..

I will try some things and if i can come up with workaround i'll mention it here, if not, sorry =[
