### ISSUE TITLE
Jitsi (Video conference) Webpage not loading

### ISSUE THREAD

**Issue by fa-grosch** [Screenly/screenly-ose#1019]
#### Overview of the Issue

When adding a [Jitsi meeting video conference link](https://meet.jit.si) into screenly as a new asset, it only displays a grey page without joining the video conference.

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Press Add Asset
* Enter the Asset URL https://meet.jit.si/SeriousBearsHugLovingly
* Press "On"
* Wait for the asset to show up on the screen
* Only a grey page is displayed

### Environment

* Raspberry Pi Hardware Version:
3 Model B (a22082, Q1 2016), CPU: 1.2 GHZ, RAM: 1 GB

* Screenly OSE Version: 62bfe2ff477122ee97bf1b1017e94abffad52013
```
cd ~/screenly && git rev-parse HEAD
```

**Comment by vpetersson** [comment]
@fa-grosch I doubt that will work. The Raspberry Pi is nowhere near powerful enough to handle something like a video conference stream.

**Comment by fa-grosch** [comment]
@vpetersson thanks for your answer, would it work with a more powerful hardware + screenlyOS?

**Comment by vpetersson** [comment]
Currently, we only support the Raspberry Pi officially. However, in theory, any of the supported hardware that [Balena](https://www.balena.io) could work.
