### ISSUE TITLE
Extended character set file names

### ISSUE THREAD

**Issue by renowden** [Screenly/screenly-ose#1020]
Screenly OSE latest version (Sprint 8). Uploading assets from Windows 10. It objects to a file name containing an apostrophe (otherwise known as a right single quote).  This is whether by select file or drag and drop. It used to work on our previous version (before the drag and drop interface). Sample file name

Ricks’s picture.jpg

**Comment by madsrh** [comment]
I can confirm this issue when using danish characters like æ, ø and å in the filename

`Server Error: 'ascii' codec can't encode character u'\xe6' in position 43: ordinal not in range(128)`

**Comment by vpetersson** [comment]
Interesting find. I thought we had already solved this with proper UTF8 support. @rusko124 let's add this to the next sprint.

**Comment by rusko124** [comment]
Solved and already in master branch.
@vpetersson I think we can close this.
@renowden @madsrh If this issue will not solved for you or you'll have any questions, please let me know.
