### ISSUE TITLE
Number of times a video was played

### ISSUE THREAD

**Issue by fbsanches** [Screenly/screenly-ose#1021]
Is there in the pro or ose version any way or in some third party software capable of knowing how many times a video was played during a period? Thanks.

**Comment by vpetersson** [comment]
@fbsanches we did have this functionality in Screenly Pro, but there wasn't a whole lot of adoption. It is something we might bring back in down the road if there is sufficient amount of demand. 

For OSE, you could in theory scrape the logs to create metrics.

**Comment by fbsanches** [comment]
Thank you!
