### ISSUE TITLE
Screenly OSE WiFi

### ISSUE THREAD

**Issue by cdesany** [Screenly/screenly-ose#1023]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I bought the Screenly OSE package from PiShop.us. I plugged it in and made a note of the new access point. Connected to it from a separate computer. When the resin screen comes up, I get a bunch of blank lines for wifi networks, and a single network repeated several times (check out attached screenshot). The wifi I actually want doesn't show up.

I can't get the pi (screenly OSE) connected to the wifi I want.

Any help would be greatly appreciated.

Thanks,

Chris

![screen shot 2019-01-28 at 10 08 52 am](https://user-images.githubusercontent.com/47113986/51846635-f97cb480-22e7-11e9-9380-8a677380404b.png)

### Environment

* Raspberry Pi Hardware Version: 3.0B+
* Screenly OSE Version: 11/23/18

**Comment by vpetersson** [comment]
@cdesany Strange. The only thing that I can think of is that you connect it over ethernet and run the upgrade to the development version to see if that resolves the issue. Then, you can reconfigure wifi.
