### ISSUE TITLE
Feature Request: Sorting Inactive Assets

### ISSUE THREAD

**Issue by soundblastdj** [Screenly/screenly-ose#1025]
I've set up our organization's sign to display fun "unusual holidays" for each week and I've scheduled them in Screenly's web interface.  I went in today to make sure that everything is working correctly, but after adding 30-40 scheduled slides, it gets really hard to track down which one you're looking for.  It would be nice if we could sort these assets by name, date added, or start/end date.  Also, it would be really nice to have an option for assets to automatically be deleted after their scheduled dates or schedule recurring dates.

**Comment by vpetersson** [comment]
@soundblastdj This is something we have in Screenly Pro, but not in OSE. We'd be happy to accept contributions for improving this in OSE but it isn't something that we have on the roadmap at the moment.
