### ISSUE TITLE
Suggested URL Format for Web Asset not working

### ISSUE THREAD

**Issue by farhangithub27** [Screenly/screenly-ose#1028]
#### Overview of the Issue

web asset with login parameters as suggest in #515 are not working. I have posted my detailed comment in #515  as well.

### Environment

* Raspberry Pi Hardware Version:pi3B
* Screenly OSE Version:image_2018-11-23-Screenly-OSE-lite

### Details:

Hi @vpetersson , I'm trying to configure web asset with URL  format as `http://username:password@domain:port` 
following cases I have used example. I'm trying to land at the home page of my reporting server.

- http://myusername:mypassword@myhost.mydomain:myport/reportingserver/flow.html?_flowid=searchFlow
This url is not getting accepted by screenly. Throws out error message 
 **Server Error: Could not retrieve file. Check the asset URL**.I guess uzbl doesn't accept _flowid parameter?
- http://myusername:mypassword@myhost.mydomain:myport/reportingserver/flow.html
This one doesn't get accepted by screenly throws out same error message as above.
- http://myusername:mypassword@myhost.mydomain:myport/reportingserver/login.html
This one gets accepted but nothing gets displayed.
- http://myhost.mydomain:myport/reportingserver/login.html
This url gets accepted and login screen gets displayed but then again I cannot use keyboard.

FYI a get request in POSTMAN and firefox  browser works fine with standard get request that lands me to the home page of the server. Postman request below is
http://myhost.mydomain:port/reportingserver/flow.html?_flowid=searchFlow&username=myusername&password=mypassword
Also
I have installed uzbl browser on my development system and used URL used for postman
I got logged in successfully through uzbl but it didn't recognize _flowid parameter. So it logged me in but didn't display the home page. I just used mouse and menu bar of the presented page to get to home page.
**This means uzbl takes in username and password parameters fine in get request while _flowid was ignored.**
So I tried to use this request format in screenly webasset configuration but it throws out same error message:
**Server Error: Could not retrieve file. Check the asset URL**

Any suggestions how to use your suggested format or anyother to login into my reporting server through screenly web asset.

**Comment by vpetersson** [comment]
@farhangithub27 I've added this to Sprint 9. We're a bit behind on this due to work being done on the commercial version of Screenly.

**Comment by rusko124** [comment]
Hi @farhangithub27!
I reproduced all the variations of the urls you described above. 
In my case, all worked.

**Server Error: Could not retrieve file. Check the asset URL**
I get this error in the following cases:
- Invalid url
- `username:password@` not specified or invalid
In other cases, I have successfully added links and they are also successfully displayed in the viewer.

If you haven't solved this issue yet, try upgrading to the latest development version or you can provide a url that doesn't work in your case so I can test.
