### ISSUE TITLE
FAQ - Touchscreen

### ISSUE THREAD

**Issue by mikebrowntsbod** [Screenly/screenly-ose#1029]
Does Screenly OSE support touchscreen? Meaning if it is connected to a TV that is touch screen does it allow for users to interact with it.

**Comment by vpetersson** [comment]
@mikebrowntsbod No, touch input is disabled (as well as keyboard). It could in theory work, but we've disabled this due as it's:

a) a security issue
b) requires a fairly different use workflow

There are a few other issues that goes into detail on this (as touch is essentially just a mouse)
