### ISSUE TITLE
How to update Screenly through Balena

### ISSUE THREAD

**Issue by Metrac** [Screenly/screenly-ose#1035]
When you update Screenly through Balena, do you need to execute the following command in the HOST OS or MAIN terminal?

$ bash <(curl -sL https://www.screenly.io/install-ose.sh)

Also, Screenly update asks thing like Networkmanageretc. what are the recommended settings?

Sorry being total new to this!

**Comment by vpetersson** [comment]
@Metrac please move this to the [Screenly OSE on Balena](https://forums.screenly.io/c/screenly-ose/balena) forum.
