### ISSUE TITLE
Website does not render (SonarQube)  Sprint 8 and Experimental

### ISSUE THREAD

**Issue by lord-carlos** [Screenly/screenly-ose#1041]
#### Overview of the Issue

I tried both latest release and experimental. Both version just show the white background instead of the expected webpage.
The webpage is a local version of sonarqube, here is a public one that also shows the same behavior: https://next.sonarqube.com/sonarqube/projects?sort=-analysis_date

#### Reproduction Steps

* Press Add Asset
* Enter the Asset URL https://next.sonarqube.com/sonarqube/projects?sort=-analysis_date
* Press "On"
* A spinner shows and then I just see white

### Environment

* Raspberry Pi Hardware Version: I think it's 3 or 3+
* Screenly OSE Version: Sprint 8 and Experimental.

**Comment by vpetersson** [comment]
I don't think there is much we can do on our end to solve this, as that is a limitation in the browser.

**Comment by lord-carlos** [comment]
Ok. Thanks anyway.
