### ISSUE TITLE
Add secondary warning about shutting down Screenly/Pi from web interface

### ISSUE THREAD

**Issue by ealmonte32** [Screenly/screenly-ose#1047]
Referencing this PR: https://github.com/Screenly/screenly-ose/pull/1011
Creating ticket per @vpetersson request

```
@celery.task
def shutdown_screenly():
    """Background task to shutdown Screenly-OSE."""
    sh.sudo('shutdown', 'now', _bg=True)
```

That would shut down the actual Pi and not just Screenly, although we know this, most of the users may forget and shutting down Screely here is actually shutting down the Raspberry Pi or whatever model they are running, and they would have to physically go and turn it back on.

A secondary warning should be given to users who try to shut down the system to remind them of this.

**Comment by vpetersson** [comment]
Sensible feature @ealmonte32. We need to change how we actually perform this, but the logic is sound. Adding to next sprint.
