### ISSUE TITLE
Video asset plays in console

### ISSUE THREAD

**Issue by madsrh** [Screenly/screenly-ose#1050]
#### Overview of the Issue

If you have videos in your playlist, the video will start playing when you are using the console/terminal on the directly on the Pi (not SSH).

#### Reproduction Steps / What Happens

* Add an image and a video asset 
* Set both assets active now
* Press CTRL + ALT + F1 to enter the console
* Wait until the duration of the image is over
* The video will play and afterwards you'll return to the console

### Environment

* Raspberry Pi Hardware Version: 3b+
* Screenly OSE Version: image_2018-11-23-Screenly-OSE-lite

#### Comments

I guess this is a pretty rare usecase, which makes this low priority.

**Comment by vpetersson** [comment]
This is expected because `omxplayer` users framebuffer to display the video, so it will override the console.
