### ISSUE TITLE
Development: Change asset location

### ISSUE THREAD

**Issue by qbicdesign** [Screenly/screenly-ose#1057]
Suggestion

#### Overview of the Issue
Currently if you need to change an asset's URL, the only way to do that is to delete the existing asset and add a new one. 

It would be really nice to be able to edit the URL, as re-adding assets requires re-entering all the date/time, duration and queue settings.

**Comment by vpetersson** [comment]
@qbicdesign This is on purpose. There are some checks that runs when you add an asset. If we would allow you to edit an asset it could create a kind of edge case.

**Comment by ealmonte32** [comment]
@qbicdesign 
Do you find yourself always setting the date/time for duration to the same "duration" ?
For example, without changing the default behavior for all other screenly users, what would you like the default duration or date/time to be for your personal environment?

**Comment by vpetersson** [comment]
Closing out this one. The recommended approach for this if you want to automate it is to delete the asset and add a new one. Tampering with assets can create all sorts of bugs.
