### ISSUE TITLE
Asset in processing

### ISSUE THREAD

**Issue by agentdogit** [Screenly/screenly-ose#1062]
Asset in processing

I have an inactive asset that says  'Asset in processing' This is not really doing anything but its annoying and I wanted to clear it out, anyone come across this before?

![2019-03-25 15_09_28-Screenly OSE - nottspimedia1](https://user-images.githubusercontent.com/18212968/54930936-114f6e00-4f10-11e9-943f-65df01022c7d.png)

### Environment

* Raspberry Pi Hardware Version: 3 model B
* Screenly OSE Version: latest development version

**Comment by ealmonte32** [comment]
@agentdogit 

I replied on the forums.

> Well the assets are kept on sqlite but unless you’re familiar with sql commands I dont recommend messing with it, but I know one way to sort of “reset” the assets, you dont lose any of the configuration or assets:
> 
> /home/pi/screenly/bin/migrate.py
> 
> I dont remember exactly why you might get a permission denied, if you do, just do:
> chmod 744 /home/pi/screenly/bin/migrate.py
> and then try again.
> You can also do the run_upgrade.sh file that is in that bin folder as well, just pick the same options you selected when you installed screenly, and if you enabled ssl then you have to run that file after as well, its in the bin called enable_ssl.sh , again, you dont lose any assets or data by running these.
