### ISSUE TITLE
Wifi Problem

### ISSUE THREAD

**Issue by mKorniK** [Screenly/screenly-ose#1063]
Hey guys.
I installed screenly OSE by option 1 (Github custom image). It works fine, but there is no way for me to connect to my fritzbox 7490 by wifi .I´m using a pi 3b+ with integrated wifi. 
I tried so many things but nothing works..
Where is the problem???

here some of my configs:

> ifconfig wlan0
`wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 9e:58:de:46:42:57  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

> sudo nano /etc/wpa_supplicant/wpa_supplicant.conf  

`country=DE
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
        ssid="FRITZ!Box_ERGO"
        psk="*****"
        key_mgmt=WPA-PSK
        proto=RSN
        pairwise=CCMP
        auth_alg=OPEN
}
`

> sudo nano /etc/network/interface

`auto lo
iface lo inet loopback
iface eth0 inet dhcp
allow-hotplug wlan0
auto wlan0
iface wlan0 inet dhcp
wpa-ssid "FRITZ!Box_ERGO"
wpa-psk "***********"`

* Raspberry Pi Hardware Version: 3B+
* Screenly OSE Version: actual / downloaded today

**Comment by vpetersson** [comment]
This is not really a Screenly-specific issue. Essentially, your WiFi fails to connect for one reason or another. I suggest that you either use the wifi wizard (should appear on a fresh installation if you don't have any network) or use the WiFi config tool in `raspi-config`.
