### ISSUE TITLE
Enable overscan functionality 

### ISSUE THREAD

**Issue by bcherup** [Screenly/screenly-ose#1064]
Screenly or X11 ignores config.txt overscan options, is there anyway we can add this to the Screenly Environment ? I have a cheap TV that turns on OVERSCAN by default and can only be disabled with the remote.... this setting does not save on input change or tv power cycle 

### Environment

* Raspberry Pi Hardware Version: B+ 3
* Screenly OSE Version: Experimental

**Comment by vpetersson** [comment]
@bcherup Screenly doesn't do anything as far as overscan goes. That's all handled by the system. Do however note that videos are played using framebuffer (using `omxplayer`) and web/images are not. Hence, you will have a different experience. What type of assets are you having issues with?

**Comment by qbicdesign** [comment]
what model TV is it?

**Comment by vpetersson** [comment]
Closing due to lack of response.
