### ISSUE TITLE
hard coded pi in install.sh

### ISSUE THREAD

**Issue by Cicicok** [Screenly/screenly-ose#1075]
In installation script is hard coded the username **pi**.

`ansible localhost -m git -a "repo=${1:-https://github.com/screenly/screenly-ose.git} dest=/home/pi/screenly version=$BRANCH"`

Is there a particular reason for it? Why is not used home folder of current user?

**Comment by vpetersson** [comment]
Yes - it's the way 99.9% of all Raspberry Pis are configured. It is however something that will become irrelevant as we move to dockerizing Screenly OSE.
