### ISSUE TITLE
Add "power down system" option via CEC remote control

### ISSUE THREAD

**Issue by stlouisubntu** [Screenly/screenly-ose#108]
Currently the only method I am able to see to property shutdown the unit when finished is to ssh into it and issue a "sudo shutdown -h now" command (then unplug it once the shutdown cycle is complete.)

Otherwise, the only other option is to cut the power to unit (always inadvisable regardless of architecture type or OS) while still in operation.  No user friendly options currently exist.

CEC works well on the xbmc raspberry pi distros (I use raspbmc) and all modern digitial / HDTVs include this feature.

By the way, I love this project.  Thanks so much for sharing.  FWIW, my use case will be a sign / message / video kiosk display in a small church in St. Louis, Missouri, USA.

**Comment by vpetersson** [comment]
@stlouisubntu Can you take a closer look how this is done in Rasbmc? If you can provide exact commands and configurations for how this is done, we can implement it.

**Comment by vpetersson** [comment]
I poked around with `cec-client` a bit today and found some useful commands.

### Turn monitor off

    $ echo 'standby 0' | cec-client -s -d 1

### Turn monitor on

    $ echo 'on 0' | cec-client -s -d 1

### Set monitor as active

    $ echo 'as' | cec-client -s -d 1

### Set monitor as inactive

    $ echo 'is' | cec-client -s -d 1

**Comment by Lil-briX** [comment]
Hey,
im just using:
"vcgencmd display_power 0" to interupt the HDMI signal from the pi. Most of the TV will automatically switch into the power saving mode afterwards. 

To wake up the TV just type "vcgencmd display_power 1" 
I just usw this in a cronjob and im perfectly fine with it. 

Greetz.

**Comment by vpetersson** [comment]
@Lil-briX interesting findings.

**Comment by C-Duv** [comment]
Note that, when not receiving HDMI signal anymore, some monitor will switch to other source (other HDMI, VGA, etc.).

**Comment by vpetersson** [comment]
I actually wrote a [blog post](https://news.screenly.io/how-to-automatically-turn-off-and-on-your-monitor-from-your-raspberry-pi-5f259f40cae5) about this that might be worth checking out.

**Comment by vpetersson** [comment]
Closing out in favor of #1178
