### ISSUE TITLE
Migrate to multi-container on Balena

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1080]
Some time ago, Balena introduced [multi-container](https://www.balena.io/docs/learn/develop/multicontainer/) support. This is a great improvement as it follows the Docker best practice of only running one service per container. We likely need three containers:

 * Viewer
 * Server
 * Celery

**Comment by vpetersson** [comment]
@rusko124 I guess this is still blocked by the lack of celery container, right?

**Comment by rusko124** [comment]
@vpetersson Yes, you're right
