### ISSUE TITLE
how to run php file with nginx server in  screenly -ose

### ISSUE THREAD

**Issue by mahejbeen** [Screenly/screenly-ose#1087]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Press Add Asset
* Enter the Asset URL ...
* Press "On"
* Wait for the asset to show up on the screen

### Environment

* Raspberry Pi Hardware Version:
* Screenly OSE Version:
i install  php in screenly ose .command line  php is working .i want see this pages in browser .
 this is my  screenly configuration file`upstream ose {
  server 127.0.0.1:8080;
 
}

upstream wifi-connect {
  server 192.168.42.1:9090;
}

server {
  server_tokens off;
  listen 80 default_server;

  location / {
    if (-f /home/pi/.screenly/initialized) {
      proxy_pass http://ose;
    }
    if (!-f /home/pi/.screenly/initialized) {
      proxy_pass http://wifi-connect;
    }

    client_max_body_size 4G;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
  }

  location /static {
    proxy_pass http://ose/static;
  }

  location /hotspot {
    allow 127.0.0.1;
    deny all;

    if (!-f /home/pi/.screenly/initialized) {
      root /tmp;
      rewrite ^ /hotspot.html break;
    }
  }

}

upstream vault {
    server 127.0.0.1:8080;
}

server {
    listen 80;
    

    error_log /var/log/nginx/vault.shopshop.space_error.log;
    access_log /var/log/nginx/vault.shopshop.space_access.log;

    root /var/www/html/contact;
    index index.php;

    location / {
        try_files $uri var/www/html/contact/index.php$is_args$args;
     }

    location ~ \.php {
          include snippets/fastcgi-php.conf;
  
  # # With php-fpm (or other unix sockets):
    fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
  # # With php-cgi (or other tcp sockets):
    #fastcgi_pass 127.0.0.1:9000;
    }
}

**Comment by vpetersson** [comment]
Sorry, but i don't really see a question in here. Generally speaking, I would not recommend doing this, but it is possible.
