### ISSUE TITLE
Perform facelift of graphic assets

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1097]
The assets are becoming somewhat dated. We need to:

 * Update the splash screen to make it clear that it's Screenly OSE (i.e perhaps write it out "Open Source Edition" 
 * Refresh all the look and feel to to make it consistent across all assets (i.e. not mix the blue and purple color scheme)

**Comment by vpetersson** [comment]
ping @L4cko

**Comment by L4cko** [comment]
@vpetersson Here is the updated kit https://drive.google.com/open?id=1xgg_5QTA8hcZUwLh5Hz5DFxRw9WxBOS4

**Comment by vpetersson** [comment]
Thanks @L4cko. I don't see the exact assets requested above in the folder, but please collaborate with @rusko124 on getting this implemented.

**Comment by rusko124** [comment]
@L4cko It would be great if we could also provide a design for this #1107

**Comment by L4cko** [comment]
![image](https://user-images.githubusercontent.com/45398471/58408247-b7813680-806d-11e9-8bf5-7c39d858104f.png)

This is the new footer design that I and Alexander work on.

**Comment by L4cko** [comment]
![image](https://user-images.githubusercontent.com/45398471/58408290-cf58ba80-806d-11e9-9ccc-d872bef8a85c.png)
This is the new footer

**Comment by vpetersson** [comment]
@L4cko No it isn't. That's the footer for the marketing site (screenly.io). We're talking about the footer in OSE here.

**Comment by L4cko** [comment]
![v1](https://user-images.githubusercontent.com/45398471/58463573-65efaf00-8134-11e9-99fc-43f5a2417105.jpg)
![v2](https://user-images.githubusercontent.com/45398471/58463574-66884580-8134-11e9-8749-981e4611802f.jpg)

Here are two versions. If you are updating the blue to purple, let me know.

**Comment by rusko124** [comment]
@L4cko Look good to me.
As for the colours I think need a full design to discussing.
#842 there @madsrh already provided some design too.

**Comment by vpetersson** [comment]
@rusko124 let's go with this one:
![58463574-66884580-8134-11e9-8749-981e4611802f](https://user-images.githubusercontent.com/357664/59610292-fd7f6680-9110-11e9-8085-02a2b59053be.jpg)
