### ISSUE TITLE
Screenly does not provide a method to input username in initial Wifi setup

### ISSUE THREAD

**Issue by djflux** [Screenly/screenly-ose#1098]
#### Overview of the Issue

Stock Screenly OSE does not provide a method to input a username to connect to a WPA Enterprise EAP-PEAP SSID.

![image](https://user-images.githubusercontent.com/5767728/57028720-6f552c80-6c05-11e9-99d6-96e2fc31ec98.png)

#### Reproduction Steps

* Load Pi with 2019-04-27-Screenly-OSE-lite.img
* Boot Pi
* Connect to adhoc SSID
* Navigate to http://screenly.io/

### Environment

* Raspberry Pi Hardware Version: Pi3 Rev B from adafruit 
* Screenly OSE Version: 2019-04-27-Screenly-OSE-lite.img

**Comment by vpetersson** [comment]
@djflux Assuming you're referring to WPA2 Enterprise (i.e. ~802.1x), this is far more complex than just adding a field for username and password. It's also not supported in Belena/Resin wifi connection tool. 

You can still configure the Rasperry Pi to connect to this manually, but this is out of scope for our use case for the WiFi connection tool unfortunately. If you want, please feel free to lobby for this feature [here](https://github.com/balena-io/wifi-connect). If it is added there, we will inherit it.

**Comment by djflux** [comment]
Thanks for the quick response. Searching through the WiFi Connect issues, according to https://github.com/balena-io/wifi-connect/issues/123 it looks as if the capability to support WPA Enterprise EAP-PEAP (which is exactly what I need) was added to wifi-connect v4.2.0 with this commit: 

https://github.com/balena-io/wifi-connect/commit/6547a4a77c76d0ec903033f44a177f312c2831fe

Is there something I need to do on my end to get it working in the UI. It's be willing to do the work and submit a pull request if someone points me in the correct direction :)

Thanks for the great software!

**Comment by vpetersson** [comment]
@rusko124 let's upgrade WiFi Connect.

**Comment by vpetersson** [comment]
@djflux Since it is supported upstream it should be fairly straight forward to add it. I've gone ahead and added it to the next sprint.

**Comment by rusko124** [comment]
@djflux 
This problem should be solved in the latest development version, try to upgrade. Please let me know if it helped you.

**Comment by rusko124** [comment]
I think we can close it.
If there's any issues reopen please.
