### ISSUE TITLE
I can't find the controlpanel

### ISSUE THREAD

**Issue by TheCazz** [Screenly/screenly-ose#1103]
Hi
I have download the latest image of screenly OSE but I can't see where I can reboot or shutdown the raspberry.

Have look in the Settings and System Info

**Comment by thefyfy** [comment]
Hi
Sorry but this is not possible. The Screenly OSE API doesn't expose this services.
(and this is not available in Settings and System Info pages...)

**Comment by vpetersson** [comment]
There is no functionality for this exposed. You'd need to SSH into the device and shut it down.

**Comment by TheCazz** [comment]
Hmmm then I misunderstood when I read this which should be included in the latest version
https://github.com/Screenly/screenly-ose/issues/121

**Comment by rusko124** [comment]
@TheCazz Hi!
Currently it works in the celery branch. In this sprint, we plan to fully test it then it will be in the production.

**Comment by TheCazz** [comment]
Ahh thanks :)
