### ISSUE TITLE
Script warning: Clean up unused packages -  apt vs apt-get

### ISSUE THREAD

**Issue by qbicdesign** [Screenly/screenly-ose#1105]
I used the upgrade script to upgrade to experimental from development.
During the upgrade it throws this warning:

TASK [system : Clean up unused packages] ****************************************************************************************************************************************************************************
 [WARNING]: Consider using the apt module rather than running 'apt-get'.  If you need to use command because apt is insufficient you can add 'warn: false' to this command task or set 'command_warnings=False' in
ansible.cfg to get rid of this message.

#### Reproduction Steps

* Install Screenly OSE from custom image
* Upgrade to experimental (I upgraded from development) 

### Environment

* Raspberry Pi Hardware Version: Model 3B+ Revision: 1.3 Ram: 1 GB Sony UK

**Comment by vpetersson** [comment]
@qbicdesign this is just a warning. Shouldn't impact anything.
