### ISSUE TITLE
Resolve issue with API docs in latest image

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1106]
#### Overview of the Issue

The API documentation does not render using the latest disk image (sprint 9). I'm getting "Failed to load spec."

#### Reproduction Steps

* Install the latest disk image (sprint 9)
* Navigate to http://<IP of device>/api/docs

### Environment

* Raspberry Pi Hardware Version: 3B+
* Screenly OSE Version: Sprint 9 disk image

**Comment by rusko124** [comment]
After updating to development version this problem was solve
![docs](https://user-images.githubusercontent.com/17593028/58230494-52200380-7d56-11e9-8d88-002c626b32bc.png)
