### ISSUE TITLE
Add Option for Backup 

### ISSUE THREAD

**Issue by AdrianKarth** [Screenly/screenly-ose#1110]
#### Overview of the Issue

Backup of Screenly saves to a generic file without a unique name. Can we please add a function to the backup that will use the Screenly name as part of the backup filename as well as a possible date as well.

#### Reproduction Steps

Creating a Backup via Screenly 

### Environment

* Raspberry Pi Hardware Version:
* Screenly OSE Version:

**Comment by vpetersson** [comment]
@AdrianOrenstein Seems like a sensible option.
