### ISSUE TITLE
Fix "Screenly Version" for Balena deployments

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1117]
Currently, the "Screenly Version" field under System Info is broken on Balena. Unfortunately, there doesn't seem to be a way to [read the version](https://www.balena.io/docs/learn/develop/runtime/) using environment variables, so I guess we need to write the version to disk and read it back.

**Comment by ShukhratK** [comment]
Hi. Is this version compatible with Balena? According to this https://www.balena.io/blog/deploy-a-digital-signage-application-with-screenly-and-resin/ it is not.

**Comment by vpetersson** [comment]
@ShukhratK Well, technically speaking, it was Balena/Resin that broke the support. It has since been fixed again.

**Comment by ShukhratK** [comment]
@vpetersson thx for ur prompt response. i just tried it and got the following error:

`[main]     W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)
[main]     E: Some index files failed to download. They have been ignored, or old ones used instead.
[main]
[main]     Removing intermediate container abb766e57ee2
[Info]     Uploading images
[main]     The command '/bin/sh -c apt-get update &&     apt-get -y install         build-essential         curl         git-core         libffi-dev         libssl-dev         matchbox         net-tools         nginx-light         omxplayer         psmisc         python-dev         python-imaging         python-netifaces         python-simplejson         libraspberrypi0         ifupdown         sqlite3         uzbl         x11-xserver-utils         xserver-xorg &&     apt-get clean' returned a non-zero code: 100
[Success]  Successfully uploaded images
[Error]    Some services failed to build:
[Error]      Service: main
[Error]        Error: The command '/bin/sh -c apt-get update &&     apt-get -y install         build-essential         curl         git-core         libffi-dev         libssl-dev         matchbox         net-tools         nginx-light         omxplayer         psmisc         python-dev         python-imaging         python-netifaces         python-simplejson         libraspberrypi0         ifupdown         sqlite3         uzbl         x11-xserver-utils         xserver-xorg &&     apt-get clean' returned a non-zero code: 100
[Error]    Not deploying release.

remote: error: hook declined to update refs/heads/master
To git.balena-cloud.com:gh_shukhratk/PiTest3.git
! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'gh_shukhratk@git.balena-cloud.com:gh_shukhratk/PiTest3.git'`

**Comment by vpetersson** [comment]
@ShukhratK From the logs it looks like you're on the production release. This has not yet been merged into there, so switch to the master branch, pull down the latest changes, and you should be good to go.

**Comment by ShukhratK** [comment]
@vpetersson 
sounds good
thx again

**Comment by ShukhratK** [comment]
@vpetersson same error with the master fork

**Comment by vpetersson** [comment]
Can you paste the output of the following commands?

```
$ git pull
$ git rev-parse --short HEAD 
$ git branch
$ git status
```

**Comment by ShukhratK** [comment]
Already up to date.
79b0818
* master
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

**Comment by vpetersson** [comment]
Are you using a fork? If so, that would explain it. The latest upstream hash on master is 093f594. Your hash, (79b0818) does not have the Balena fixes in it.

**Comment by ShukhratK** [comment]
i see. how do i fix that?

**Comment by ShukhratK** [comment]
@vpetersson i am using a fork.

**Comment by vpetersson** [comment]
Yeah so you either need to [merge in the latest changes](https://help.github.com/en/articles/syncing-a-fork) or not use a fork.

**Comment by ShukhratK** [comment]
sorry, this is probably a noobie question: i am getting the following error now

fatal: 'upstream' does not appear to be a git repository

**Comment by vpetersson** [comment]
Please move this discussion to the [forum](https://forums.screenly.io/) as this is out of scope for this particular issue.

**Comment by ShukhratK** [comment]
will do. thx again

**Comment by vpetersson** [comment]
Closing in favour of  #1126/
