### ISSUE TITLE
Automatically set "End date" 

### ISSUE THREAD

**Issue by madsrh** [Screenly/screenly-ose#1119]
This is a feature request / enhancement 

#### Overview of the Issue

When uploading a new asset, the dates (start and end) are by default set to the current date. When changing the "Start date" you get a notification that `end date should be after start date` but the end date is unchanged. It obviously isn't possible to set the end date before the start date, so why not link the two, so the end date always will show the same date as the starte date. 

![image](https://user-images.githubusercontent.com/3986894/57842084-1d4b0400-77cc-11e9-964e-3d8ac712f0b4.png)

It's not much trouble to change the end date for the user, but it would be a nice usability improvement if the two were linked :)

**Comment by vpetersson** [comment]
Thanks for reporting!

**Comment by rusko124** [comment]
Should be resolved here #1156.
I think we can close this.
