### ISSUE TITLE
Add Github design

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1120]
This needs to be populated:

![Screenshot_2019-05-16 Screenly screenly-ose](https://user-images.githubusercontent.com/357664/57851683-18408180-77d9-11e9-911d-0318f42bbcc2.png)

Here's the template link:
![repository-open-graph-template](https://user-images.githubusercontent.com/357664/57851749-3e662180-77d9-11e9-83da-a35e09a277eb.png)

**Comment by L4cko** [comment]
![-Open Source Edition-logo-white](https://user-images.githubusercontent.com/45398471/57864115-9ca3fc00-77fb-11e9-859e-bcf6ba824ef5.jpg)
![Open Source Edition-icon-white](https://user-images.githubusercontent.com/45398471/57864116-9d3c9280-77fb-11e9-82f4-aad9c7503c85.jpg)
![Open Source Edition-icon](https://user-images.githubusercontent.com/45398471/57864117-9d3c9280-77fb-11e9-8605-c9f3c8bc34c2.jpg)
![Uploading Open Source Edition-logo.jpg…]()
