### ISSUE TITLE
OpenGL Driver on experimental?

### ISSUE THREAD

**Issue by danpoltawski** [Screenly/screenly-ose#1134]
Is it possible to use Screenly-OSE on experimental with the opengl drivers? 

I'd really like to see if with the experimental drivers, a page we want to display with some CSS animation would render..

### Environment

* Raspberry Pi Hardware Version: Pi 3 Model B+
* Screenly OSE Version: OSE experimental

**Comment by vpetersson** [comment]
My understanding is that we're already using hardware accelleration in the experimental branch (at least to the extent supported by QT). I don't know if that translates to full OpeNGL support or not.

**Comment by danpoltawski** [comment]
When I switch to the opengl driver with raspi-config, the system boots up into a black screen - just trying to debug how to work out where the problem is

**Comment by vpetersson** [comment]
Interesting. Could potentially be some docker flag or `/dev/` mapping we need to make.

**Comment by danpoltawski** [comment]
I'm trying to understand the architecture in order to try and debug - is Xorg running in the viewer container?

**Comment by vpetersson** [comment]
It's actually not using xorg. It's a QT app, so it's talking directly to frame buffer.
