### ISSUE TITLE
localisation of date display

### ISSUE THREAD

**Issue by pooh22** [Screenly/screenly-ose#1142]
Please reopen #599 (Localise date format)
It would be really nice if the date could be displayed in a more intuitive form for the people using it. In the Netherlands, we're really used to day-month-year format, not the US format month/day/year.

**Comment by rusko124** [comment]
Hi @pooh22 !
Feature was added. Try to upgrade and let me know your opinion.

**Comment by pooh22** [comment]
Thanks @rusko124 It will be a while before I have time to test it, but it is much appreciated!
