### ISSUE TITLE
Unable to run tvservices command

### ISSUE THREAD

**Issue by singh87** [Screenly/screenly-ose#1151]
#### Overview of the Issue

I am trying to setup Screenly with balena. The problem is that HDMI signal is not showing up on the display. I want to be able to get the EDID information of the connected monitor/TV to troubleshoot this issue. (forced HDMI, hdmi_group, and hdmi_mode did not work) The display is a Samsung DC43J

I thought I would just be able to run the tvservices commands in the balena host os terminal but the command was not found.

Any help would be appreciated

**Comment by vpetersson** [comment]
@singh87 We've been looking to add support for `tvservice` on Balena, but are yet to get there (as we had more pressing issues to deal with). 

For the time being, I would suggest you use the regular disk image to make sure everything works (as it includes `tvservice`).

**Comment by altontoth** [comment]
So,I just updated my install of Screenly,and I assume Docker causes a similar issue? I'm getting the exact same problem on one device, and it's the only one I've applied an update to as of today.

**Comment by vpetersson** [comment]
@altontoth Yes, i believe the dockerized version broke `tvservice` for now. It should be possible to work around this in the future.
