### ISSUE TITLE
Issue with Balena

### ISSUE THREAD

**Issue by car-thee-ca** [Screenly/screenly-ose#1167]
I have been trying to use screenlyOSE on balena cloud . After ive successfully performed balena push, and got the unicorn image, i have been waiting for a really long time but screenly doesnt appear in my page. I tried to access my public URL and it gives off an error that “Device does not have registered vpn tunnel endpoint” ive been following the tutorial from this link: https://www.balena.io/blog/deploy-free-digital-signage-software-screenly-ose/

**Comment by car-thee-ca** [comment]
![Screenshot (76)](https://user-images.githubusercontent.com/42571681/59899726-674e8780-9413-11e9-87ce-618548f868c2.png)
This is the exact error message that i am receiving.

I did get build finished. I unzipped the github screenly-ose-master and performed balena push. Ive been waiting ever since yesterday evening but the screenly page does not appear on the monitor connected to my raspberry pi
![Screenshot (77)](https://user-images.githubusercontent.com/42571681/59899811-c6140100-9413-11e9-879a-ecb50dc43588.png)

**Comment by vpetersson** [comment]
@remingtona - can you see if you can reproduce this?

**Comment by RemingtonA** [comment]
Can do!

**Comment by novasea** [comment]
I got the exact same issue. When I check the balena device trying to run screenly, through the balena web interface, the logs says it cant find some command, and that there's a syntax error near unexpected token.

`26.06.19 11:19:02 (+0200)  screenly-server  /tmp/screenly/bin/start_balena.sh: line 2: $'\r': command not found
26.06.19 11:19:02 (+0200)  screenly-server  /tmp/screenly/bin/start_balena.sh: line 3: syntax error near unexpected token `$'{\r''
'6.06.19 11:19:02 (+0200)  screenly-server  /tmp/screenly/bin/start_balena.sh: line 3: `run_setup () {
26.06.19 11:19:03 (+0200) Service exited 'screenly-server sha256:ca1430a370504fa7e178f951562e8490d5bb6ab5dc08c77ddd1f1854db666128'
26.06.19 11:19:14 (+0200) Restarting service 'screenly-viewer sha256:d60e6aed47c824e8917b0cc0bf3d088d0c909c772678c9cca79568d4d06cd8c4'
26.06.19 11:19:14 (+0200)  screenly-viewer  /tmp/screenly/bin/start_balena.sh: line 2: $'\r': command not found
26.06.19 11:19:14 (+0200)  screenly-viewer  /tmp/screenly/bin/start_balena.sh: line 3: syntax error near unexpected token `$'{\r''
'6.06.19 11:19:14 (+0200)  screenly-viewer  /tmp/screenly/bin/start_balena.sh: line 3: `run_setup () {
26.06.19 11:19:14 (+0200)  screenly-websocket  /tmp/screenly/bin/start_balena.sh: line 2: $'\r': command not found
26.06.19 11:19:14 (+0200)  screenly-websocket  /tmp/screenly/bin/start_balena.sh: line 3: syntax error near unexpected token `$'{\r''
'6.06.19 11:19:14 (+0200)  screenly-websocket  /tmp/screenly/bin/start_balena.sh: line 3: `run_setup () {`

**Comment by vpetersson** [comment]
@novasea I'm not sure that's the same error. That looks very much like a Windows formatting error (i.e. a file edited on Windows, that broke the newlines).

**Comment by vpetersson** [comment]
@RemingtonA were you able to reproduce this?

**Comment by rusko124** [comment]
![first](https://user-images.githubusercontent.com/17593028/60430567-70afcf00-9c1f-11e9-8171-9e8b86fbccb5.png)
![second](https://user-images.githubusercontent.com/17593028/60430570-70afcf00-9c1f-11e9-9e7c-cc2dfe041a06.png)

Works good for me, `9bdd4e8` release version

**Comment by homerosbart2** [comment]
> ![first](https://user-images.githubusercontent.com/17593028/60430567-70afcf00-9c1f-11e9-8171-9e8b86fbccb5.png)
> ![second](https://user-images.githubusercontent.com/17593028/60430570-70afcf00-9c1f-11e9-9e7c-cc2dfe041a06.png)
> 
> Works good for me, `9bdd4e8` release version

**Is this in Windows?**

**Comment by rusko124** [comment]
> > ![first](https://user-images.githubusercontent.com/17593028/60430567-70afcf00-9c1f-11e9-8171-9e8b86fbccb5.png)
> > ![second](https://user-images.githubusercontent.com/17593028/60430570-70afcf00-9c1f-11e9-9e7c-cc2dfe041a06.png)
> > Works good for me, `9bdd4e8` release version
> 
> **Is this in Windows?**

Ubuntu 18, but I also reproduced all steps on Windows 8.
![изображение](https://user-images.githubusercontent.com/17593028/61269003-171ed700-a7bf-11e9-8114-832a358d1dcf.png)
