### ISSUE TITLE
Screenly-OSE and wifi-connect

### ISSUE THREAD

**Issue by bitos2002** [Screenly/screenly-ose#1171]
#### Overview of the Issue
 
 Screenly-OSE and wifi-connect
 
#### Reproduction Steps

Hello,
I want to use screenly-ose on balena container, but I want to use wifi-connect.
Is wifi-connect include in screenly-ose last version.
I have tried to merge on one container screenly-ose an wifi-container, but i have not exit on it.
Anyone has done this and can help me or share the project.

Thanks !!!!

**Comment by rusko124** [comment]
Hey @bitos2002 !
I don't think it's that obvious. A possible solution can be found here I think https://www.balena.io/docs/reference/cli/

**Comment by madsrh** [comment]
Can we close this issue?

**Comment by vpetersson** [comment]
@madsrh Yeah i think so. 

Closing this out.
