### ISSUE TITLE
WoTT installer prompt backwards. 

### ISSUE THREAD

**Issue by willworkforicecream** [Screenly/screenly-ose#1174]
When installing and answering to the WoTT install prompt, installer.sh will do the opposite of what is intended. 

#### Reproduction Steps
Run
`$ bash <(curl -sL https://screenly.io/install-ose.sh)`
on a fresh Rasbian lite.

### Environment

* Raspberry Pi Hardware Version: 3b+

Looking at installer.sh, it looks like this is backwards so if you answer that yes, you do want to install WoTT, it Won'TT and if you do want to install Wott, it will. 

```
echo && read -p "Would you like to install the WoTT agent to help you manage security of your Raspberry Pi? (y/N)" -n 1 -r -s WOTT && echo
if [ "$WOTT" != 'y' ]; then
    curl -s https://packagecloud.io/install/repositories/wott/agent/script.deb.sh | sudo bash
    sudo apt install wott-agent
fi
```

**Comment by vpetersson** [comment]
@willworkforicecream good catch! Pushed a fix. I completely missed that.
