### ISSUE TITLE
Screenly IP changes 

### ISSUE THREAD

**Issue by prwiley** [Screenly/screenly-ose#1175]
I installed Screenly OSE from NOOBS and got it to work just fine at first.

However, the IP address for the Screenly controls stopped responding after a bit -- Chrome said the address could not be reached.

I rebooted the pi and got a new IP address. Is it possible that the IP was somehow changed before the reboot as Screenly was running?

Rasberry Pi B

**Comment by vpetersson** [comment]
The IP is not managed by Screenly - It's managed by the operating system (and received from the DHCP server). Hence, depending on the configuration, it might very well change even during run time.
