### ISSUE TITLE
Webbrowser 

### ISSUE THREAD

**Issue by Micbui** [Screenly/screenly-ose#1176]
Where and how can I change the Webbrower? 

In addition I like to intrate a ssl certificate? Does anyone have an idea how I can do it?

**Comment by vpetersson** [comment]
> Where and how can I change the Webbrower?

You can't. It's deeply integrated into the stack.

> In addition I like to intrate a ssl certificate? Does anyone have an idea how I can do it?

You'd have to install it as a trusted system certificate. That way it should in theory work.
