### ISSUE TITLE
HLS Video Support (or working hls player)

### ISSUE THREAD

**Issue by unmanagedtn** [Screenly/screenly-ose#1179]
#### Overview of the Issue

Trying to play HLS stream using videojs player

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Add 'https://082b07eb-6dc0-44be-bdc5-faf3ddafb129.htmlpasta.com' as an asset 
2. Turn it on
* Wait for the asset toblack box to  show up on the screen
### Environment

* Raspberry Pi Hardware Version: v2 
* Screenly OSE Version:

Load Average | Free Space | Uptime | Monitor Info | Display Power | Raspberry Model | Screenly Version | MAC address
-- | -- | -- | -- | -- | -- | -- | --
0.11 | 12G | 0 days and 9.31 hours | state 0x12000a [HDMI CEA (16) RGB lim 16:9], 1920x1080 @ 60.00Hz, progressive | On | Model 2B Revision: 1.1 Ram: 1 GB Embest | production@618864d | b8:27:eb:bc:57

**Comment by vpetersson** [comment]
This is expected. Videos embedded in an web page is not supported. The Pi is simply not powerful enough to do that.
