### ISSUE TITLE
ERR_CONNECTION_REFUSED after update (see #361) - rerunning upgrade not working.

### ISSUE THREAD

**Issue by WTPLJim** [Screenly/screenly-ose#1183]
#### Overview of the Issue:
    Ran upgrade today, splash screen comes up and then TV goes blank. I tried accessing the 8080 page, and it refused connection. I assume at this time, the screen going blank after showing commands after splash screen is simply that there is no active assets in the 8080 page.

#### Reproduction Steps
Upgraded, see splash screen, see some commands, screen blanks, attempt login to 8080 via another browser, told connection refused.

### Environment

* Raspberry Pi Hardware Version: Raspberry Pi 2
* Screenly OSE Version: Jessie

**Comment by WTPLJim** [comment]
**Note: Service is failing to load!!


pi@raspberrypi:~ $ sudo systemctl
  UNIT                      LOAD   ACTIVE     SUB          DESCRIPTION
  proc-sys-fs-binfmt_misc.automount loaded active     waiting      Arbitrary Exe
  sys-devices-platform-soc-3f201000.uart-tty-ttyAMA0.device loaded active     pl
  sys-devices-platform-soc-3f202000.sdhost-mmc_host-mmc0-mmc0:0001-block-mmcblk0
  sys-devices-platform-soc-3f202000.sdhost-mmc_host-mmc0-mmc0:0001-block-mmcblk0
  sys-devices-platform-soc-3f202000.sdhost-mmc_host-mmc0-mmc0:0001-block-mmcblk0
  sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.1-1\x2d1.1:1.0-net-et
  sys-devices-virtual-sound-card0.device loaded active     plugged      /sys/dev
  sys-devices-virtual-tty-ttyprintk.device loaded active     plugged      /sys/d
  sys-module-configfs.device loaded active     plugged      /sys/module/configfs
  sys-subsystem-net-devices-eth0.device loaded active     plugged      SMSC9512/
  -.mount                   loaded active     mounted      /
  boot.mount                loaded active     mounted      /boot
  dev-mqueue.mount          loaded active     mounted      POSIX Message Queue F
  run-user-1000.mount       loaded active     mounted      /run/user/1000
  sys-kernel-config.mount   loaded active     mounted      Configuration File Sy
  sys-kernel-debug.mount    loaded active     mounted      Debug File System
  systemd-ask-password-plymouth.path loaded active     waiting      Forward Pass
  systemd-ask-password-wall.path loaded active     waiting      Forward Password
  session-c2.scope          loaded active     running      Session c2 of user pi
  asplashscreen.service     loaded active     exited       LSB: Show custom spla
  avahi-daemon.service      loaded active     running      Avahi mDNS/DNS-SD Sta
  console-setup.service     loaded active     exited       LSB: Set console font
lines 1-23
  UNIT                      LOAD   ACTIVE     SUB          DESCRIPTION
  proc-sys-fs-binfmt_misc.automount loaded active     waiting      Arbitrary Executable
  sys-devices-platform-soc-3f201000.uart-tty-ttyAMA0.device loaded active     plugged      /sys/devices/platform
  sys-devices-platform-soc-3f202000.sdhost-mmc_host-mmc0-mmc0:0001-block-mmcblk0-mmcblk0p1.device loaded active     plug
  sys-devices-platform-soc-3f202000.sdhost-mmc_host-mmc0-mmc0:0001-block-mmcblk0-mmcblk0p2.device loaded active     plug
  sys-devices-platform-soc-3f202000.sdhost-mmc_host-mmc0-mmc0:0001-block-mmcblk0.device loaded active     plugged      /
  sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.1-1\x2d1.1:1.0-net-eth0.device loaded active     plugged
  sys-devices-virtual-sound-card0.device loaded active     plugged      /sys/devices/virtual/
  sys-devices-virtual-tty-ttyprintk.device loaded active     plugged      /sys/devices/virtual/
  sys-module-configfs.device loaded active     plugged      /sys/module/configfs
  sys-subsystem-net-devices-eth0.device loaded active     plugged      SMSC9512/9514 Fast Et
  -.mount                   loaded active     mounted      /
  boot.mount                loaded active     mounted      /boot
  dev-mqueue.mount          loaded active     mounted      POSIX Message Queue F
  run-user-1000.mount       loaded active     mounted      /run/user/1000
  sys-kernel-config.mount   loaded active     mounted      Configuration File Sy
  sys-kernel-debug.mount    loaded active     mounted      Debug File System
  systemd-ask-password-plymouth.path loaded active     waiting      Forward Password Requ
  systemd-ask-password-wall.path loaded active     waiting      Forward Password Requ
  session-c2.scope          loaded active     running      Session c2 of user pi
  asplashscreen.service     loaded active     exited       LSB: Show custom spla
  avahi-daemon.service      loaded active     running      Avahi mDNS/DNS-SD Sta
  console-setup.service     loaded active     exited       LSB: Set console font
  cron.service              loaded active     running      Regular background pr
  dbus.service              loaded active     running      D-Bus System Message
  dhcpcd.service            loaded active     running      dhcpcd on all interfa
  dphys-swapfile.service    loaded active     exited       LSB: Autogenerate and
  fake-hwclock.service      loaded active     exited       Restore / save the cu
  getty@tty1.service        loaded active     running      Getty on tty1
  kbd.service               loaded active     exited       LSB: Prepare console
  keyboard-setup.service    loaded active     exited       LSB: Set preliminary
  kmod-static-nodes.service loaded active     exited       Create list of requir
  matchbox.service          loaded active     running      X11
  ModemManager.service      loaded active     running      Modem Manager
  networking.service        loaded active     exited       LSB: Raise network in
  ntp.service               loaded active     running      LSB: Start NTP daemon
  polkitd.service           loaded active     running      Authenticate and Auth
  raspi-config.service      loaded active     exited       LSB: Switch to ondema
  rc-local.service          loaded active     exited       /etc/rc.local Compati
  rsyslog.service           loaded active     running      System Logging Servic
● screenly-viewer.service   loaded failed     failed       Screenly Viewer
  screenly-web.service      loaded activating auto-restart Screenly Web UI
● screenly_net_mgr.service  loaded failed     failed       LSB: Screenly network
  serial-getty@ttyAMA0.service loaded active     running      Serial Getty on ttyAM
  ssh.service               loaded active     running      OpenBSD Secure Shell
  systemd-fsck-root.service loaded active     exited       File System Check on
  systemd-fsck@dev-mmcblk0p1.service loaded active     exited       File System Check on
  systemd-journald.service  loaded active     running      Journal Service
  systemd-logind.service    loaded active     running      Login Service
  systemd-modules-load.service loaded active     exited       Load Kernel Modules
  systemd-random-seed.service loaded active     exited       Load/Save Random Seed
  systemd-remount-fs.service loaded active     exited       Remount Root and Kern
  systemd-setup-dgram-qlen.service loaded active     exited       Increase datagram que
  systemd-sysctl.service    loaded active     exited       Apply Kernel Variable
  systemd-tmpfiles-setup-dev.service loaded active     exited       Create Static Device
  systemd-tmpfiles-setup.service loaded active     exited       Create Volatile Files
  systemd-udev-trigger.service loaded active     exited       udev Coldplug all Dev
  systemd-udevd.service     loaded active     running      udev Kernel Device Ma
  systemd-update-utmp.service loaded active     exited       Update UTMP about Sys
  systemd-user-sessions.service loaded active     exited       Permit User Sessions
  triggerhappy.service      loaded active     running      LSB: triggerhappy hot
  udev-finish.service       loaded active     exited       Copy rules generated
  user@1000.service         loaded active     running      User Manager for UID
  X.service                 loaded active     running      X11
  -.slice                   loaded active     active       Root Slice
  system-getty.slice        loaded active     active       system-getty.slice
  system-serial\x2dgetty.slice loaded active     active       system-serial\x2dgett
  system-systemd\x2dfsck.slice loaded active     active       system-systemd\x2dfsc
  system.slice              loaded active     active       System Slice
  user-1000.slice           loaded active     active       user-1000.slice
  user.slice                loaded active     active       User and Session Slic
  avahi-daemon.socket       loaded active     running      Avahi mDNS/DNS-SD Sta
  dbus.socket               loaded active     running      D-Bus System Message
  syslog.socket             loaded active     running      Syslog Socket
  systemd-initctl.socket    loaded active     listening    /dev/initctl Compatib
  systemd-journald-dev-log.socket loaded active     running      Journal Socket (/dev/
  systemd-journald.socket   loaded active     running      Journal Socket
  systemd-shutdownd.socket  loaded active     listening    Delayed Shutdown Sock
  systemd-udevd-control.socket loaded active     running      udev Control Socket
  systemd-udevd-kernel.socket loaded active     running      udev Kernel Socket
  basic.target              loaded active     active       Basic System
  cryptsetup.target         loaded active     active       Encrypted Volumes
  getty.target              loaded active     active       Login Prompts
  graphical.target          loaded active     active       Graphical Interface
  local-fs-pre.target       loaded active     active       Local File Systems (P
  local-fs.target           loaded active     active       Local File Systems
  multi-user.target         loaded active     active       Multi-User System
  network-online.target     loaded active     active       Network is Online
  network.target            loaded active     active       Network
  paths.target              loaded active     active       Paths
  remote-fs-pre.target      loaded active     active       Remote File Systems (
  remote-fs.target          loaded active     active       Remote File Systems
  slices.target             loaded active     active       Slices
  sockets.target            loaded active     active       Sockets
  sound.target              loaded active     active       Sound Card
  swap.target               loaded active     active       Swap
  sysinit.target            loaded active     active       System Initialization
  timers.target             loaded active     active       Timers
  systemd-tmpfiles-clean.timer loaded active     waiting      Daily Cleanup of Temp

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

98 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.

**Comment by WTPLJim** [comment]
Some more...

pi@raspberrypi:~ $ sudo service screenly-viewer start
pi@raspberrypi:~ $ sudo service screenly_net_mgr start
Job for screenly_net_mgr.service failed. See 'systemctl status screenly_net_mgr.                   service' and 'journalctl -xn' for details.
pi@raspberrypi:~ $ journalctl -xn
No journal files were found.
pi@raspberrypi:~ $ systemctl status screenly_net_mgr.service
● screenly_net_mgr.service - LSB: Screenly network config tool
   Loaded: loaded (/etc/init.d/screenly_net_mgr)
   Active: failed (Result: exit-code) since Mon 2019-07-08 13:09:17 EDT; 5min ag                   o
  Process: 8916 ExecStart=/etc/init.d/screenly_net_mgr start (code=exited, statu                   s=203/EXEC)
pi@raspberrypi:~ $

**Comment by vpetersson** [comment]
@rusko124

**Comment by rusko124** [comment]
Hey @WTPLJim !
`screenly_net_mgr.service` looks like a old service.
Good and fast solution for you I think will be installing the latest version from https://github.com/Screenly/screenly-ose/releases/tag/0.17.
If you still want to keep the current version then run this command `cd ~/screenly && ./bin/run_upgrade.sh` and after that provide me logs of updating, please.

**Comment by WTPLJim** [comment]
Okay - is there a command path via SSH to upgrade to the newest Sprint?
- Pi is in an engineered "security" cage that can be a bit rough to access.

I'll start the upgrade tomorrow if I need to access the physical device.

Thanks, running update on current version now.

**Comment by WTPLJim** [comment]
Log of upgrade:


pi@raspberrypi:~ $ cd ~/screenly && ./bin/run_upgrade.sh
   _____                           __         ____  _____ ______
  / ___/_____________  ___  ____  / /_  __   / __ \/ ___// ____/
  \__ \/ ___/ ___/ _ \/ _ \/ __ \/ / / / /  / / / /\__ \/ __/
 ___/ / /__/ /  /  __/  __/ / / / / /_/ /  / /_/ /___/ / /___
/____/\___/_/   \___/\___/_/ /_/_/\__, /   \____//____/_____/
                                 /____/
Screenly OSE requires a dedicated Raspberry Pi / SD card.
You will not be able to use the regular desktop environment once installed.

Do you still want to continue? (y/N)
Would you like to use the experimental branch? It contains the last major changes, such as the new browser and migrating to Docker (y/N)

Do you want Screenly to manage your network? This is recommended for most users because this adds features to manage your network. (Y/n)

Would you like to install the WoTT agent to help you manage security of your Raspberry Pi? (y/N)

Would you like to perform a full system upgrade as well? (y/N)
+ sudo mkdir -p /etc/ansible
+ echo -e '[local]\nlocalhost ansible_connection=local'
+ sudo tee /etc/ansible/hosts
+ '[' '!' -f /etc/locale.gen ']'
+ sudo sed -i s/apt.screenlyapp.com/archive.raspbian.org/g /etc/apt/sources.list
+ sudo apt-get update
Get:1 http://mirrordirector.raspbian.org jessie InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org jessie InRelease [22.9 kB]
Get:3 http://mirrordirector.raspbian.org jessie/main armhf Packages [9,539 kB]
Get:4 http://archive.raspberrypi.org jessie/main armhf Packages [170 kB]
Get:5 http://archive.raspberrypi.org jessie/ui armhf Packages [58.9 kB]
Ign http://archive.raspberrypi.org jessie/main Translation-en_US
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_US
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Fetched 9,806 kB in 42s (230 kB/s)
Reading package lists... Done
+ sudo apt-get purge -y python-setuptools python-pip python-pyasn1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'python-pip' is not installed, so not removed
Package 'python-pyasn1' is not installed, so not removed
Package 'python-setuptools' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 256 not upgraded.
+ sudo apt-get install -y python-dev git-core libffi-dev libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
git-core is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.
python-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 256 not upgraded.
+ curl -s https://bootstrap.pypa.io/get-pip.py
+ sudo python
Traceback (most recent call last):
  File "<stdin>", line 21492, in <module>
  File "<stdin>", line 197, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpO1RmJ_/pip.zip/pip/_internal/__init__.py", line 40, in <module>
  File "/tmp/tmpO1RmJ_/pip.zip/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/tmp/tmpO1RmJ_/pip.zip/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "/tmp/tmpO1RmJ_/pip.zip/pip/_internal/commands/__init__.py", line 6, in <module>
  File "/tmp/tmpO1RmJ_/pip.zip/pip/_internal/commands/completion.py", line 6, in <module>
  File "/tmp/tmpO1RmJ_/pip.zip/pip/_internal/cli/base_command.py", line 20, in <module>
  File "/tmp/tmpO1RmJ_/pip.zip/pip/_internal/download.py", line 37, in <module>
  File "/tmp/tmpO1RmJ_/pip.zip/pip/_internal/utils/glibc.py", line 3, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /usr/lib/python2.7/lib-dynload/_ctypes.arm-linux-gnueabihf.so: undefined symbol: PyNumber_AsSsize_t
+ '[' Y == y ']'
+ export MANAGE_NETWORK=false
+ MANAGE_NETWORK=false
+ sudo pip install ansible==2.8.1
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/lib/python2.7/dist-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 7, in <module>
    import csv
  File "/usr/lib/python2.7/csv.py", line 8, in <module>
    from _csv import Error, __version__, writer, reader, register_dialect, \
ImportError: /usr/lib/python2.7/lib-dynload/_csv.arm-linux-gnueabihf.so: undefined symbol: PySequence_Check
+ ansible localhost -m git -a 'repo=https://github.com/screenly/screenly-ose.git dest=/home/pi/screenly version=experimental'
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 41, in <module>
    from multiprocessing import Lock
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 84, in <module>
    import _multiprocessing
ImportError: /usr/lib/python2.7/lib-dynload/_multiprocessing.arm-linux-gnueabihf.so: undefined symbol: PyFloat_AsDouble
+ cd /home/pi/screenly/ansible
+ ansible-playbook site.yml --skip-tags enable-ssl
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 41, in <module>
    from multiprocessing import Lock
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 84, in <module>
    import _multiprocessing
ImportError: /usr/lib/python2.7/lib-dynload/_multiprocessing.arm-linux-gnueabihf.so: undefined symbol: PyFloat_AsDouble
+ sudo apt-get autoclean
Reading package lists... Done
Building dependency tree
Reading state information... Done
+ sudo apt-get clean
+ sudo find /usr/share/doc -depth -type f '!' -name copyright -delete
+ sudo find /usr/share/doc -empty -delete
+ sudo rm -rf /usr/share/man /usr/share/groff /usr/share/info /usr/share/lintian /usr/share/linda /var/cache/man
+ sudo find /usr/share/locale -type f '!' -name en '!' -name 'de*' '!' -name 'es*' '!' -name 'ja*' '!' -name 'fr*' '!' -name 'zh*' -delete
+ sudo find /usr/share/locale -mindepth 1 -maxdepth 1 '!' -name 'en*' '!' -name 'de*' '!' -name 'es*' '!' -name 'ja*' '!' -name 'fr*' '!' -name 'zh*' -exec rm -r '{}' ';'
+ cd /home/pi/screenly
+ git rev-parse HEAD
++ git rev-parse --abbrev-ref HEAD
++ git rev-parse --short HEAD
++ lsb_release -a
No LSB modules are available.
+ echo -e 'Screenly version: production@85732dd\nDistributor ID:        Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie'
+ set +x
Installation completed.

**Comment by WTPLJim** [comment]
Upgraded to Sprint9. 
I have a splash screen; cannot connect to web interface (IP:8080).
Nor can I access via SSH.

I am able to ping on IP (172.29.53.102)

**Comment by WTPLJim** [comment]
Got it... removed the Port 8080 on flash!

**Comment by WTPLJim** [comment]
Up and working again, thanks!

**Comment by WTPLJim** [comment]
Before closing.... SSH is no longer connecting on new version.
Is this now on a non standard port?

**Comment by vpetersson** [comment]
> Before closing.... SSH is no longer connecting on new version.
> Is this now on a non standard port?

SSH has been disabled by default for some time in Raspbian (and Screenly OSE). 

You need to manually enable it using `sudo raspi-config`.
