### ISSUE TITLE
Feature Request: Test Travis CI on Ubuntu 18.04

### ISSUE THREAD

**Issue by gtrak** [Screenly/screenly-ose#1184]
The Travis CI config references 14.04, but 18.04 is the current LTS release, and more representative of developer machines in 2019.

The proposal is to target 18.04 in CI.

**Comment by vpetersson** [comment]
@gtrak sensible feature request.

**Comment by vpetersson** [comment]
@gtrak we've now bumped up to 16.04 (see #1208). I presume that @rusko124 had a good reason not to bump to 18.04 right away.
