### ISSUE TITLE
Issues with wired network if no cable is inserted on boot

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1186]
#### Overview of the Issue

If you boot the device without an Ethernet cable and then insert one after the hotspot has appeared, the web interface will not be accessible as you get to the hotspot.

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Boot the system without an Ethernet cable
* Wait for the hotspot splash screen to appear
* Insert the network cable

##### Behavior

* Hotspot should disappear

##### Behavior

* Hotspot remains

### Environment

* Raspberry Pi Hardware Version: 3B
* Screenly OSE Version: Latest production release

**Comment by rusko124** [comment]
Fix merged, Issue can be close.
