### ISSUE TITLE
Upgrade to Raspbian Buster

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1187]
The Raspberry Pi 4 Model B does not seem to boot on Stretch. We need to upgrade to Buster.

**Comment by klarkizim** [comment]
Hi Victor, still learning how to follow on Git, 
where will i find the 'buster' image / instructions on upgrading ?

**Comment by vpetersson** [comment]
@klarkizim No need to know anything about `git`. You can find images [here](https://github.com/Screenly/screenly-ose/releases). Just do a backup and then restore. That's the easiest way to do it.

**Comment by klarkizim** [comment]
thanks so much, will give it a try

**Comment by vpetersson** [comment]
Correct - the Pi 4 is not fully supported yet. The GPU is completely different in the Pi 4, such that `ompxlayer` now breaks for video playback.

**Comment by alastairbattrick** [comment]
> Correct - the Pi 4 is not fully supported yet. The GPU is completely different in the Pi 4, such that `ompxlayer` now breaks for video playback.

Is there an ETA on it being resolved?

**Comment by vpetersson** [comment]
It looks like `omxplayer` now supports the Pi 4 (but not in 4k). Hence we could in theory add support for it once we've unblocked some other things. Tl;dr is that the reason why it's taken a while is because Buster + Pi 4 broke a few components that were out of our control. Check the roadmap for more details.

**Comment by codmdu** [comment]
Is there a ETA for full Pi 4 Support ? (i cant find a ETA on the roadmap)

**Comment by vpetersson** [comment]
@codmdu This is the ticket for it, so yes, it is on the roadmap (i.e. [Sprint 11](https://github.com/Screenly/screenly-ose/projects/4)).

**Comment by hoerms** [comment]
Hi. Do you have any idea when sprint 11 will be finished. Regards Hermann S.

**Comment by vpetersson** [comment]
No update on this as of right now, unfortunately. COVID as forced us to tighten our budgets.

**Comment by ealmonte32** [comment]
https://github.com/Screenly/screenly-ose/issues/1355#issuecomment-696388611
