### ISSUE TITLE
504 gateway time-out

### ISSUE THREAD

**Issue by TheCazz** [Screenly/screenly-ose#1194]
Hi
I have install the latest version of screenly OSE and I have got it running for a friend

At home I have add som rtsp streaming and got it to work and I have now done that on for my friends screenly but now I get 504 gateway time-out and not sure how to see how to fix the problem.
I have look at journalctl but it does not say so much when I do not know what to look after.

The only think I can think of that is different between his and my Raspberry Pi is that my is a little new then his (My is 3+ and he is 3) other then that is not so much change.

**Comment by vpetersson** [comment]
@TheCazz Try upgrading to the latest development version to see if that resolves the issue.

**Comment by TheCazz** [comment]
hmm sorry if it sound stupid but how do I do that?

I guess if I use this

`bash <(curl -sL https://www.screenly.io/install-ose.sh)`

then it not the dev it trying to install?

**Comment by vpetersson** [comment]
That's the right steps - just make sure to answer `Y` to if you want to install the development version.

**Comment by TheCazz** [comment]
After a update now I get 502 Bad Gateway

**Comment by rusko124** [comment]
Hey @TheCazz !
![изображение](https://user-images.githubusercontent.com/17593028/61348498-c07ad100-a882-11e9-8fd4-5f76ea812ec2.png)

Could your provide logs(`journalctl -u screenly-web.service`), please?
Also would be good if you said all steps to reproduce the problem, and what device do you use?

**Comment by TheCazz** [comment]
Well first I did install the image to SD card and Power on
It looks like it works so I have to after that force HDMI (Have VGA adapter) and then rotate the screen
Everything looks fine so I did add a rstp address that I know is working (Have try it on VLC) and after that I get the error. so I did run the manual update and did say yes to almost everything (but no to update the raspberry system). I did take sometime but after a reboot I get now 502 error.


When I run the journal command it say nothing
`-- No enteries --`

So I guess the screenly does not start?


when I look for the model I get
`Raspberry Pi Model B Plus Rev.12`
so is not so old version of raspberry pi

My friend want to have like me rstp streaming but I was thinking if I try to remove the rstp and see if it works but I can't do that, Maybe is possible att edit from the terminal but not sure.

**Comment by rusko124** [comment]
@TheCazz As far as I understand you got the error right after adding the rstp asset?
Then could you provide the full logs?`journalctl`

**Comment by TheCazz** [comment]
![screenly](https://user-images.githubusercontent.com/3855207/61452612-7ebe5900-a95c-11e9-93ce-a2dc851b4c3a.PNG)

Hmm well no but I maybe do something wrong?

**Comment by rusko124** [comment]
@TheCazz I mean without any unit. Just `journalctl` :)

**Comment by TheCazz** [comment]
ahh ok but what are I going to look after. is going to be many line of info :)
All I can see now is 
![screenly](https://user-images.githubusercontent.com/3855207/61453058-7d416080-a95d-11e9-9e92-ce83f23f67c3.PNG)
wlan info (I going to use wifi later but now is ethernet connected)

**Comment by rusko124** [comment]
@TheCazz Please put the logs to somewhere(online text paste service or textfile)

**Comment by TheCazz** [comment]
ok here it is but it does not say so much.
https://www.c-media.se/log.txt

**Comment by rusko124** [comment]
@TheCazz could you update one more time and show the logs at the end of the updating, please ?

**Comment by TheCazz** [comment]
Sure it going to take a little time but I going to do it
Just run the update and again run  journalctl

**Comment by TheCazz** [comment]
ok after I came back after have been out I did see it was finnish and did run the command but it gave me same info as before.
So I did reboot the raspberry and again run the command and it gave me this info
https://www.c-media.se/log2.txt

**Comment by rusko124** [comment]
@TheCazz Judging by the logs, no one of the services Screenly does not start. Have you had any problems with the update?Any errors?

**Comment by TheCazz** [comment]
No error what I can see but I think I have to reinstall it again when I'm at his place again.

**Comment by rusko124** [comment]
Hey @TheCazz !
How is it going?
