### ISSUE TITLE
Fix demo setup

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1211]
As of recent, we've starting to have a lot of OOM errors on the demo site, leading to it being down a lot. We need to resolve this.

I don't know what is causing the OOM issue but it is a recent development as of the last few weeks.

**Comment by ealmonte32** [comment]
@vpetersson what is "the demo site"? sorry for the noob question.. just wondering.

**Comment by rusko124** [comment]
Hey @ealmonte32 !
[Demo site](http://ose.demo.screenlyapp.com/)

**Comment by vpetersson** [comment]
@ealmonte32 That's not a silly question at all. We should be more clear with these things ;)

**Comment by vpetersson** [comment]
Closed in favor of #1251
