### ISSUE TITLE
Issues jumping out to a terminal session

### ISSUE THREAD

**Issue by notaturkey** [Screenly/screenly-ose#1213]
#### Overview of the Issue
ctr + alt + f1 does not work on my raspberry pi with screenly ose. Ive tried on multiple pis and on the latest release of ose. Just trying to get to the terminal so i can update without reflashing the pis we have setup with the older version of ose. Can't ssh into them since ssh isnt enabled yet. Ive tried multiple keyboards as well.
#### Reproduction Steps

Steps to reproduce this issue:
load ose flashed on sd card
boot raspberry pi
ctr+alt+f1 as its still in the add screen menu or while its displaying assets

### Environment

* Raspberry Pi Hardware Version: Raspberry Pi 3 model b+
* Screenly OSE Version: screenly-v2-pi3-2019-08-06

**Comment by vpetersson** [comment]
@notaturkey Any chance you have a video playing while you're trying to do this? If so, try disabling it as the video will take over the screen entirely.

**Comment by notaturkey** [comment]
no, no video. I've tried to access the terminal directly after flashing the os onto the pi and after it boots up and shows the code to pair the screen it wont let me access the terminal, doesnt let me access the terminal while its booting either.

**Comment by vpetersson** [comment]
@notaturkey I just noticed that you're using the commercial version of Screenly. There is no shell access there (as it's fully locked down). This Github repository is for Screenly OSE, which is a completely separate version of Screenly. For Screenly OSE you can find the disk images [here](https://github.com/Screenly/screenly-ose/releases). For further support for the commercial version of Screenly, please get in touch with [support.screenly.io](https://support.screenly.io). 

To learn more about the differences between the versions, please see [this page](https://www.screenly.io/screenly-ose-vs-pro/)
