### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4)...

### ISSUE THREAD

**Issue by malti84** [Screenly/screenly-ose#1220]
Hello,

i have update my Screenly today to the new version and now i have the problem, that my viewer will not start. The syslog say:

[root@SCREENLY-DO1] /usr/local/lib/python2.7/dist-packages/requests # tail -f /var/log/syslog
Sep 17 07:53:14 SCREENLY-DO1 systemd[1]: screenly-viewer.service: Unit entered failed state.
Sep 17 07:53:14 SCREENLY-DO1 systemd[1]: screenly-viewer.service: Failed with result 'exit-code'.
Sep 17 07:53:14 SCREENLY-DO1 systemd[1]: screenly-viewer.service: Service hold-off time over, scheduling restart.
Sep 17 07:53:14 SCREENLY-DO1 systemd[1]: Stopped Screenly Viewer.
Sep 17 07:53:14 SCREENLY-DO1 systemd[1]: Starting Screenly Viewer...
Sep 17 07:53:14 SCREENLY-DO1 systemd[1]: Started Screenly Viewer.
Sep 17 07:53:19 SCREENLY-DO1 python[12134]: Generating asset-list...
Sep 17 07:53:19 SCREENLY-DO1 python[12134]: browser found dead, restarting
Sep 17 07:53:19 SCREENLY-DO1 python[12134]: Loading browser...
Sep 17 07:53:19 SCREENLY-DO1 python[12134]: Browser loading file:///tmp/screenly_html/black_page.html. Running as PID 12153.
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: Viewer crashed.
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: Traceback (most recent call last):
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 580, in <module>
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     main()
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 558, in main
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     browser_url(url=url)
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 328, in browser_url
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     browser_send('uri ' + escaped_url, cb=cb)
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 307, in browser_send
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     load_browser()
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 277, in load_browser
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     browser_send(uzbl_rc)
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 298, in browser_send
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     browser_event = browser_get_event()
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 283, in browser_get_event
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     event = browser.next()
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 355, in next
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     self.wait()
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 295, in wait
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     self._handle_exit_code(self.process.wait())
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 309, in _handle_exit_code
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:     self.process.stderr
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: ErrorReturnCode_127:
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   RAN: '/usr/bin/uzbl-browser --config=- --uri=file:///tmp/screenly_html/black_page.html --print-events'
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   STDOUT:
Sep 17 07:53:24 SCREENLY-DO1 python[12134]:   STDERR:
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: uzbl-core: error while loading shared libraries: 6:00 SCREENLY03-DO systemd[1]: screenly-viewer.service: Unit entered failed state.
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: screenly-viewer.service: Failed with result 'exit-code'.
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: screenly-viewer.service: Service hold-off time over, scheduling restart.
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: Stopped Screenly Viewer.
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: Starting Screenly Viewer...
Sep 17 07:53:24 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: Started Screenly Viewer.
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: Aug  4 11:06:04 SCREENLY03-DO python[7622]: /usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported ver... (361520 more, please see e.stderr)
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: Traceback (most recent call last):
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 580, in <module>
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     main()
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 558, in main
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     browser_url(url=url)
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 328, in browser_url
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     browser_send('uri ' + escaped_url, cb=cb)
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 307, in browser_send
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     load_browser()
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 277, in load_browser
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     browser_send(uzbl_rc)
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 298, in browser_send
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     browser_event = browser_get_event()
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/home/pi/screenly/viewer.py", line 283, in browser_get_event
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     event = browser.next()
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 355, in next
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     self.wait()
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 295, in wait
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     self._handle_exit_code(self.process.wait())
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 309, in _handle_exit_code
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:     self.process.stderr
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: sh.ErrorReturnCode_127:
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   RAN: '/usr/bin/uzbl-browser --config=- --uri=file:///tmp/screenly_html/black_page.html --print-events'
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   STDOUT:
Sep 17 07:53:25 SCREENLY-DO1 python[12134]:   STDERR:
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: uzbl-core: error while loading shared libraries: 6:00 SCREENLY03-DO systemd[1]: screenly-viewer.service: Unit entered failed state.
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: screenly-viewer.service: Failed with result 'exit-code'.
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: screenly-viewer.service: Service hold-off time over, scheduling restart.
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: Stopped Screenly Viewer.
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: Starting Screenly Viewer...
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: Aug  4 11:06:00 SCREENLY03-DO systemd[1]: Started Screenly Viewer.
Sep 17 07:53:25 SCREENLY-DO1 python[12134]: Aug  4 11:06:04 SCREENLY03-DO python[7622]: /usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported ver... (361520 more, please see e.stderr)
Sep 17 07:53:25 SCREENLY-DO1 systemd[1]: screenly-viewer.service: Main process exited, code=exited, status=1/FAILURE
Sep 17 07:53:26 SCREENLY-DO1 systemd[1]: screenly-viewer.service: Unit entered failed state.
Sep 17 07:53:26 SCREENLY-DO1 systemd[1]: screenly-viewer.service: Failed with result 'exit-code'.
Sep 17 07:53:26 SCREENLY-DO1 systemd[1]: screenly-viewer.service: Service hold-off time over, scheduling restart.
Sep 17 07:53:26 SCREENLY-DO1 systemd[1]: Stopped Screenly Viewer.
Sep 17 07:53:26 SCREENLY-DO1 systemd[1]: Starting Screenly Viewer...

When i try to downgrade to 1.25.1 i become an error, INCOMPATIBLE.

[root@SCREENLY-DO1] /usr/local/lib/python2.7/dist-packages/requests # pip2 install --upgrade --user urllib3==1.25.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting urllib3==1.25.1
  Using cached https://files.pythonhosted.org/packages/c0/1f/516c14fd47ced1a2e2882edd776241c5b707ffc9051cd372843579829994/urllib3-1.25.1-py2.py3-none-any.whl
ERROR: requests 2.22.0 has requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.25.1 which is incompatible.
Installing collected packages: urllib3
  Found existing installation: urllib3 1.25.3
    Uninstalling urllib3-1.25.3:
      Successfully uninstalled urllib3-1.25.3
Successfully installed urllib3-1.25.1

What can i do? I also downgrade requests, same error...

chardet is on Version 3.0.4

Thanks for the help.

Best regards
Andreas

**Comment by vpetersson** [comment]
@malti84 please note that the latest release (assuming you're talking about Sprint 10) is a pre-release. It's not fully tested yet and we already found some issues with it. Until it has been flagged as stable, we recommend that you revert to the older disk image.
