### ISSUE TITLE
Rotate screenly

### ISSUE THREAD

**Issue by TheCazz** [Screenly/screenly-ose#1221]
Have install the latest version of Screenly OSE (Very nice work) and was going to have it on a monitor that is portrait and not landscape.

I have edit the config.txt file and have it so raspberry bootup right for me and even screenly show it right but when I upload image it still want to show image in landscape mode. 
Is it possible to edit setting so I do not need to rotate the image and maybe even the video 90 
degrees

Show two picture. One that show how it looks right with the startup of screenly and the other when it show a picture.

![nr1](https://user-images.githubusercontent.com/3855207/65136012-2f051800-da07-11e9-83f6-002d4891ee5b.jpg)
![nr2](https://user-images.githubusercontent.com/3855207/65136013-2f051800-da07-11e9-8559-a30a9972bd59.jpg)

**Comment by rusko124** [comment]
@vpetersson Could you add this to the current sprint?
