### ISSUE TITLE
"Play for" options on Start/End Date not on Experimental

### ISSUE THREAD

**Issue by ealmonte32** [Screenly/screenly-ose#1228]
#### Overview of the Issue

The "Play for Week/Month/Forever" options are not available on the Experimental branch.

#### Reproduction Steps

Steps to reproduce this issue:

* Press Add Asset
* Enter the Asset URL or File upload ... Save.
* Click Edit to check on the "Play for Start/End Date" options

### Environment

* Screenly OSE Version: Experimental

**Comment by ealmonte32** [comment]
* this is current experimental edit of asset options:

![screenly_exp_play_forever_issue2](https://user-images.githubusercontent.com/24350198/65717504-804c8180-e06f-11e9-969f-9c2d3a7aafaa.png)

---

* this is production and development edit of asset options:

![screenly_exp_play_forever_issue3](https://user-images.githubusercontent.com/24350198/65718954-ac1d3680-e072-11e9-8229-4a48c3a71f60.png)

**Comment by rusko124** [comment]
Hey @ealmonte32 !
In the current sprint our main point is to close the experimental branch. To do this, we need to make all features of the experimental branch as default.
https://github.com/Screenly/screenly-ose/issues/1093

**Comment by ealmonte32** [comment]
gotcha.. sorry it's just I have all 3 branches in different SD cards in order to test everything on whichever one the issue needs to be tested on, and during one of my tests I saw that experimental branch didn't have this option, and i thought it would be a quick edit of the code, but all good then, i'll close this.
