### ISSUE TITLE
Screenly-ose self install instructions link to Raspbian Buster

### ISSUE THREAD

**Issue by bmcwr** [Screenly/screenly-ose#1231]
Buster support #1187 appears to have been moved into Sprint 11 from Sprint 10.
Also #1198 says Uzbl does not work with Buster.

The OSE web installation instructions are at https://www.screenly.io/ose/ 

Option 2 NOOBS - does this use Buster?
Option 3 links to Raspbian Buster releases. 

If Buster is not supported, or only on some versions of Pi, then this should be clearly set out on in the web instructions so potential users know they have to find and use Stretch.

**Comment by vpetersson** [comment]
> Buster support #1187 appears to have been moved into Sprint 11 from Sprint 10.
Also #1198 says Uzbl does not work with Buster.

The lack of Uzbl in Buster is the reason why it has been delayed. So yes, Buster is currently not supported (neither in NOOBS or in the regular release). The disk images are currently using Stretch.
