### ISSUE TITLE
Management page login, restrictions, users

### ISSUE THREAD

**Issue by KronnNZ** [Screenly/screenly-ose#1233]
Hi all,

1. Does anyone have any steps to enable HTTPS on the management login?
2. Is it possible to restrict users from accessing the 'Settings ' Page 
3. Is it possible to allow for multiple user logins?

### Environment
* Raspberry Pi Hardware Version: Pi 3B+
* Screenly OSE Version: Experimental Version

**Comment by vpetersson** [comment]
> Does anyone have any steps to enable HTTPS on the management login?

Yes, that's built-in. There's a [script available](https://github.com/Screenly/screenly-ose/blob/master/docs/http-basic-authentication.md) to do this.

> Is it possible to restrict users from accessing the 'Settings ' Page

No, you can either enable auth for everything, or nothing. See [this document](https://github.com/Screenly/screenly-ose/blob/master/docs/http-basic-authentication.md) for details.

> Is it possible to allow for multiple user logins?

No, this is not possible. However, this is supported in the commercial version of Screenly.
