### ISSUE TITLE
Is there support for WPA2-Enterprise?

### ISSUE THREAD

**Issue by ilovecats516** [Screenly/screenly-ose#1237]
#### Overview of the Issue

I'm looking for a solution to our current slideshow setup. Our wi-fi is WPA2-Enterprise secured and I'm not sure if Screenly OSE supports this.

#### Reproduction Steps

N/A

### Environment

* Raspberry Pi Hardware Version: Raspberry Pi 3B+
* Screenly OSE Version: N/A

**Comment by vpetersson** [comment]
Linux does, so you should be able to do it. There's a guide [here](https://raspberrypi.stackexchange.com/questions/22875/connecting-to-wpa2-enterprise-wifi-network) on this. It's not something I've tested myself, but I don't see any reason why it wouldn't work.
