### ISSUE TITLE
Mounting OSE in Balena

### ISSUE THREAD

**Issue by vhgarciaa** [Screenly/screenly-ose#1238]
Hello, I  have a problem uploading Screenly OSE to my balenacloud because it gives me an error when doing Git Push and Balena push.

The error I leave them in photos, I tried to upload it from windows and from ubuntu and I always get the same error, I don't know if it is a screenly bug.

[https://drive.google.com/open?id=1-4TkrSUhS_rTRZ7S6X-f7SxW5HaX4oDn](url)

I hope you can help me, thank you very much

**Comment by vpetersson** [comment]
Attaching screenshots directly here:

![IMG_4009](https://user-images.githubusercontent.com/357664/66481990-ec7cab80-ea99-11e9-916e-e1b5297aafd3.jpg)
![IMG_4010](https://user-images.githubusercontent.com/357664/66481991-ec7cab80-ea99-11e9-9896-2697484483ca.jpg)
![IMG_4011](https://user-images.githubusercontent.com/357664/66481992-ec7cab80-ea99-11e9-9680-70ed947abfa7.jpg)

Looks like it is a build issue. Unclear what's causing it. @RemingtonA can you try reproducing this?

**Comment by vhgarciaa** [comment]
Any progress with this? Thank you

**Comment by jcbeebe21** [comment]
Same exact issue when trying a git push or balena push with the production branch.  Any workaround for this?

**Comment by vpetersson** [comment]
Yes, there's a [pull request](https://github.com/Screenly/screenly-ose/pull/1239) that should address this. Feel free to give it a spin.

**Comment by tho-wa** [comment]
Is there any fix right now?

**Comment by vpetersson** [comment]
> Is there any fix right now?

Should have been fixed in master.

**Comment by tho-wa** [comment]
Still running in same issue.

**Comment by vpetersson** [comment]
@rusko124 can you see if you can reproduce this?

**Comment by rusko124** [comment]
I'll investigate the issue in the next few days

**Comment by rusko124** [comment]
The issue is reproducible for RPi4.
I suggest to close the current thread and continue the discussion here #1282.

On RPi3 everything works fine.
![image](https://user-images.githubusercontent.com/17593028/72145233-4906a400-33c4-11ea-8d24-7d1d2ebe3cd5.png)
![image](https://user-images.githubusercontent.com/17593028/72145286-63d91880-33c4-11ea-97b4-d4bcd1d51cec.png)
