### ISSUE TITLE
Add ISO date format to Screenly settings

### ISSUE THREAD

**Issue by ajagelund** [Screenly/screenly-ose#1241]
#### ISO format missing

In the date format dropdown for Screenly settings the ISO standard format is missing.
ISO format: *yyyy-mm-dd*

### Side note

I have a Pull Request ready to push on my computer... :-)

### Environment

_Don't think this is environment related, however:_

* Raspberry Model: Model 3B Revision: 1.2 Ram: 1 GB Sony UK
* Screenly Version: production@6c2c2fd

**Comment by vpetersson** [comment]
@rusko124 can you take a look at this?

**Comment by ajagelund** [comment]
In settings.html:

`<option value="yyyy-mm-dd"
                                        {% if context.date_format == 'yyyy-mm-dd' %} selected="selected" {% endif %}>
                                    year-month-day
                                </option>
`

**Comment by vpetersson** [comment]
Could you do a pull request for this?

**Comment by rusko124** [comment]
Can be closed
