### ISSUE TITLE
Live Demo does not work

### ISSUE THREAD

**Issue by didiatworkz** [Screenly/screenly-ose#1245]
Hey guys

http://ose.demo.screenlyapp.com/ do not work at the last days
![image](https://user-images.githubusercontent.com/18490798/67968162-31ae7c00-fc07-11e9-85e3-0a519bc39491.png)

Can you please fix this? - I will check a bug with the API 😄

**Comment by racquetmaster** [comment]
Also contributes to #1246

**Comment by vpetersson** [comment]
Will be fixed in #1251
