### ISSUE TITLE
API Documentation is unavailable

### ISSUE THREAD

**Issue by racquetmaster** [Screenly/screenly-ose#1246]
#### Overview of the Issue
API Documentation is missing / unavailable.

#### Reproduction Steps
Go to: [Demo Site Docs](http://ose.demo.screenlyapp.com/api/docs/)
OR
Go to local raspberry pi docs: ```<yourip>/api/docs/```

**Comment by vpetersson** [comment]
@racquetmaster this is a known issue. @rusko124 do we have any update on this?

**Comment by vpetersson** [comment]
Will be fixed in #1251.
