### ISSUE TITLE
Opening splash screen and api/docs screen displays screenly-ose_server container IP as of #1252

### ISSUE THREAD

**Issue by ChuckIT** [Screenly/screenly-ose#1253]
#### Overview of the Issue
As of version #1252 for both production and development the opening splash screen and api/docs screen displays screenly-ose_server container IP instead of the local network ip address for the RPi3. Related to changes made for issue #1244
EDIT:
On Reboot/Power cycle Screenly does not produce the splash screen only displays:
502 Bad Gateway
        nginx
Then goes to displaying the contents in the schedule as normal.

#### Reproduction Steps
rm -r screenly-ose
git clone https://github.com/Screenly/screenly-ose.git
git remote add balena ???@git.balena-cloud.com:stryder/screenly.git
balena push screenly
wait for balenaCloud to update
from device screen click on the REBOOT or RESTART button

### Environment

* Device: RPi3
* Host OS: balenaOS 2.43.0+rev1 production
* Screenly OSE Version: #1252

**Comment by vpetersson** [comment]
@ChuckIT Could you please provide the logs from the Balena dashboard?
