### ISSUE TITLE
Cross Site Scripting (Stored) vulnerability

### ISSUE THREAD

**Issue by aegisduck** [Screenly/screenly-ose#1254]
# Describe the bug
### Suggested description of the vulnerability
: A stored cross-site scripting (XSS) vulnerability in the 'Add Asset' page of Screenly-OSE allows a remote attacker to introduce arbitary Javascript via manipulation of a 'URL' filed.

### Attack vector(s)
![1](https://user-images.githubusercontent.com/40930382/68667977-8c8e8e80-058a-11ea-9278-d901414b9b1b.png)
　1. Press the 'Add Asset' button in the upper right corner.

![2](https://user-images.githubusercontent.com/40930382/68668387-60274200-058b-11ea-9190-22330b7ffb2e.png)
　2. Enter `https://www.google.com/?<img src=xss onerror=alert(document.domain)>` in the 'Asset URL' field.

![3](https://user-images.githubusercontent.com/40930382/68668393-63223280-058b-11ea-8403-d9943b7f2651.png)
　3. When accessing the main page ('Schedule Overview' menu), arbitrary code is executed.
(The same vulnerability occurs when uploading to a file other than a URL.)

### Affected URL/API(s)
`/api/v1.2/assets`

### Environment
* Raspberry Pi Hardware Version: Model 3B+ Revision: 1.3 Ram: 1 GB Sony UK
* Screenly OSE Version: 2019-09-25-Screenly-OSE-lite.img

**Comment by vpetersson** [comment]
Good find! Adding this to the next sprint.
