### ISSUE TITLE
No boot after power off

### ISSUE THREAD

**Issue by gady87** [Screenly/screenly-ose#1257]
Hi when the device gets disconnected from the power supply and plug it back in sometimes its doesnt boot at all its stays on the raspberry splash screen the rainbow one .
sometimes when you power on and off again works but for after a while and sometimes it doesn't and i need to reflash the image again.  what might be the issue ? 

--

#### Reproduction Steps

Steps to reproduce this issue, eg:

* unplug the device from the power supply

### Environment

* Raspberry Pi Hardware Version: 3
* Screenly OSE Version: lastest

**Comment by vpetersson** [comment]
That's an indication of an SD card that is about to give up. I'd suggest swapping it out.
