### ISSUE TITLE
Experimental, Development and Stable

### ISSUE THREAD

**Issue by Kipjr** [Screenly/screenly-ose#1260]
I had some issues with installing the correct version. I noticed that there is a Master, an Experimental, a Celery and a production branch.. 
Which of these are still being maintained and what is the difference between those?

**Comment by vpetersson** [comment]
@Kipjr here's a summary:

 * **production**: This is what we use for releases (and disk images). Consider this the stable branch where we have QA'd.
 * **master** (a.k.a. development): This is the branch everything goes into before being merged into production. This branch might be broken at times. Use it if you want to follow the latest development efforts.
 * **celery**: This is a feature branch that if I'm not mistaken is already merged into master (ping @rusko124)
 * **experimental**: This is another feature branch with the next generation browser. This branch also includes dockerization and we're working on bringing this into master.
