### ISSUE TITLE
Is the experimental branch using the experimental WebView from Qt active?

### ISSUE THREAD

**Issue by jmrbcu** [Screenly/screenly-ose#1268]
Any plans to release/merge the new Qt WebView in the experimental branch with the master? Isn't it better and more performant than uzbl in the master and production branch?

**Comment by vpetersson** [comment]
@jmrbcu Yes. That's part of the next sprint.

**Comment by jmrbcu** [comment]
do you guys have an ETA?

**Comment by vpetersson** [comment]
No ETA right now, but you can always switch to the experimental branch and do some more testing. We always need more hands there.
