### ISSUE TITLE
Automatically load video if no connection instead of going to AP mode

### ISSUE THREAD

**Issue by sipsontm** [Screenly/screenly-ose#1277]
I just tested the Screenly OSE build and i was so impressed, it really works great. Congrats to all that put an effort to it.
We are building an Xmass display stand that has a fireplace. We've built the fireplace and put an lcd display (TV) in it that need to play a short fire burning video. - this helped a lot: 

https://www.screenly.io/blog/2018/12/22/virtual-fireplace-raspberry-pi/

![WhatsApp Image 2019-12-09 at 13 19 23](https://user-images.githubusercontent.com/58630695/70568286-4257f780-1ba0-11ea-8831-93ad25713f5f.jpeg)
![WhatsApp Image 2019-12-10 at 10 00 49](https://user-images.githubusercontent.com/58630695/70568283-41bf6100-1ba0-11ea-8234-b8ba855c9ac6.jpeg)
![WhatsApp Image 2019-12-09 at 13 21 52](https://user-images.githubusercontent.com/58630695/70568285-4257f780-1ba0-11ea-9a00-87a81d26374c.jpeg)

On the way i came across the following issue, that i managed to fix:

- We needed to play the video on loop mode so that we don't get the black screen between preloading of video - i found a fix here and it works great: https://forums.screenly.io/t/looping-video-for-a-virtual-fireplace/145/11

**### We will install this in a location with no internet access.
When i boot PI with no internet connection it will go into AP mode and will not display the video.
Is there a fix for this to be able to boot and load the video automatically without internet connection?**

Sincerely,

Ciprian

**Comment by vpetersson** [comment]
> When i boot PI with no internet connection it will go into AP mode and will not display the video.
Is there a fix for this to be able to boot and load the video automatically without internet connection?

This is expected. It's because if the Pi has no internet connection, it doesn't know what time it is. If it doesn't know what time it is, it doesn't know what to play.  The technical reason for this is because the Raspberry Pi lacks a Real Time Clock (RTC). This is why Screenly requires internet (or at least LAN) access in order to properly function.

**Comment by vpetersson** [comment]
But also - great project! Would love to see some more photos.

**Comment by sipsontm** [comment]
vpetersson, thank you for your quick reply, it all makes sense now. Apparently, we now have to use 2 displays in the posm stand (one for the fireplace and one to display a video ad). I will be using 2 x RPI Zero W. I already got a portable wifi hotspot 4G from Huawei that we're going to use. Hope it all goes well. It will be displayed in Carrefour Hypermarket in Timisoara/Romania.


![WhatsApp Image 2019-12-11 at 13 26 01](https://user-images.githubusercontent.com/58630695/70617897-4163ac00-1c1a-11ea-83ac-07d61e0846ff.jpeg)
![WhatsApp Image 2019-12-06 at 11 36 33 (1)](https://user-images.githubusercontent.com/58630695/70617898-4163ac00-1c1a-11ea-96ca-0353d09fb5ef.jpeg)
![WhatsApp Image 2019-12-06 at 11 36 33](https://user-images.githubusercontent.com/58630695/70617900-41fc4280-1c1a-11ea-944b-2af343193da7.jpeg)

**Comment by djmtc** [comment]
Hi there @sipsontm! Daniel here with Screenly. I'm the guy who wrote the original article that you found helpful :) We'd love to do an case study on you deployment and get you more exposure with our audience. Can you reach out to dmountcastle@screenly.io and we can talk more about this? Happy holidays!!
