### ISSUE TITLE
Container services not removed/purged after switching branches

### ISSUE THREAD

**Issue by ealmonte32** [Screenly/screenly-ose#1289]
Went from Experimental to Master/Dev and noticed that container service was still running and packages were still installed.

![image](https://user-images.githubusercontent.com/24350198/72369704-a5bcd400-36ce-11ea-8912-9e7e8c1b3dc9.png)

I also noticed that the experimental `install.sh` file does not contain the same script as the master and production, just wondering, this is by design/expected right? Just saying because I wanted to make sure I would be able to get version from terminal with the ~/version.md file but the experimental doesnt have this line and makes me have to go on the webUI to get screenly version, so I will just add it in a PR, but that brought me to the attention that the install script is different.

![image](https://user-images.githubusercontent.com/24350198/72369765-c8e78380-36ce-11ea-92f7-c8710c1c02c1.png)

**Comment by rusko124** [comment]
Good found @ealmonte32 ! In current sprint we are working on migration experimental(with docker) browser to master. But If you have a time, It would be great if you create cleanup tasks for ansible.
