### ISSUE TITLE
Grafana failed to load data 

### ISSUE THREAD

**Issue by ruben-herold** [Screenly/screenly-ose#1293]
hi,

we have here some screenly OSE systems to show grafana dashboards. After the last grafana update we get an error on loading the dashboards:

prometheus-src plugin failed
Error: Loading chunk 44 failed. (missing:
https://grafanaserver.local/public/build/prometheusPlugin.<some hex vaules>.js)

with normal desktop browsers we don't see any problems.

**Comment by vpetersson** [comment]
Could you try switching to the experimental version to see if that works?

**Comment by ruben-herold** [comment]
@vpetersson is there an image downloadable?
My last test was with: https://github.com/Screenly/screenly-ose/releases/download/0.18.2/2019-09-25-Screenly-OSE.zip

**Comment by vpetersson** [comment]
No, you need to manually install it using the [installer](https://github.com/Screenly/screenly-ose#installing-on-raspbian). That said, you can still use that as the base image.

Alternatively, you could try the commercial version of Screenly, which is known to work with Grafana (see [this page](https://www.screenly.io/screenly-ose-vs-pro/) for details).

**Comment by ruben-herold** [comment]
what I have done no was:

Settings --> Upgrade Screenly --> Latest. 

after this reboot. But nothing changed.

**Comment by ruben-herold** [comment]
@vpetersson version shows now 

Screenly Version | master@55e9f9f
-- | --

**Comment by vpetersson** [comment]
No, you need to SSH into the Pi, run the upgrade script and answer yes to the question if you want to run the experimental version.

**Comment by ruben-herold** [comment]
@vpetersson tried this. After reboot the pi hangs now in rc-local.service. I can access the new webinterface but no browser on the screen only the Screenly Logo with rc-local.service on it.

**Comment by vpetersson** [comment]
Can you SSH in an get some logs?

**Comment by ruben-herold** [comment]
@vpetersson no cause card already new flashed with an  Raspbian Lite. Its updating in the moment, after this I will try again.

**Comment by ruben-herold** [comment]
@vpetersson first try with Raspbian Lite. failed:

  Booted it, 
  logged in , 
  update system, 
  start your script. 

Ended in a error message installing docker-ce 
![20200124_150535](https://user-images.githubusercontent.com/1569572/73075593-93a41800-3ebc-11ea-8831-224dc7376b5a.jpg)

Now I will try again via ssh.

**Comment by ruben-herold** [comment]
@vpetersson got it running now. But same error.

**Comment by ruben-herold** [comment]
@vpetersson on my desktop all grafana stuff runs fine with firefox, chromium, google chome, and even with midori (small webkit based browser)

**Comment by vpetersson** [comment]
What Raspberry Pi hardware are you running on?

**Comment by ruben-herold** [comment]
@vpetersson Raspberry Pi 3 Model B V1.2

**Comment by vpetersson** [comment]
Please take a look at #1282 to see if that helps.

**Comment by ruben-herold** [comment]
@vpetersson I'm not sure if we talk about different stuff.  I got experimental running, please see above. If I understand #1282 right it's about an install problem. 

But on experimental I get the same error like on current.  The browser in experimental also said:

prometheus-src plugin failed
Error: Loading chunk 44 failed. (missing:
https://grafanaserver.local/public/build/prometheusPlugin..js)

On my desktop all grafana stuff runs fine with firefox, chromium, google chome, and even with midori (small webkit based browser)

**Comment by equinoxefr** [comment]
Hi,

Same issue here, i'm running experimental version with grafana. Since last version (6.6.0) of grafana i have an error: "An unexpected error as happened"

Opening a grafana screen without any graph works.

Is there a log to check ?

**Comment by ruben-herold** [comment]
Yes the same her with 6.6.0 with 6.5 I get the error above.

**Comment by ruben-herold** [comment]
any news here?

**Comment by varac** [comment]
I just installed latest screenly-ose release then the *only* use case for me is to show grafana dashboards, which won't work for me neither.
Hearing the the paid version supports grafana makes me sad because this shows that the ose version doesn't get the support it should. Please fix this ! As @ruben-herold explained above, my grafana dashboards display fine with any browser I tried so far and only fail in screenly-ose.

**Comment by varac** [comment]
I'm using grafana v6.6.0 (5c11bbdfb4) for the record.

**Comment by vpetersson** [comment]
> Hearing the the paid version supports grafana makes me sad because this shows that the ose version doesn't get the support it should

We're happy to accept contributions. The reality is that the commercial version of Screenly is what enable us to spending money on paid developers to OSE in the first place. So yes, it will always take precedence.

**Comment by ruben-herold** [comment]
@vpetersson is it possible to get a build that starts the browser with enabled  js console or something, so that the error can logged to see whats going wrong.

**Comment by vpetersson** [comment]
@ruben-herold I'd have to pass that on to @rusko124 as he worked most recently on it. But yes, i think that should be possible.

**Comment by ealmonte32** [comment]
@ruben-herold , you can use VNC viewer and control the browser with mouse and get to inspect element (screenshots on bottom).. but, I just tested with a master version of screenly (development), and I get the site to load this:

![Screen Shot 2020-02-23 at 9 26 32 PM](https://user-images.githubusercontent.com/24350198/75125455-3352f280-5683-11ea-85ec-7b1aa6744c50.png)
![Screen Shot 2020-02-23 at 9 24 50 PM](https://user-images.githubusercontent.com/24350198/75125460-36e67980-5683-11ea-9cb5-bc4d7080a72f.png)

using VNC viewer:
![Screen Shot 2020-02-23 at 9 27 15 PM](https://user-images.githubusercontent.com/24350198/75125500-6301fa80-5683-11ea-8244-3da9666203e7.png)
![Screen Shot 2020-02-23 at 9 27 31 PM](https://user-images.githubusercontent.com/24350198/75125501-639a9100-5683-11ea-938e-7170e60042c3.png)

**Comment by ruben-herold** [comment]
I have done some testing and it happend only if I use prometheus as datasource. 
Non Prometheus based databsources worked.

**Comment by ealmonte32** [comment]
Ok, I see what you mean, these errors:

![image](https://user-images.githubusercontent.com/24350198/75189436-2afac600-571c-11ea-999a-e2096660c3be.png)

![image](https://user-images.githubusercontent.com/24350198/75190327-0f90ba80-571e-11ea-9231-369015b11cde.png)

Well.. this is as you know most likely the uzbl browser not supporting whatever plugin that is.

**Comment by ealmonte32** [comment]
_Self-note: I am noticing that when I leave this asset open for unlimited time (only asset), Xorg (X.service) CPU usage spikes to 100%+ for undefined time, stays like that, and makes Pi hang.
Will need to use cpu limits on this._

**Comment by ruben-herold** [comment]
@ealmonte32  also it does not work in experimental. As far as I know that experimental don't use uzbl

**Comment by ealmonte32** [comment]
> @ealmonte32 also it does not work in experimental. As far as I know that experimental don't use uzbl

Correct, it uses QT webview, and I think it just needs to be compiled with support for all these plugins.. maybe rusko can chime in about that..

**Comment by ruben-herold** [comment]
Still not work. Any progress?

**Comment by vpetersson** [comment]
No progress has been made on this, but I can confirm that this is working in the commercial version. That's the only workaround i can offer right now.

**Comment by ruben-herold** [comment]
@vpetersson  anything I can do as non developer? Testing? Or something else to speedup

**Comment by vpetersson** [comment]
@ruben-herold Yes, it seems like we need to patch the [browser](https://github.com/Screenly/screenly-ose-webview) to support Grafana. We had a similar issue in the commercial version a while back. @sergey-borovkov, perhaps you can chime in here?

**Comment by sergey-borovkov** [comment]
> @ruben-herold Yes, it seems like we need to patch the [browser](https://github.com/Screenly/screenly-ose-webview) to support Grafana. We had a similar issue in the commercial version a while back. @sergey-borovkov, perhaps you can chime in here?

We moved to webengine in the commercial version. So that issue resolved itself there.

**Comment by vpetersson** [comment]
@ruben-herold I'm not sure what the amount of effort is to move from Webkit to Webengine in the browser to be honest. If you're interested in looking into this, that would be fantastic.
