### ISSUE TITLE
Create contributing guideline

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1303]
We need to add a [contributor guideline](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) to the project.

**Comment by ealmonte32** [comment]
Just my opinion, I think the Atom one given on the example is really too much reading and too long, I like this simple and to the point example one:
https://github.com/rails/rails/blob/master/CONTRIBUTING.md
