### ISSUE TITLE
External monitoring

### ISSUE THREAD

**Issue by pelicanmedia** [Screenly/screenly-ose#1307]
Not an issue, more of a query...
I'd like to install Nagios on my Balena install to monitor uptime along with all my other external servers etc.
Out of the services installed (redis, screenly-celery, screenly-server, screenly-viewer & screenly-websocket) what would be the best one to install on that would be persistent on reboot?

Thanks

### Environment

* Raspberry Pi Hardware Version: Pi3 B
* Screenly OSE Version: Latest

**Comment by vpetersson** [comment]
Not sure  if you mean a Nagios server or just monitor it using Nagios. I would strongly discourage installing a Nagios server, as we're already operating on limited resources. If you're just looking to monitor the installation using Nagios, the easiest way is to monitor the webservice i presume.

**Comment by pelicanmedia** [comment]
Hi, sorry I meant just monitor it using Nagios. By installing the nagios-nrpe-server and nagios-plugins. Mainly to monitor uptime so I can see if/when there have been unplanned power disruptions.

**Comment by vpetersson** [comment]
Ah, ok. I'm not sure if it's pull or push (been ages since I touched Nagios). Regardless, I would recommend adding a new container that only has Nagios. Since Docker containers should be considered ephemeral, you can't just install it within an existing one.

**Comment by pelicanmedia** [comment]
Ok great, thanks for the quick response. Just wanted to check before I broke something!
I'll have a go at creating a new container.
