### ISSUE TITLE
Problem with USB Stick use

### ISSUE THREAD

**Issue by srops** [Screenly/screenly-ose#1310]
Hello guys,

I need your help, please.

I connected my hard drive to the Rasperry Pi.
I installed the Screenly software on the Raperry.

Now I would like to play the images wich are on the hard drive.
But still have the ability to quickly change whether it should play folder 1 or folder 2.

Is this possible?

Best regards
Manuel

**Comment by ealmonte32** [comment]
Did you click on Settings > USB assets > generate file ?
You have to set it up that way.

![Screen Shot 2020-02-26 at 12 49 56 AM](https://user-images.githubusercontent.com/24350198/75319687-2416a500-583b-11ea-9ec5-96599f3170c5.png)

**Comment by vpetersson** [comment]
@srops Doesn't sound like a good fit. It would be a lot easier if you simply uploaded the assets and scheduled them accordingly. That said, as @ealmonte32 correctly pointed out, you can play assets from the USB interface (assuming they are mounted correctly).

**Comment by srops** [comment]
Hmmm Okey I will check this @ealmonte32 

I can’t upload 5000 pictures? @vpetersson

**Comment by ealmonte32** [comment]
> Hmmm Okey I will check this @ealmonte32
> 
> I can’t upload 5000 pictures? @vpetersson

Well, as far as i know, if the total size (MB or GB) of all the pictures is available in the disk drive (SD card), then the sqlite database should be able to handle those entries (rows) without a problem.. remember, uploading the assets from your USB will then be saved into the raspberry pi, so make sure there is enough space.

**Comment by vpetersson** [comment]
Yep, there's no technical limitation in adding 5k pictures. It might not be the best user experience using the web interface, but you should in theory be able to do it (assuming the constraints that @ealmonte32 correctly points out).
