### ISSUE TITLE
Unable to play MPEG stream Sprint 10

### ISSUE THREAD

**Issue by hostheimer** [Screenly/screenly-ose#1319]
Since I've installed Sprint 10 the some video steams will not run.

#### Overview of the Issue

Since I've installed Sprint10 the .mjpg and .cgi  video streams stop running.

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Press Add Asset
* Enter the Asset URL  http://213.4.39.225:81/mjpg/video.mjpg
* Press "On"
* Wait for the asset to show up on the screen

also url: http://88.26.233.51:8080/mjpg/video.mjpg
Also a site with a video URL: http://87.140.122.56/axis-cgi/mjpg/video.cgi does not work anymore after I installed Sprint10

### Environment

* Raspberry Pi Hardware Version: 3B+
* Raspberry Pi Network Setup:  built-in WiFi and Ethernet
* Screenly OSE Version: Sprint10

**Comment by ealmonte32** [comment]
@hostheimer 
Works fine for me, which version of screenly-ose are you using?
Screenshots of my test below.

![Screen Shot 2020-03-13 at 5 00 42 PM](https://user-images.githubusercontent.com/24350198/76659252-4bb08180-654c-11ea-9211-cdb6ad39f77a.png)
![Screen Shot 2020-03-13 at 5 00 26 PM](https://user-images.githubusercontent.com/24350198/76659253-4bb08180-654c-11ea-8f88-10d6b59928b9.png)
![Screen Shot 2020-03-13 at 5 00 16 PM](https://user-images.githubusercontent.com/24350198/76659254-4c491800-654c-11ea-9272-93e4f8b9d9f0.png)

**Comment by ealmonte32** [comment]
So I just realized, having a stream might be a problem/conflict if LimitCPU # of seconds is shorter than how long the stream asset is left "On" for because the uzbl-core process stays in "R" (Running) state for as long as the stream is on...  
Conflict with this PR: https://github.com/Screenly/screenly-ose/pull/1304
