### ISSUE TITLE
Unable to mount disk image file of Screenly OSE 

### ISSUE THREAD

**Issue by rreno-soltech** [Screenly/screenly-ose#1326]
#### Overview of the Issue

Sprint 10 Disk Image File appears to be corrupted. The file cannot be mounted on Windows 10.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Download the Sprint 10 2019-09-25-Screenly-OSE.zip file.
2. Extract the contents of the file.
3. Right-click the 2019-09-25-Screenly-OSE-lite Disk Image File, and selected "Mount" from the context menu. A message is displayed saying that the Disk Image File is corrupt. The file size is 2.17 GB.

### Environment

Windows 10
Screenly OSE Version 2019-09-25

**Comment by vpetersson** [comment]
This is expected. Windows cannot mount Linux file systems (e.g. ext3/4).
