### ISSUE TITLE
Possibilities to sponsor this project

### ISSUE THREAD

**Issue by loleg** [Screenly/screenly-ose#1329]
In a [recent comment](https://github.com/Screenly/screenly-ose/issues/1187#issuecomment-627827966) on #1187 the financial situation of the project was mentioned as a reason we're not seeing fresh releases of Screenly OSE. Of course, [buying a subscription](https://www.screenly.io/pricing/) is an obvious way to support the project (and something I am considering). Additionally, I would like to suggest that the OSE project looks for alternative financing mechanisms to boost the good work being done here. 

GitHub recently launched a [Sponsors](https://github.com/sponsors) initiative with a button you can easily add to this repo, and I recommend [OpenCollective](https://opencollective.com/) and [Patreon](https://www.patreon.com/) among many other ways out there to connect to transparent funding and a supportive community for an open source project.

**Comment by vpetersson** [comment]
Hi @loleg - those are good points. I haven't looked closely at the GitHub Sponsors initiative yet, but it does seem interesting.

**Comment by vpetersson** [comment]
@loleg This is now live **and** we have our first Gold sponsor.

More can be found here: https://github.com/sponsors/Screenly

**Comment by loleg** [comment]
Congratulations! Here's to many more ...
