### ISSUE TITLE
502 Bad Gateway - nginx

### ISSUE THREAD

**Issue by swebervna** [Screenly/screenly-ose#1333]
#### Overview of the Issue

When I start my Raspberry Pi with Screenly OSE installed and try to access the Screenly web interface, I get "502 Bad Gateway nginx". I've tried updating Raspbian, power cycling the Raspberry Pi, etc, with no luck.

![image](https://user-images.githubusercontent.com/66483494/83897335-7a8d5c80-a723-11ea-93e5-5135ef26dcbd.png)

#### Reproduction Steps

Very simple for my case: start the Raspberry Pi. Nothing specific from my input causes it, it's just stuck anytime the Pi runs.

### Environment

* Raspberry Pi Hardware Version: Model 3B Revision: 1.2 Ram: 1 GB Sony UK
* Raspberry Pi Network Setup: Ethernet
* Screenly OSE Version: master@fcf603e

**Comment by vpetersson** [comment]
Can you please provide more details on how you installed Screenly (disk image or Raspbian). Also, could you provide logs from `journalctl`? Thanks.
