### ISSUE TITLE
Status of the Project

### ISSUE THREAD

**Issue by shaqaruden** [Screenly/screenly-ose#1334]
First and foremost what is the current status of this project. With nothing committed since mid-march and with the current world situation that this project has been put on hold for a while if not indefinitely.

**Comment by shaqaruden** [comment]
Fixed my network issue

**Comment by vpetersson** [comment]
Hi @shaqaruden,

We are in the process of hiring a new developer to revamp OSE. We have a lot of work in progress that is not reflected in the current build. We're going to track that work [here](https://github.com/Screenly/screenly-ose/projects/7).
