### ISSUE TITLE
TASK [system : Install build-essential] **************************************** fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: "}

### ISSUE THREAD

**Issue by arjunior07** [Screenly/screenly-ose#1340]
when i build my disk image i get this error i don't know how to fix that

**Comment by ealmonte32** [comment]
@arjunior07 - pls give more details... this is too vague..
clear all temp & cache folders..  and maybe run`sudo apt clean && sudo apt autoclean`
