### ISSUE TITLE
(Recurring) 502 Bad Gateway - nginx

### ISSUE THREAD

**Issue by swebervna** [Screenly/screenly-ose#1358]
**Overview of the Issue:**
My Screenly OSE instances keep encountering this issue around a week after installing Screenly OSE. For the longest time everything worked, but lately, this issue keeps popping up, even after countless reinstallations of Screenly OSE (I install via the disk image, onto my 2 Raspberry Pi's). Screenly OSE is working just fine, it's just the web interface that I can't access.

Here's what I get when I try accessing the web interface:
![83897335-7a8d5c80-a723-11ea-93e5-5135ef26dcbd](https://user-images.githubusercontent.com/66483494/89044118-84909d80-d317-11ea-952d-a8b4daaa6488.png)

**Reproduction Steps:**
Very simple for my case: start the Raspberry Pi. Nothing specific from my input causes it, it's just stuck anytime the Pi runs.

**What I've tried:**

- Formatting Pi SD cards and flashing the disk image again (multiple times) to install
- Updating Screenly OSE (every time I update, I get this error & block of code in the middle of the update process):
> + sudo -u pi ansible localhost -m git -a 'repo=https://github.com/screenly/screenly-ose.git dest=/home/pi/screenly version=production'
> _An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 13] Permission denied: '.'
> localhost | FAILED! => {
>     "msg": "Unexpected failure during module execution.", 
>     "stdout": ""
> }_

**Environment:**
Raspberry Pi Hardware Version: Model 3B Revision: 1.2 Ram: 1 GB Sony UK
Raspberry Pi Network Setup: Ethernet
Screenly OSE Version: master@fcf603e

**Comment by vpetersson** [comment]
The most common reason for why this would happen would be because of a broken SD card. I'd recommend that you replace it and see if that solves the issue. If that doesn't solve the issue, please commend and I'll reopen the issue.

**Comment by swebervna** [comment]
@vpetersson I tried a new SD card for one of them and I'm still experiencing the issue.
