### ISSUE TITLE
Screenly OSE + LED Screen 336x504 px without external scalar

### ISSUE THREAD

**Issue by francovico** [Screenly/screenly-ose#1359]
Hello everybody,
I want to use Screenly OSE with a 504x336 resolution LED screen that is connected directly to a sender without a scalar proccesor.
I need to fit the image in there and start from the coordinate x = o, y = o.
Is there any way to do it?
I cannot change the screen size or the position of the screen.
Any tips for this?

**Comment by scharph** [comment]
For RaspberryPi maybe the section **"Custom mode"** in [is](https://www.raspberrypi.org/documentation/configuration/config-txt/video.md) interesting for you

**Comment by vpetersson** [comment]
I don't *think* that is possible, @francovico but I could be wrong. To my knowledge, we haven't had anyone doing this.

**Comment by ealmonte32** [comment]
@francovico i tested this and worked fine on VNC display.. see screenshot

![Screen Shot 2020-09-17 at 4 10 25 PM](https://user-images.githubusercontent.com/24350198/93522981-50d9f900-f900-11ea-952c-8b93de65313d.png)
![Screen Shot 2020-09-17 at 4 09 54 PM](https://user-images.githubusercontent.com/24350198/93522984-51728f80-f900-11ea-995f-7c098a90399e.png)
![Screen Shot 2020-09-17 at 4 08 58 PM](https://user-images.githubusercontent.com/24350198/93522985-51728f80-f900-11ea-9c91-ecd6d53703a8.png)
