### ISSUE TITLE
Stuck on boot

### ISSUE THREAD

**Issue by FedericoFedeFede** [Screenly/screenly-ose#1364]
The rpi doesn't boot after the installation through downloading the [custom image](https://support.screenly.io/hc/en-us/articles/360042164173-Getting-started-with-Screenly-OSE)

![raspberry-pi-not-booting](https://user-images.githubusercontent.com/38628552/93708613-fe831d00-fb37-11ea-8b6b-e5e2c6ef291e.jpg)

### Environment

* Raspberry Pi Hardware Version: RPI 2 Model B V1.1
* Raspberry Pi Network Setup: Ethernet
* Screenly OSE Version: [Sprint 10.1 Release](https://github.com/Screenly/screenly-ose/releases/tag/v0.18.3)

**Comment by ealmonte32** [comment]
@FedericoFedeFede 

How about some logs? run command `journalctl` 
or
To see if there is an issue with the sprint 10.1 release image, could you instead please do the following:

download the official raspbian stretch lite image:
http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/2019-04-08-raspbian-stretch-lite.zip

burn that to the SD card..
then, boot it up and in the terminal, run the bash install script:
`bash <(curl -sL https://www.screenly.io/install-ose.sh)`

select Y for the development/master branch, and Y for the full system upgrade, just in case..
let me know how it goes..

**Comment by vpetersson** [comment]
Closing out due to inactivity.
