### ISSUE TITLE
Better font for passwords

### ISSUE THREAD

**Issue by shaqaruden** [Screenly/screenly-ose#1375]
Password for wifi on the hotspot splash screen are difficult to read. I would recommend switching to a monospaced font like Fira Code, DejaVu Sans Mono, or Source Code Pro.

Though a issue was resolved for password readability before still not knowing is l is a upper case i or a lower case L is an issue and the characters are too close together

**Comment by ealmonte32** [comment]
@shaqaruden 
Just wondering if you could test this real quick, if you could get to the terminal or ssh into your pi, would you mind editing this file on the screenshot and adding that line highlighted in red.. then restart the pi and see if it changes the font of the resin wifi hotspot info.. I just want to see how much difference it makes, so attach a before and after if you can.

![Screen Shot 2020-10-06 at 9 45 20 PM](https://user-images.githubusercontent.com/24350198/95280770-c4966400-0823-11eb-947f-54bfe3f01b11.png)

**Comment by ealmonte32** [comment]
@shaqaruden 
The lowercase letter `i` was removed from the ppp_letters list of available characters, thus there should no longer be any need to change fonts since there is no other character that has similarities with another.
I think this issue can be closed.

**Comment by ealmonte32** [comment]
@shaqaruden just a reminder to close this, thx

**Comment by shaqaruden** [comment]
\
