### ISSUE TITLE
Change Logos/Splash etc.

### ISSUE THREAD

**Issue by bd8392** [Screenly/screenly-ose#1406]
Hi =) This is no real issue, but a request,: How can I brand screenly OSE differently? (Change Logos on Splash and in browser, hotspot etc.)

**Comment by vpetersson** [comment]
This is not something we support. You'd have to fork it and modify the logos yourself by hand.

**Comment by bd8392** [comment]
Is there dev-docs or something?

**Comment by vpetersson** [comment]
No, not really. It should be pretty easy tho. Just fork the project and replace the images.
