### ISSUE TITLE
API_URL tries to resolve to the SSL enabled version instead of HTTP because of is_demo_node

### ISSUE THREAD

**Issue by ealmonte32** [Screenly/screenly-ose#1410]
#### Overview of the Issue

API_URL tries to resolve to the SSL enabled version of the URL instead of HTTP because of `is_demo_node` but the RPi is not set up as demo node..

When is_demo_node bool function is commented out, the API_URL properly gets assigned.

Code section that was edited:
```
else:
    SWAGGER_URL = '/api/docs'
    swagger_address = getenv("SWAGGER_HOST", my_ip)

    if settings['use_ssl']: # or is_demo_node:
        API_URL = 'https://{}/api/swagger.json'.format(swagger_address)
    elif LISTEN == '127.0.0.1' or swagger_address != my_ip:
        API_URL = "http://{}/api/swagger.json".format(swagger_address)
    else:
        API_URL = "http://{}:{}/api/swagger.json".format(swagger_address, PORT)
```

#### Reproduction Steps

Without enabling SSL on your Screenly OSE Pi, visit the API url http://ip.of.your.rpi/api/docs/

You should get a:
```
Failed to load spec.
and
Online validator badge showing INVALID
```

![Screen Shot 2020-11-16 at 12 01 28 AM](https://user-images.githubusercontent.com/24350198/99217859-0ad9ce00-27a7-11eb-93c2-7af5766bd009.png)

**Comment by ealmonte32** [comment]
Need to solve this so want to open up this ticket again..

config has use_ssl as off, and the Pi is not as demo_node, so swagger should be trying to connect as "https"..

![image](https://user-images.githubusercontent.com/24350198/202568305-4355fc05-6e94-4b1f-ba46-b1be06374832.png)

**Comment by vpetersson** [comment]
Good find.

**Comment by ealmonte32** [comment]
Current page when pressing API docs link:

![image](https://user-images.githubusercontent.com/24350198/202572277-9404747d-9020-4f45-94e2-628f07713cf8.png)

If manually change address to use HTTP, swagger works:
![image](https://user-images.githubusercontent.com/24350198/202572396-a838c257-a7d6-4569-b15b-ed73a2855713.png)
