### ISSUE TITLE
Failed to install the experimental version on raspberry Pie 4 in run docker compose

### ISSUE THREAD

**Issue by wmysummer** [Screenly/screenly-ose#1411]
#### Environment

* Raspberry Pi Hardware Version: Raspberry Pi 4
* Raspberry Pi Network Setup: Ethernet
* Screenly OSE Version:Experimental
I use balena etcher to burn "2020-08-20-raspios-buster-armhf- lite.img ", and then use" $bash < (curl - sl https://www.screenly.io/install-ose.sh ）"Installation of the experimental version has failed all the time in run docker compose
![image](https://user-images.githubusercontent.com/28956825/99656319-b2048100-2a97-11eb-9186-06edf89f88c8.png)

**Comment by vpetersson** [comment]
Yeah this is expected. I'm working on this right now. Hope to have something ready in the coming days.

**Comment by wmysummer** [comment]
> Yeah this is expected. I'm working on this right now. Hope to have something ready in the coming days.

OK，Thanks.

**Comment by vpetersson** [comment]
@wmysummer Try upgrading to the latest "developer" release now.
