### ISSUE TITLE
Idiot N00b question

### ISSUE THREAD

**Issue by Heinz-YVR** [Screenly/screenly-ose#1412]
OK, hopefully my stupidity does not get me flamed. I thought this would be an easy install. I bought a number of 8 Gig Raspberry Pi 4B's and flashed the most recent image onto a 4 gig SD card using Etcher. Plopped the card into the pi and tried booting. No joy. I am the epitome of a n00b, the most I have done with a pi is install Kodi, which was dead easy. Could someone give me an easy to follow complete idiot guide to getting this going. I have a windows laptop and the Pi is connected to a TV without a keyboard or mouse. Thank you and sorry for the idiot question

Apparently the Elf is not compatible. Uggg, damn midget green critters are messing with me.

I now have balena running on the pi in hopes this would help. Unfortunately the instructions do not really make sense to me. I think I need to bash the damn incompatible elf into submission?

I also found something on the screenly site which said it could be installed by using Noobs, unfortunately screenly was not an option on there, either. Why does this jesus character hate me? was it because I made an elf joke?

**Comment by vpetersson** [comment]
@Heinz-YVR lol

See https://github.com/Screenly/screenly-ose/issues/1389
