### ISSUE TITLE
Installing with balenaCloud Fails

### ISSUE THREAD

**Issue by viradhanus** [Screenly/screenly-ose#1431]
I tried to install Screenly OSE with balenaCloud but it throws "Remote build failed"

#### Environment

* Raspberry Pi Hardware Version: 3 B+
* Raspberry Pi Network Setup: built-in WiFi

![Screenshot from 2020-12-03 02-45-20](https://user-images.githubusercontent.com/59219626/100932958-a2af1a00-3512-11eb-9da6-d5c00a245c6a.png)

**Comment by vpetersson** [comment]
I've pushed changes to master that should resolve this.
