### ISSUE TITLE
Screenly OSE showing black screen while it is turn to video on assets list-RPi 4 Model B

### ISSUE THREAD

**Issue by javad87** [Screenly/screenly-ose#1434]
#### Overview of the Issue

I did the same things that mentioned in [issue](https://github.com/Screenly/screenly-ose/issues/1389), everything is ok except when it comes to showing video assets, screen will be black for a moment till moving to a next asset which is a pic and it shows pic correclty....

I increased GPU to 256, file is around 2 minutes and 13MB , mp4 codec H264
What should I do to solve black screen problem?

#### Reproduction Steps
screenly log:

Dec 01 17:41:57 raspberrypi python[3119]: Displaying video /home/pi/screenly_assets/9f0e815ed52840199fb48dcebd2722e1 for 1
Dec 01 17:41:57 raspberrypi python[3119]: current url is file:///tmp/screenly_html/black_page.html
Dec 01 17:44:50 raspberrypi python[3119]: Last update: 2020-12-01 10:18:41.020324
Dec 01 17:44:50 raspberrypi python[3119]: get_next_asset
Dec 01 17:44:50 raspberrypi python[3119]: refresh_playlist
Dec 01 17:44:50 raspberrypi python[3119]: refresh: counter: (0) deadline (2020-11-29 22:07:00) timecur (2020-12-01 14:14:5
Dec 01 17:44:50 raspberrypi python[3119]: update_playlist
Dec 01 17:44:50 raspberrypi python[3119]: Generating asset-list...
Dec 01 17:44:50 raspberrypi python[3119]: generate_asset_list deadline: 2020-11-29 22:07:00
Dec 01 17:44:50 raspberrypi python[3119]: get_next_asset after refresh
Dec 01 17:44:50 raspberrypi python[3119]: get_next_asset counter 0 returning asset 1 of 4
Dec 01 17:44:50 raspberrypi python[3119]: Showing asset Pasargad.jpg (image)
Dec 01 17:44:50 raspberrypi python[3119]: Asset URI /home/pi/screenly_assets/55de0f08b0ff465e9441164d3dff66dc
Dec 01 17:44:50 raspberrypi python[3119]: Already showing file:///tmp/screenly_html/black_page.html, reloading it.
Dec 01 17:44:50 raspberrypi python[3119]: Sleeping for 10
Dec 01 17:45:00 raspberrypi python[3119]: Last update: 2020-12-01 10:18:41.020324
Dec 01 17:45:00 raspberrypi python[3119]: get_next_asset
Dec 01 17:45:00 raspberrypi python[3119]: refresh_playlist
Dec 01 17:45:00 raspberrypi python[3119]: refresh: counter: (0) deadline (2020-11-29 22:07:00) timecur (2020-12-01 14:15:0
Dec 01 17:45:00 raspberrypi python[3119]: update_playlist
Dec 01 17:45:00 raspberrypi python[3119]: Generating asset-list...
Dec 01 17:45:00 raspberrypi python[3119]: generate_asset_list deadline: 2020-11-29 22:07:00
Dec 01 17:45:00 raspberrypi python[3119]: get_next_asset after refresh
Dec 01 17:45:00 raspberrypi python[3119]: get_next_asset counter 0 returning asset 2 of 4
Dec 01 17:45:00 raspberrypi python[3119]: Showing asset Hafez.jpg (image)
Dec 01 17:45:00 raspberrypi python[3119]: Asset URI /home/pi/screenly_assets/4456bd4409aa4b6f8f114a11babe420b
Dec 01 17:45:00 raspberrypi python[3119]: Already showing file:///tmp/screenly_html/black_page.html, reloading it.
Dec 01 17:45:00 raspberrypi python[3119]: Sleeping for 10
Dec 01 17:45:10 raspberrypi python[3119]: Last update: 2020-12-01 10:18:41.020324
Dec 01 17:45:10 raspberrypi python[3119]: get_next_asset
Dec 01 17:45:10 raspberrypi python[3119]: refresh_playlist
Dec 01 17:45:10 raspberrypi python[3119]: refresh: counter: (0) deadline (2020-11-29 22:07:00) timecur (2020-12-01 14:15:1
Dec 01 17:45:10 raspberrypi python[3119]: update_playlist
Dec 01 17:45:10 raspberrypi python[3119]: Generating asset-list...
Dec 01 17:45:10 raspberrypi python[3119]: generate_asset_list deadline: 2020-11-29 22:07:00
Dec 01 17:45:10 raspberrypi python[3119]: get_next_asset after refresh
Dec 01 17:45:10 raspberrypi python[3119]: get_next_asset counter 0 returning asset 3 of 4
Dec 01 17:45:10 raspberrypi python[3119]: Showing asset h264-low.mp4 (video)
Dec 01 17:45:10 raspberrypi python[3119]: Asset URI /home/pi/screenly_assets/902596d7542f4de59a5d929307e97e5e
Dec 01 17:45:10 raspberrypi python[3119]: Displaying video /home/pi/screenly_assets/902596d7542f4de59a5d929307e97e5e for 1
Dec 01 17:45:10 raspberrypi python[3119]: current url is file:///tmp/screenly_html/black_page.html
#### Environment

* Raspberry Pi Hardware Version:omxplayer Version: 20190723+gitf543a0d-1,I use buster image, Rpi 4 model B
* Raspberry Pi Network Setup: built-in WiFi, Using TP-Link wireless modem
* Screenly OSE Version: lastest version on develpment branch (pulled on Monday 30th December 2020)
* OS: rasbian buster image

**Comment by vpetersson** [comment]
Won't spend time on this as [1426](https://github.com/Screenly/screenly-ose/issues/1426) will replace it.
