### ISSUE TITLE
Periodic Reloads of Repeated Web Assets

### ISSUE THREAD

**Issue by gohanman** [Screenly/screenly-ose#1437]
#### Overview of the Issue

I'm looking for more info about this: https://github.com/Screenly/screenly-ose/blob/master/viewer.py#L456-L457

I'm trying to accomplish exactly what the FIXME says and it references a commit, but Github just gives me a 404 for that SHA. Does anyone have a record of what the suggested solution was?

**Comment by vpetersson** [comment]
The best way to do this is write something that uses the [API](https://ose.demo.screenlyapp.com/api/docs/) to accomplish this task.
