### ISSUE TITLE
Balena issues with most recent build

### ISSUE THREAD

**Issue by singh87** [Screenly/screenly-ose#1441]
#### Overview of the Issue

So this all started a week back when I updated my screenly-ose because my sd card had corrupted. I purchased a high quality sd card this time around and proceeded with flashing balenaOS and installing screenly. I was never able to successfully deploy to balena because of [#1431](https://github.com/Screenly/screenly-ose/issues/1431). This seems to have been fixed with the most recent commit.

The issue I'm having now is that redis keeps exiting/crashing in balena and I have no idea how to fix it.
![image](https://user-images.githubusercontent.com/9346189/101114086-57dee200-35a6-11eb-9b40-869307a88541.png)

#### Steps

1. Flash latest BalenaOS to sd card
2. Balena push most recent commit from master branch
3. Redis keeps restarting at this point
4. Public url for balena stops working after recovering assets from backup and rebooting the device

#### Environment

* Raspberry Pi Hardware Version: Pi Zero W
* Raspberry Pi Network Setup: built-in WiFi
* Screenly OSE Version: lastest Dec 3, 2020 commit

**Comment by vpetersson** [comment]
Strange. Looks like a communication error. Make sure the redis container is working properly.

**Comment by vpetersson** [comment]
Found and fixed the error in master.

**Comment by singh87** [comment]
Ok so I'm still getting this issue. It seemed to be fixed with the newest commit but when I upload my backup assets to screenly, I get the error message "The operation failed. Please reload the page and try again.". Reloading the page didn't help so I restarted the device and get the redis error again every 32 seconds.

**Comment by singh87** [comment]
@vpetersson Could you please reopen this?

**Comment by vpetersson** [comment]
Can't really spend cycles on this. All my focus is on getting the experimental branch merged into master. Will look into this if it is still an issue after that.

**Comment by singh87** [comment]
I completely understand. I actually ended up ordering a raspberry pi 3b+ and balena/screenly work fine on there. I'm guessing the pi-zero just isn't powerful enough to run the latest build anymore.
