### ISSUE TITLE
Custom root CA Certificate / ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by LeSnowTiger** [Screenly/screenly-ose#1464]
#### Overview of the Issue
Some internal webservices use a self singed certificate. After the update to the new docker version, screenly viewer does not trust them anymore (since the rootCA is unknown to the container). 

Maybe its just me, but I think there needs to be an option to import a Root CA certificate to the docker container.

 #### Reproduction Steps
Steps to reproduce this issue, eg:
* Add asset url with a self singed certificate.
* Watch viewer
* Error: ERR_CERT_AUTHORITY_INVALID

#### Environment
* Raspberry Pi Hardware Version: Pi 4 2GB
* Raspberry Pi Network Setup: built-in WiFi
* Screenly OSE Version: latest master / dev

#### Proposed fix
Add the custom Root CA certificate to the dockers trusted storage (maybe there is a better way but this should work):
```
ADD your_ca_root.crt /usr/local/share/ca-certificates/foo.crt
RUN chmod 644 /usr/local/share/ca-certificates/foo.crt && update-ca-certificates
```

**Comment by vpetersson** [comment]
Hmm i don't think this is a use case we want to support upstream. The easiest solution for this is to simply create another Dockerfile that builds on the existing one and just adds this.
