### ISSUE TITLE
Celery container crashing

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#1471]
#### Overview of the Issue

It appears as the celery container crashes on master

Logs:

```
$ docker logs screenly_srly-ose-celery_1
* failed to open vchiq instance
* failed to open vchiq instance
* failed to open vchiq instance
* failed to open vchiq instance
* failed to open vchiq instance
* failed to open vchiq instance
* failed to open vchiq instance
* failed to open vchiq instance
* failed to open vchiq instance
[...]
```

#### Reproduction Steps

Unclear atm

#### Environment

* Raspberry Pi Hardware Version: 3 Model B
* Raspberry Pi Network Setup: (ex. built-in WiFi, Ethernet, USB WiFi Adapter): WiFi
* Screenly OSE Version: Latest on master

**Comment by ealmonte32** [comment]
Happening to me as well now troubleshooting with Pi4.

**Comment by ealmonte32** [comment]
Fix for it found, dealing with devices for dev/vchiq not set on dockerfile for celery but instead on viewer.

**Comment by ealmonte32** [comment]
this can be closed, fixed on https://github.com/Screenly/screenly-ose/pull/1477
