### ISSUE TITLE
API Docs is not working

### ISSUE THREAD

**Issue by viradhanus** [Screenly/screenly-ose#1472]
[API Docs](https://ose.demo.screenlyapp.com/api/docs/) in README.md does not load.

**Comment by vpetersson** [comment]
This should be working now. Had to update it based on the recent developments. However, you can always access the API docs on your local Pi.

**Comment by viradhanus** [comment]
@vpetersson Thank you... But still it gives 502 error.. hopefully you guys will fix it soon.
![Screenshot from 2021-01-14 16-14-46](https://user-images.githubusercontent.com/59219626/104580915-ddfd4680-5683-11eb-8660-33413780b659.png)

**Comment by vpetersson** [comment]
The demo site is using the developer version and it's under active development. I just resolved it. Tl;dr, it had to do with docker images of various architectures clashing.
