### ISSUE TITLE
Install Fails; multiple attempts

### ISSUE THREAD

**Issue by voyager529** [Screenly/screenly-ose#1474]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Press Add Asset
* Enter the Asset URL ...
* Press "On"
* Wait for the asset to show up on the screen

#### Environment

* Raspberry Pi Hardware Version:
* Raspberry Pi Network Setup: (ex. built-in WiFi, Ethernet, USB WiFi Adapter)
* Screenly OSE Version:

Hello!!

I'm trying to deploy Screenly for a friend; no success. Core stuff:

Raspberry Pi 3A+
DietPi 6.34.3 (Debian Buster base)
Wi-Fi connectivity (known, working, tested connectivity)
Ran the normal install script on the front Github page; most combinations (stable/unstable, network/no network, upgrade/no upgrade).

Install transcript:

       _____                           __         ____  _____ ______
      / ___/_____________  ___  ____  / /_  __   / __ \/ ___// ____/
      \__ \/ ___/ ___/ _ \/ _ \/ __ \/ / / / /  / / / /\__ \/ __/
     ___/ / /__/ /  /  __/  __/ / / / / /_/ /  / /_/ /___/ / /___
    /____/\___/_/   \___/\___/_/ /_/_/\__, /   \____//____/_____/
                                     /____/
Screenly OSE requires a dedicated Raspberry Pi / SD card.
You will not be able to use the regular desktop environment once installed.

Do you still want to continue? (y/N)
________________________________________

Which version/branch of Screenly OSE would you like to install:

 Press (1) for the Production branch, which is the latest stable.
 Press (2) for the Development/Master branch, which has the latest features and fixes, but things may break.

You selected: Production

Do you want Screenly to manage your network? This is recommended for most users because this adds features to manage your network. (Y/n)

Would you like to perform a full system upgrade as well? (y/N)
+ REPOSITORY=https://github.com/screenly/screenly-ose.git
+ sudo mkdir -p /etc/ansible
+ echo -e '[local]\nlocalhost ansible_connection=local'
+ sudo tee /etc/ansible/hosts
+ '[' '!' -f /etc/locale.gen ']'
+ sudo sed -i s/apt.screenlyapp.com/archive.raspbian.org/g /etc/apt/sources.list
+ sudo apt update -y
Hit:1 https://deb.debian.org/debian buster InRelease
Hit:2 https://deb.debian.org/debian buster-updates InRelease
Hit:3 https://deb.debian.org/debian-security buster/updates InRelease
Hit:4 https://deb.debian.org/debian buster-backports InRelease
Hit:5 https://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
+ sudo apt-get purge -y python-setuptools python-pip python-pyasn1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'python-pyasn1' is not installed, so not removed
Package 'python-setuptools' is not installed, so not removed
Package 'python-pip' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ sudo apt-get install -y python-dev git-core libffi-dev libssl-dev whois
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
git is already the newest version (1:2.20.1-2+deb10u3).
libffi-dev is already the newest version (3.2.1-9).
python-dev is already the newest version (2.7.16-1).
whois is already the newest version (5.4.3).
libssl-dev is already the newest version (1.1.1d-0+deb10u4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ curl -s https://bootstrap.pypa.io/get-pip.py
+ sudo python
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting pip
  Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.3
    Uninstalling pip-20.3.3:
      Successfully uninstalled pip-20.3.3
Successfully installed pip-20.3.3
+ '[' n == y ']'
+ export MANAGE_NETWORK=false
+ MANAGE_NETWORK=false
+ sudo pip install ansible==2.8.8
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting ansible==2.8.8
  Using cached ansible-2.8.8.tar.gz (12.7 MB)
Collecting jinja2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting PyYAML
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting cryptography
  Using cached cryptography-3.3.1.tar.gz (539 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5zpJ1A/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"''
       cwd: None
  Complete output (125 lines):
  DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
  Collecting setuptools>=40.6.0
    Using cached setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
  Collecting wheel
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting cffi>=1.12
    Using cached cffi-1.14.4.tar.gz (471 kB)
  Collecting pycparser
    Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
  Building wheels for collected packages: cffi
    Building wheel for cffi (setup.py): started
    Building wheel for cffi (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y_TMHW/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y_TMHW/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-Q4mu3k
         cwd: /tmp/pip-install-y_TMHW/cffi/
    Complete output (48 lines):
    unable to execute 'aarch64-linux-gnu-gcc': No such file or directory
    unable to execute 'aarch64-linux-gnu-gcc': No such file or directory

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

        Trying to continue anyway.  If you are trying to install CFFI from
        a build done in a different context, you can ignore this warning.

    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-2.7
    creating build/lib.linux-aarch64-2.7/cffi
    copying cffi/recompiler.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/verifier.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/__init__.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/lock.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/api.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/cparser.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/error.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/model.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/_embedding.h -> build/lib.linux-aarch64-2.7/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-aarch64-2.7
    creating build/temp.linux-aarch64-2.7/c
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-aarch64-2.7/c/_cffi_backend.o
    unable to execute 'aarch64-linux-gnu-gcc': No such file or directory
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for cffi
    Running setup.py clean for cffi
  Failed to build cffi
  Installing collected packages: setuptools, wheel, pycparser, cffi
      Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y_TMHW/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y_TMHW/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-swzeNr/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-5zpJ1A/overlay --compile --install-headers /tmp/pip-build-env-5zpJ1A/overlay/include/python2.7/cffi
           cwd: /tmp/pip-install-y_TMHW/cffi/
      Complete output (48 lines):
      unable to execute 'aarch64-linux-gnu-gcc': No such file or directory
      unable to execute 'aarch64-linux-gnu-gcc': No such file or directory

          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.freenode.net.)

          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.

      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-2.7
      creating build/lib.linux-aarch64-2.7/cffi
      copying cffi/recompiler.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/verifier.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/__init__.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/lock.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/api.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/cparser.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/error.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/commontypes.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/model.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/_embedding.h -> build/lib.linux-aarch64-2.7/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-2.7/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-aarch64-2.7
      creating build/temp.linux-aarch64-2.7/c
      aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QCkEc0/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-aarch64-2.7/c/_cffi_backend.o
      unable to execute 'aarch64-linux-gnu-gcc': No such file or directory
      error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y_TMHW/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y_TMHW/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-swzeNr/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-5zpJ1A/overlay --compile --install-headers /tmp/pip-build-env-5zpJ1A/overlay/include/python2.7/cffi Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5zpJ1A/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
+ sudo -u pi ansible localhost -m git -a 'repo=https://github.com/screenly/screenly-ose.git dest=/home/pi/screenly version=production force=no'
sudo: unknown user: pi
sudo: unable to initialize policy plugin
+ cd /home/pi/screenly/ansible
/dev/fd/63: line 182: cd: /home/pi/screenly/ansible: No such file or directory
+ sudo -E ansible-playbook site.yml --skip-tags system-upgrade
sudo: ansible-playbook: command not found
++ ip -4 route get 8.8.8.8
++ awk '{print $7}'
++ tr -d '\n'
+ export MY_IP=10.0.0.20
+ MY_IP=10.0.0.20
++ grep MemTotal /proc/meminfo
++ awk '{print $2}'
+ TOTAL_MEMORY_KB=470960
++ echo 470960 '*' 0.7
++ bc
+ export VIEWER_MEMORY_LIMIT_KB=329672.0
+ VIEWER_MEMORY_LIMIT_KB=329672.0
+ sudo -E docker-compose -f /home/pi/screenly/docker-compose.yml -f /home/pi/screenly/docker-compose.override.yml pull
sudo: docker-compose: command not found
+ sudo -E docker-compose -f /home/pi/screenly/docker-compose.yml -f /home/pi/screenly/docker-compose.override.yml up -d
sudo: docker-compose: command not found
+ sudo apt-get autoclean
Reading package lists... Done
Building dependency tree
Reading state information... Done
+ sudo apt-get clean
+ sudo docker system prune -f
sudo: docker: command not found
+ sudo apt autoremove -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ sudo find /usr/share/doc -depth -type f '!' -name copyright -delete
+ sudo find /usr/share/doc -empty -delete
+ sudo rm -rf /usr/share/man /usr/share/groff '/usr/share/info/*' /usr/share/lintian /usr/share/linda /var/cache/man
+ sudo find /usr/share/locale -type f '!' -name en '!' -name 'de*' '!' -name 'es*' '!' -name 'ja*' '!' -name 'fr*' '!' -name 'zh*' -delete
+ sudo find /usr/share/locale -mindepth 1 -maxdepth 1 '!' -name 'en*' '!' -name 'de*' '!' -name 'es*' '!' -name 'ja*' '!' -name 'fr*' '!' -name 'zh*' '!' -name locale.alias -exec rm -r '{}' ';'
+ sudo chown -R pi:pi /home/pi
chown: invalid user: ‘pi:pi’
+ '[' '!' -f /etc/sudoers.d/010_pi-nopasswd ']'
+ check_defaultpw
+ '[' production = master ']'
+ '[' production = production ']'
+ '[' false = false ']'
+ set +x
The default raspberry pi password was not detected, continuing with installation...
++ git rev-parse --abbrev-ref HEAD
fatal: not a git repository (or any of the parent directories): .git
++ git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git
++ lsb_release -a
/dev/fd/63: line 279: lsb_release: command not found
+ echo -e 'Screenly version: @\n'
+ '[' false = false ']'
+ set +x
Installation completed.
You need to reboot the system for the installation to complete. Would you like to reboot now? (y/N)

Note that the lines between "Installing build dependencies ... error" and "+ sudo -u pi ansible localhost -m git -a 'repo=https://github.com/screenly/screenly-ose.git dest=/home/pi/screenly version=production force=no'" appear in red in the terminal window.

I appreciate the assist.

edit: format fix
edit 2: I'm sorry I don't spend enough time on Github to know how to do raw text in a comment; here's a pastebin link:
https://pastebin.com/xqLbEFqA

**Comment by vpetersson** [comment]
> DietPi 6.34.3 (Debian Buster base)

This is not supported. We have not tested it at all. Please switch to Raspbian OS Buster Lite as the base image.

Please switch to the developer version and Raspbian OS Lite and that will likely solve the issue. There are a lot of upstream changes in the developer version that will be brought into the next production version.

Alternatively, use the latest production disk image.
