### ISSUE TITLE
VNC Black Screen

### ISSUE THREAD

**Issue by Arodriguez81** [Screenly/screenly-ose#1476]
#### Overview of the Issue

Screenly OSE is working fine, when try to VNC to PI I only see a Black Screen
But I can see the splash screen with the URL.

I tried both options headless and HDMI, wondering if this is a limitation on Screenly side or Raspberry
Do I need Full Raspberry OS instead of Lite, My concern is am I going to have the same behavior?

Please advise

#### Environment

* Raspberry Pi Hardware Version: 3 B+
* Raspberry Pi Network Setup: built-in WiFi and Ethernet
* Screenly OSE Version: 10.1 Release

**Comment by vpetersson** [comment]
See [this comment](https://github.com/Screenly/screenly-ose/issues/1470#issuecomment-758805196).
