### ISSUE TITLE
non-existing sudo.conf file being called

### ISSUE THREAD

**Issue by ealmonte32** [Screenly/screenly-ose#1478]
Reading some journal logs to see of any potential errors, saw this one:
`screenlypi4 90130a749e08[568]: chown: cannot access '/etc/sudo.conf': No such file or directory`

Looked for area on code that references this file:
```
# For whatever reason Raspbian messes up the sudo permissions
..
..
chown -R root:root /etc/sudo.conf
```

this file does not exist under /etc/ when I go into the container:
```
root@90130a749e08:/usr/src/app# ls /etc/ | grep -i "conf"
adduser.conf
ca-certificates.conf
debconf.conf
deluser.conf
gai.conf
host.conf
ld.so.conf
ld.so.conf.d
libaudit.conf
mke2fs.conf
nsswitch.conf
pam.conf
pip.conf
resolv.conf
sensors3.conf
sysctl.conf
ts.conf
ucf.conf
xattr.conf
root@90130a749e08:/usr/src/app# ls /etc/ | grep -i "sudo.conf"
root@90130a749e08:/usr/src/app# 
```

#### Environment

* Raspberry Pi Hardware Version: Pi4
* Screenly OSE Version: master

**Comment by vpetersson** [comment]
This shouldn't impact anything. I've pushed a fix that silences the output.
