### ISSUE TITLE
Quickest way to merge updates from github into my install

### ISSUE THREAD

**Issue by Goteez** [Screenly/screenly-ose#1479]
Quick question: I just installed the latest Screenly OSE on a buster image yesterday using the devel/master branch, and today its showing me in the browser there are updates available. Short of running the whole bash/curl script, is there a quicker way to merge in the latest commits to my install? Or is that still the best way to do it, and no shortcuts recommended?

**Comment by vpetersson** [comment]
Currently, that is the best way. Or you can use the `bin/run_upgrade.sh` script, which is basically a shorthand for that `curl` script. That said, I am due to refactor this now that we have moved over to Docker. The long-term plan is to do automatic updates.

**Comment by Goteez** [comment]
Thanks!
