### ISSUE TITLE
Add RTMP/livestream output?

### ISSUE THREAD

**Issue by tedbragg** [Screenly/screenly-ose#1483]
First timer here—any plans to add RTMP output for livestreaming? This would be a big help during our conferences. Everyone has smartphones or tablets we could stream directly to, rather than deploy dozens of Pi-screens.

**Comment by vpetersson** [comment]
Hi there,

No, that's outside of the scope of Screenly and Screenly OSE. There are probably a lot of more suitable tools out there for doing scheduling/streaming than this project. Basically, if there is no screen to output to, it's not a fit for Screenly.
