### ISSUE TITLE
Change port screenly

### ISSUE THREAD

**Issue by fbsanches** [Screenly/screenly-ose#1489]
In the current version is it possible to change the default port 80 to another one? Example: 5000

**Comment by vpetersson** [comment]
You'd have to fork the repo and use your own `docker-compose.yaml`-file, but all you'd need to do (theoretically) is to change all reference of 80 in https://github.com/Screenly/screenly-ose/blob/master/docker-compose.yml

**Comment by fbsanches** [comment]
but i don't use docker and even changing it doesn't work. but still grateful for the help.

**Comment by fbsanches** [comment]
I decided by changing the nginx. thankful
