### ISSUE TITLE
RPI4, This site can't be reached

### ISSUE THREAD

**Issue by Robiv8** [Screenly/screenly-ose#1506]
#### Environment

* Raspberry Pi Hardware Version: raspi4 b 8GB
* Raspberry Pi Network Setup: built-in WiFi, Ethernet
* Screenly OSE Version: latest over bash <(curl -sL https://www.screenly.io/install-ose.sh)

Raspi4 wit the latest Buster
all updates and upgrades are doing
installing screenly OSE developer version over the terminal
manage network = no
full system upgrade = no
installation without error. OK 

and?
no website no screenly
This site can't be reached
srly-ose-nginx's server IP dress could not be found

ERR_Name_not_resolved 

what can I do?

**Comment by shaqaruden** [comment]
We are looking into this over here https://github.com/Screenly/screenly-ose/issues/1508

**Comment by shaqaruden** [comment]
if you ran `docker ps` you will see that the nginx container is constantly restarting.

Try this

```
$ cd ~/screenly
$ git checkout master
$ git pull
$ ./bin/build_containers.sh
$ ./bin/upgrade_containers.sh
```

**Comment by shaqaruden** [comment]
Please look at the last comment here https://github.com/Screenly/screenly-ose/issues/1508 to find the solution to this problem
