### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by shaqaruden** [Screenly/screenly-ose#1507]
When will the move to Python 3 take place?

**Comment by vpetersson** [comment]
Depends on a large number of variables, including how many contributors we get.

**Comment by shaqaruden** [comment]
I would help, but I am not well versed in Python

**Comment by vpetersson** [comment]
Thanks for the offer @shaqaruden. It's unfortunately a fairly large task that is hard to break apart. We've made some progress recently with the move to Docker, which will allow us to work on one components at the time. Yet, even so it's not a trivial effort.
