### ISSUE TITLE
self-signed certificates aren't accepted, touchscreen not working

### ISSUE THREAD

**Issue by Gifford47** [Screenly/screenly-ose#1516]
#### Overview of the Issue

I have add an asset like: https://192.168.1.100:8443/basicui/app?sitemap=main, but the viewer cant display it. It show the error message "ERR_CERT_AUTHORITY_INVALID", but i already set verify_ssl = False in the conf.
Also, the touchscreen/mouse no longer works with the latest Screenly version. i can't click anything.

#### Reproduction Steps

Add an asset with s self-signed certificate and show it on the screen.

#### Environment

* Raspberry Pi Hardware Version: RPI 3B+ with official 7" Touchscreen
* Raspberry Pi Network Setup: Ethernet
* Screenly OSE Version: WebView-v0.2, 19.12.2020

**Comment by DarthDestroyer** [comment]
Found the same Problem!

Just wanted to use my local Page (only available with https) on the Screen, but "ERR_CERT_AUTHORITY_INVALID".

Wouldnt it be possible to add that Cert to the Viewer? Or something like that?
(verify_ssl isnt enought)

**Comment by vpetersson** [comment]
Yeah exactly. The solution is to install the cert into the viewer container.

**Comment by DarthDestroyer** [comment]
Is there a recommended way for that?

**Comment by vpetersson** [comment]
No, just the regular way you would do it on Debian.

**Comment by nicomiguelino** [comment]
Got it, @vpetersson

**Comment by DarthDestroyer** [comment]
Found no way to get it working! moved the cert around, added it nearly everywhere but nothing worked as "expected"...

Any Info / ETA of that Documentation? Merci!

**Comment by vpetersson** [comment]
Did you make the changes inside the container(s)? If not, it will not work. We'll add some tools for this later, but it's not something we have on the immediate roadmap.

**Comment by DarthDestroyer** [comment]
Yeah, did it in the Container itself @screenly-anthias-viewer-1

**Comment by vpetersson** [comment]
You also need to do it to the server container.

**Comment by DarthDestroyer** [comment]
OK - did it on both containers - but no success!

Is it probably because of the trust store?
Like for example https://thomas-leister.de/en/how-to-import-ca-root-certificate/
