### ISSUE TITLE
Screenly-OSE on RPi4 "Internal Server Error"

### ISSUE THREAD

**Issue by hsilva090** [Screenly/screenly-ose#1520]
Hi,
Unfortunately I can't install screenly-ose without going through a proxy. This way I enabled the proxy in the environment variables and also enabled the proxy for docker.
Performing communication tests, everything went well and ready to perform the installation!
Let's go!

_bash <(curl -sL https://www.screenly.io/install-ose.sh)_

With options: Development (y)    NetworkManager (n)    SystemUpgrade (n)

Perfect! It installed without any problems, however the page with the IP address does not appear. Only an "Internal Server Error" page appears.

I tried to check if it could be a docker communication error, but the docker seems to be working using the command:

_docker run hello-world_

I tried to upgrade_containers with upgrade_containers.sh, no problems in here.

If I connect with normal link to Internet (without proxy), it works.

Please I need this running with internal IP Address!

**Comment by vpetersson** [comment]
Yeah Proxy is not really something we have tested nor officially support. It may or may not work, but it's not something that I think we can justify spending development cycles on. Contributions are welcome however.
