### ISSUE TITLE
How can I add scrolling menu items?

### ISSUE THREAD

**Issue by HootisTigglebits** [Screenly/screenly-ose#1521]
I have made a menu board in photoshop and would like to add a gif to it.  I've noticed Screenly OSE displays a gif by itself, but when I add that same gif to my menu board in photoshop and export the entire image as a gif there is no animation.  What can I do to fix this?

* Raspberry Pi Hardware Version: 3B
* Raspberry Pi Network Setup: Ethernet
* Screenly OSE Version: production@d12df55

**Comment by vpetersson** [comment]
Try switching to the developer version. It uses a newer browser that should hopefully support this (re-run the [installation](https://github.com/Screenly/screenly-ose#installing-on-raspbianraspberry-pi-os)).

**Comment by HootisTigglebits** [comment]
How do I switch to the developer version?

**Comment by vpetersson** [comment]
You need to SSH into the device and then re-run the installation. If you don't have SSH enabled, you need to first [enable it](https://www.raspberrypi.org/documentation/remote-access/ssh/).
