### ISSUE TITLE
Just installed the dev version and cannot pull up screenly ose gui. 

### ISSUE THREAD

**Issue by HootisTigglebits** [Screenly/screenly-ose#1525]
I just finished installing the dev version of screenly ose and have it connected to my network wirelessly, but cannot pull up the Screenly OSE gui on my phone by going to its IP address. On the tv the Screenly splash screen is displayed with the text system-udevd.service in the lower left corner.  How can I fix this?

**Comment by vpetersson** [comment]
Best guess is that either the installation failed or that the SD card has been busted (very common). If you're seeing anything like that, it likely didn't boot properly.

**Comment by HootisTigglebits** [comment]
I’ve done the install twice now with no luck.   What do you mean “busted”?  I’ve never heard of that terminology when referring to a SD card before.

**Comment by vpetersson** [comment]
Busted as in broken.

**Comment by HootisTigglebits** [comment]
Thanks.  I reformatted the sd card and reinstalled the dev version.  I was able to get to the webpage gui, but have now ran into another issue that I just posted.
