### ISSUE TITLE
how to make changes in the templates

### ISSUE THREAD

**Issue by pittipuk** [Screenly/screenly-ose#1533]
Hello, I want to make a few changes in the html documents in /home/pi/screenly/templates.
But how does screenly show the changes after a reboot? 
Have the changed htmls to be loaded into the docker container or what has to be done?
Thanks for a little help and your nice work!
Greetings!

**Comment by pittipuk** [comment]
I  suspected something like this ;-) Thank you!
Is there something like an instruction how to fork and build ....?

**Comment by vpetersson** [comment]
No, there aren't any formal instructions for this unfortunately. Reading the `docker-compose` files should give you a good start however.

**Comment by pittipuk** [comment]
I tried something like:
	cd ~/screenly
	./bin/build_containers.sh
	./bin/upgrade_containers.sh
but without success.

**Comment by vpetersson** [comment]
No, because that will pull images from upstream and overwrite your local containers. Read over the scripts and docker-compose file and it should become pretty clear what needs to be done.
