### ISSUE TITLE
Screenly OSE working with folder files

### ISSUE THREAD

**Issue by JhonathanJJGS** [Screenly/screenly-ose#1534]
Hello, i'm trying to use screenly with one local server to provide the assests, i'm using the html css background image to provide the images, but i need to do the same with video, there is any work around? 

Scope: 
I want to configure screenly in one lan without internet access, and to make the things easy i cant use the web interface to provide the assests. 
Need to do something like place the file in one folder and automatic screenly starts to presents the content. 
As i said in the begin, i'm using the html way that takes the image as the body background, but i need to do the same with videos;

 
Screenly version: 
Last devolper compilation;

Hardware pi2b

**Comment by vpetersson** [comment]
Long story short, don't use a Raspberry Pi without RTC if you don't have a local NTP server on the network.

With regards to your idea, you probably want to use the API for that.

**Comment by JhonathanJJGS** [comment]
Thank you helped me alot, now thats working with api!!
