### ISSUE TITLE
Schedule recurring assets

### ISSUE THREAD

**Issue by jimmyhess** [Screenly/screenly-ose#1540]
Feature request:

Schedule recurring assets.

E.g. make asset active daily from 5:00 PM to 7:00 PM.

**Comment by vpetersson** [comment]
This isn't something we'll implement ourselves as this is available in the commercial version. If someone would like to contribute the code for it, that's a different story.

**Comment by ealmonte32** [comment]
@jimmyhess Can you close this since OSE does not support this, only the Commercial version of Screenly does.
Trying to cleanup stale and resolved issues.
