### ISSUE TITLE
Can I remotely connect to Screenly OSE over the internet?

### ISSUE THREAD

**Issue by HootisTigglebits** [Screenly/screenly-ose#1547]
#### remote connection. 
Is it possible to remotely connect to the Screenly OSE over the internet?  I’ve done it in the past by using my Windows 10 PC at home and our store’s windows 10 PC, but thought it would easier if I could just connect directly to the raspberry pi.

**Comment by vpetersson** [comment]
Certainly possible with port forwarding etc, but it's outside the scope of the Screenly OSE itself. You might want to check out our commercial offerings if you're looking for remote management.
