### ISSUE TITLE
 2020-07-17-Screenly-OSE.zip image requires internet access or will not display assets

### ISSUE THREAD

**Issue by MisterAnderson91** [Screenly/screenly-ose#1548]
#### Overview of the Issue

 2020-07-17-Screenly-OSE.zip image will not show any assets (.png,.jpg images and .mp4 video files tested) when configured to connect to a network with no internet access (blocked by proxy). The time has been configured correctly and assets have been uploaded and scheduled to run from 2000 to 2099 with only the blank black screenly logo page showing.

Having an unfiltered internet connection during boot (via USB tethering from smartphone) fixes whatever the issue is and assets continue working from then onwards.

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Apply 2020-07-17-Screenly-OSE.zip to SD card. Boot in rpi 3B+.
* First boot with no network connection, used local keyboard to switch to terminal, set an NTP server address in timesyncd that is available on local network to sync time, set all localization options in raspi-config, turned off overscan in raspi-config, rebooted
* At second boot, connect to wifi hotspot on rpi, connect to local wifi network
* Reboot in web interface
* At next reboot, attempt to upload and apply assets, assets will not appear, no matter their time options etc
* No other fixes work including subsequent reboots, changing date formatting, setting assets to being years into past and end years into future, disabling splash screen, etc
* Only fix found is to connect android phone (unknown if any other method will work) as USB device, enable "USB Tethering" on phone to share internet connection, then reboot screenly. Make sure to monitor phone and re-enable USB tethering on phone after poweroff/poweron during reboot
* Suddenly at boot, assets will begin working and playing
* This seems to continue through subsequent reboots and new asset uploads

#### Environment

* Raspberry Pi Hardware Version: 3B+
* Raspberry Pi Network Setup: built-in Wifi to network without direct internet access (blocked by network proxy system)
* Screenly OSE Version:  2020-07-17-Screenly-OSE.zip (Sprint 10.1)

**Comment by vpetersson** [comment]
This is expected. Offline support isn't really supported. See https://github.com/Screenly/screenly-ose/issues/764 for details.
