### ISSUE TITLE
NEed a way to change the Default duration to a longer time than 30 days

### ISSUE THREAD

**Issue by soundtechscott** [Screenly/screenly-ose#1549]
I am trying to set the default time to a VERY long time... I have about 200 pictures I want to scroll thru indefinitely...and I am always adding more

so I want to change the time value default to like 2000 Days
but it always populates the assets with 30 days instead

how can I make this auto set to a longer value or is there a file I can edit in the config manually to do this?

**Comment by vpetersson** [comment]
Easiest way to do that is to use the API.
