### ISSUE TITLE
Disable SSL on RaspPI3 

### ISSUE THREAD

**Issue by JhonathanJJGS** [Screenly/screenly-ose#1550]
Screenly on raspberry pi3 comes with ssl enabled how can i disable it?

#### Overview of the Issue

ssl enabled by default, need to disable it to work with curl

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Install screenly on raspberry pi 3 

#### Environment

* Raspberry Pi Hardware Version: Pi 3b
* Raspberry Pi Network Setup: Ethernet
* Screenly OSE Version: last release

**Comment by vpetersson** [comment]
This is not true. The only reason why you would need to disable SSL (which you *really* shouldn't) is if you either have an incorrect date set on the device *or* if your router/firewall does some sketchy Man-in-the-Middle (MiTM) to break the SSL.
