### ISSUE TITLE
Raspberry Pi 3 B+ new install with install-ose.sh script fails

### ISSUE THREAD

**Issue by ZhangXector** [Screenly/screenly-ose#1558]
#### Overview of the Issue

New install to Raspberry Pi 3 B+ (fresh Raspberry Pi OS Lite install) using the install script at https://www.screenly.io/install-ose.sh fails with the following error:

`./install-ose.sh: line 179: /home/pi/screenly/bin/upgrade_containers.sh: No such file or directory`

#### Reproduction Steps

On a fresh Raspberry Pi OS install:
Run: `bash <(curl -sL https://www.screenly.io/install-ose.sh)`
Select: Stable channel
Select: Do not manage network
Select: Perform a system upgrade
Wait for install to reach the point that it fails, exiting the install script.

#### Environment

* Raspberry Pi Hardware Version: 3 B+
* Raspberry Pi Network Setup: Ethernet (Wi-Fi disabled with rfkill)
* Screenly OSE Version: N/A

**Comment by rebootit** [comment]
Bump -- still an issue

**Comment by ealmonte32** [comment]
I will look into some of these issues today, some dont make sense if the repository is pulled down then the bin folder comes down with all files, including that one..

**Comment by ealmonte32** [comment]
I ran into docker-ce not being installed during installation (raspbian buster lite, do not use bullseye).. please see my comment here: https://github.com/Screenly/screenly-ose/issues/1559#issuecomment-1048480683
Worked afterwards.

**Comment by ZhangXector** [comment]
We actually tried both, but I feel like development didn't work either. Stable was just the one I used while writing the reproduction steps. It's been a while since we've tried it, I might be able to try it again tomorrow. Then I can let you know if the development version also has issues.

**Comment by ZhangXector** [comment]
It appears that Bullseye was the culprit. We just ran the installer for the dev version from a fresh Buster (lite) install, and it worked like a charm.
