### ISSUE TITLE
Change splashscreen duration

### ISSUE THREAD

**Issue by damienpeerbolte** [Screenly/screenly-ose#1563]
How can I change the splashscreen duration(the screen that displays the ip). I believe that there was a setting like that in earlier versions. Thanks!

**Comment by willworkforicecream** [comment]
I'm no expert but I believe you can go into viewer.py and change `SPLASH_DELAY = 60` to however many seconds you'd rather.

**Comment by damienpeerbolte** [comment]
Found it! Thanks!
