### ISSUE TITLE
Installation script is outdated. Some packages have no installation candidate.

### ISSUE THREAD

**Issue by NassimBentarka** [Screenly/screenly-ose#1568]
#### Overview of the Issue

The main installation script does not install properly on Raspbian Lite. My environment is Raspberry Pi Zero W. It looks like python-pip was renamed to python3-pip and other packages were renamed as well.
The result is that Screenly doesn't install on a fresh Raspbian Lite on Raspberry Pi Zero W.

#### Reproduction Steps

On a fresh Raspbian Lite on Raspberry Pi Zero W, run: 

`bash <(curl -sL https://www.screenly.io/install-ose.sh)`

#### Output

`       _____                           __         ____  _____ ______
      / ___/_____________  ___  ____  / /_  __   / __ \/ ___// ____/
      \__ \/ ___/ ___/ _ \/ _ \/ __ \/ / / / /  / / / /\__ \/ __/
     ___/ / /__/ /  /  __/  __/ / / / / /_/ /  / /_/ /___/ / /___
    /____/\___/_/   \___/\___/_/ /_/_/\__, /   \____//____/_____/
                                     /____/
Screenly OSE requires a dedicated Raspberry Pi / SD card.
You will not be able to use the regular desktop environment once installed.

Do you still want to continue? (y/N)
________________________________________

Which version/branch of Screenly OSE would you like to install:

 Press (1) for the Production branch, which is the latest stable.
 Press (2) for the Development/Master branch, which has the latest features and fixes, but things may break.

You selected: Production

Do you want Screenly OSE to manage your network? This is recommended for most users because this adds features to manage your network. (Y/n)

Would you like to perform a full system upgrade as well? (y/N)
+ REPOSITORY=https://github.com/screenly/screenly-ose.git
+ sudo mkdir -p /etc/ansible
+ sudo tee /etc/ansible/hosts
+ echo -e '[local]\nlocalhost ansible_connection=local'
+ '[' '!' -f /etc/locale.gen ']'
+ sudo sed -i s/apt.screenlyapp.com/archive.raspbian.org/g /etc/apt/sources.list
+ sudo apt update -y
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease           
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
+ sudo apt-get purge -y python-pyasn1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'python-pyasn1' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ sudo apt-get install -y --no-install-recommends git-core libffi-dev libssl-dev python-dev python-pip python-setuptools python-wheel whois
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate
E: Unable to locate package python-wheel
+ '[' y == y ']'
+ export MANAGE_NETWORK=true
+ MANAGE_NETWORK=true
+ sudo apt-get install -y network-manager
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  dns-root-data dnsmasq-base iptables libbluetooth3 libip6tc2
  libmbim-glib4 libmbim-proxy libmm-glib0 libndp0
  libnetfilter-conntrack3 libnfnetlink0 libnm0 libpcap0.8 libqmi-glib5
  libqmi-proxy libteamdctl0 modemmanager ppp
Suggested packages:
  firewalld libteam-utils
The following NEW packages will be installed:
  dns-root-data dnsmasq-base iptables libbluetooth3 libip6tc2
  libmbim-glib4 libmbim-proxy libmm-glib0 libndp0
  libnetfilter-conntrack3 libnfnetlink0 libnm0 libpcap0.8 libqmi-glib5
  libqmi-proxy libteamdctl0 modemmanager network-manager ppp
0 upgraded, 19 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,965 kB of archives.
After this operation, 28.7 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian bullseye/main armhf libbluetooth3 armhf 5.55-3.1+rpt1 [106 kB]
Get:2 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf dns-root-data all 2021011101 [5,524 B]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libnfnetlink0 armhf 1.0.1-3+b1 [12.4 kB]
Get:4 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libnetfilter-conntrack3 armhf 1.0.8-3 [32.5 kB]
Get:5 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf dnsmasq-base armhf 2.85-1 [416 kB]
Get:6 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libip6tc2 armhf 1.8.7-1 [33.0 kB]
Get:7 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf iptables armhf 1.8.7-1 [328 kB]
Get:8 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libmbim-glib4 armhf 1.24.6-0.1 [172 kB]
Get:9 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libmbim-proxy armhf 1.24.6-0.1 [89.4 kB]
Get:10 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libmm-glib0 armhf 1.14.12-0.2 [1,067 kB]
Get:11 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libndp0 armhf 1.6-1 [9,328 B]
Get:12 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libnm0 armhf 1.30.0-2 [369 kB]
Get:13 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libpcap0.8 armhf 1.10.0-2 [143 kB]
Get:14 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libqmi-glib5 armhf 1.26.10-0.1 [519 kB]
Get:15 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libqmi-proxy armhf 1.26.10-0.1 [10.3 kB]
Get:16 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf libteamdctl0 armhf 1.31-1 [10.4 kB]
Get:17 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf modemmanager armhf 1.14.12-0.2 [1,589 kB]
Get:18 http://mirror.umd.edu/raspbian/raspbian bullseye/main armhf network-manager armhf 1.30.0-2 [2,734 kB]
Get:19 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf ppp armhf 2.4.9-1+1 [321 kB]
Fetched 7,965 kB in 17s (461 kB/s)                                       
Selecting previously unselected package dns-root-data.
(Reading database ... 41546 files and directories currently installed.)
Preparing to unpack .../00-dns-root-data_2021011101_all.deb ...
Unpacking dns-root-data (2021011101) ...
Selecting previously unselected package libnfnetlink0:armhf.
Preparing to unpack .../01-libnfnetlink0_1.0.1-3+b1_armhf.deb ...
Unpacking libnfnetlink0:armhf (1.0.1-3+b1) ...
Selecting previously unselected package libnetfilter-conntrack3:armhf.
Preparing to unpack .../02-libnetfilter-conntrack3_1.0.8-3_armhf.deb ...
Unpacking libnetfilter-conntrack3:armhf (1.0.8-3) ...
Selecting previously unselected package dnsmasq-base.
Preparing to unpack .../03-dnsmasq-base_2.85-1_armhf.deb ...
Unpacking dnsmasq-base (2.85-1) ...
Selecting previously unselected package libip6tc2:armhf.
Preparing to unpack .../04-libip6tc2_1.8.7-1_armhf.deb ...
Unpacking libip6tc2:armhf (1.8.7-1) ...
Selecting previously unselected package iptables.
Preparing to unpack .../05-iptables_1.8.7-1_armhf.deb ...
Unpacking iptables (1.8.7-1) ...
Selecting previously unselected package libbluetooth3:armhf.
Preparing to unpack .../06-libbluetooth3_5.55-3.1+rpt1_armhf.deb ...
Unpacking libbluetooth3:armhf (5.55-3.1+rpt1) ...
Selecting previously unselected package libmbim-glib4:armhf.
Preparing to unpack .../07-libmbim-glib4_1.24.6-0.1_armhf.deb ...
Unpacking libmbim-glib4:armhf (1.24.6-0.1) ...
Selecting previously unselected package libmbim-proxy.
Preparing to unpack .../08-libmbim-proxy_1.24.6-0.1_armhf.deb ...
Unpacking libmbim-proxy (1.24.6-0.1) ...
Selecting previously unselected package libmm-glib0:armhf.
Preparing to unpack .../09-libmm-glib0_1.14.12-0.2_armhf.deb ...
Unpacking libmm-glib0:armhf (1.14.12-0.2) ...
Selecting previously unselected package libndp0:armhf.
Preparing to unpack .../10-libndp0_1.6-1_armhf.deb ...
Unpacking libndp0:armhf (1.6-1) ...
Selecting previously unselected package libnm0:armhf.
Preparing to unpack .../11-libnm0_1.30.0-2_armhf.deb ...
Unpacking libnm0:armhf (1.30.0-2) ...
Selecting previously unselected package libpcap0.8:armhf.
Preparing to unpack .../12-libpcap0.8_1.10.0-2_armhf.deb ...
Unpacking libpcap0.8:armhf (1.10.0-2) ...
Selecting previously unselected package libqmi-glib5:armhf.
Preparing to unpack .../13-libqmi-glib5_1.26.10-0.1_armhf.deb ...
Unpacking libqmi-glib5:armhf (1.26.10-0.1) ...
Selecting previously unselected package libqmi-proxy.
Preparing to unpack .../14-libqmi-proxy_1.26.10-0.1_armhf.deb ...
Unpacking libqmi-proxy (1.26.10-0.1) ...
Selecting previously unselected package libteamdctl0:armhf.
Preparing to unpack .../15-libteamdctl0_1.31-1_armhf.deb ...
Unpacking libteamdctl0:armhf (1.31-1) ...
Selecting previously unselected package modemmanager.
Preparing to unpack .../16-modemmanager_1.14.12-0.2_armhf.deb ...
Unpacking modemmanager (1.14.12-0.2) ...
Selecting previously unselected package network-manager.
Preparing to unpack .../17-network-manager_1.30.0-2_armhf.deb ...
Unpacking network-manager (1.30.0-2) ...
Selecting previously unselected package ppp.
Preparing to unpack .../18-ppp_2.4.9-1+1_armhf.deb ...
Unpacking ppp (2.4.9-1+1) ...
Setting up libip6tc2:armhf (1.8.7-1) ...
Setting up dns-root-data (2021011101) ...
Setting up libpcap0.8:armhf (1.10.0-2) ...
Setting up libteamdctl0:armhf (1.31-1) ...
Setting up libnm0:armhf (1.30.0-2) ...
Setting up ppp (2.4.9-1+1) ...
Setting up libmm-glib0:armhf (1.14.12-0.2) ...
Setting up libbluetooth3:armhf (5.55-3.1+rpt1) ...
Setting up libnfnetlink0:armhf (1.0.1-3+b1) ...
Setting up libndp0:armhf (1.6-1) ...
Setting up libmbim-glib4:armhf (1.24.6-0.1) ...
Setting up network-manager (1.30.0-2) ...
Created symlink /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service → /lib/systemd/system/NetworkManager-dispatcher.service.
Created symlink /etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service → /lib/systemd/system/NetworkManager-wait-online.service.
Created symlink /etc/systemd/system/multi-user.target.wants/NetworkManager.service → /lib/systemd/system/NetworkManager.service.
Setting up libmbim-proxy (1.24.6-0.1) ...
Setting up libnetfilter-conntrack3:armhf (1.0.8-3) ...
Setting up iptables (1.8.7-1) ...
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in auto mode
update-alternatives: using /usr/sbin/iptables-nft to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/ip6tables-nft to provide /usr/sbin/ip6tables (ip6tables) in auto mode
update-alternatives: using /usr/sbin/arptables-nft to provide /usr/sbin/arptables (arptables) in auto mode
update-alternatives: using /usr/sbin/ebtables-nft to provide /usr/sbin/ebtables (ebtables) in auto mode
Setting up libqmi-glib5:armhf (1.26.10-0.1) ...
Setting up dnsmasq-base (2.85-1) ...
Setting up libqmi-proxy (1.26.10-0.1) ...
Setting up modemmanager (1.14.12-0.2) ...
Created symlink /etc/systemd/system/dbus-org.freedesktop.ModemManager1.service → /lib/systemd/system/ModemManager.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ModemManager.service → /lib/systemd/system/ModemManager.service.
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for dbus (1.12.20-2) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u2) ...
+ '[' production = master ']'
+ ANSIBLE_VERSION=ansible==2.8.8
+ sudo pip install ansible==2.8.8
sudo: pip: command not found
+ sudo -u pi ansible localhost -m git -a 'repo=https://github.com/screenly/screenly-ose.git dest=/home/pi/screenly version=production force=no'
sudo: ansible: command not found
+ cd /home/pi/screenly/ansible
/dev/fd/63: line 174: cd: /home/pi/screenly/ansible: No such file or directory
+ sudo -E ansible-playbook site.yml
sudo: ansible-playbook: command not found
+ /home/pi/screenly/bin/upgrade_containers.sh
/dev/fd/63: line 179: /home/pi/screenly/bin/upgrade_containers.sh: No such file or directory
+ sudo apt-get autoclean
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
+ sudo apt-get clean
+ sudo docker system prune -f
sudo: docker: command not found
+ sudo apt autoremove -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ sudo apt-get install plymouth --reinstall -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libplymouth5
Suggested packages:
  desktop-base plymouth-themes
The following NEW packages will be installed:
  libplymouth5 plymouth
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 218 kB of archives.
After this operation, 858 kB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian bullseye/main armhf libplymouth5 armhf 0.9.5-3+rpt2 [93.7 kB]
Get:2 http://archive.raspberrypi.org/debian bullseye/main armhf plymouth armhf 0.9.5-3+rpt2 [125 kB]
Fetched 218 kB in 3s (73.1 kB/s)   
Selecting previously unselected package libplymouth5:armhf.
(Reading database ... 42250 files and directories currently installed.)
Preparing to unpack .../libplymouth5_0.9.5-3+rpt2_armhf.deb ...
Unpacking libplymouth5:armhf (0.9.5-3+rpt2) ...
Selecting previously unselected package plymouth.
Preparing to unpack .../plymouth_0.9.5-3+rpt2_armhf.deb ...
Unpacking plymouth (0.9.5-3+rpt2) ...
Setting up libplymouth5:armhf (0.9.5-3+rpt2) ...
Setting up plymouth (0.9.5-3+rpt2) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u2) ...
Processing triggers for initramfs-tools (0.140) ...
+ sudo find /usr/share/doc -depth -type f '!' -name copyright -delete
+ sudo find /usr/share/doc -empty -delete
+ sudo rm -rf /usr/share/man /usr/share/groff /usr/share/info/coreutils.info.gz /usr/share/info/dc.info.gz /usr/share/info/diffutils.info.gz /usr/share/info/dir /usr/share/info/dir.old /usr/share/info/ed.info.gz /usr/share/info/find.info-1.gz /usr/share/info/find.info-2.gz /usr/share/info/find.info.gz /usr/share/info/find-maint.info.gz /usr/share/info/gnupg-card-architecture.png /usr/share/info/gnupg.info-1.gz /usr/share/info/gnupg.info-2.gz /usr/share/info/gnupg.info.gz /usr/share/info/gnupg-module-overview.png /usr/share/info/grep.info.gz /usr/share/info/gzip.info.gz /usr/share/info/nano.info.gz /usr/share/info/rluserman.info.gz /usr/share/info/sed.info.gz /usr/share/info/wget.info.gz /usr/share/lintian /usr/share/linda /var/cache/man
+ sudo find /usr/share/locale -type f '!' -name en '!' -name 'de*' '!' -name 'es*' '!' -name 'ja*' '!' -name 'fr*' '!' -name 'zh*' -delete
+ sudo find /usr/share/locale -mindepth 1 -maxdepth 1 '!' -name 'en*' '!' -name 'de*' '!' -name 'es*' '!' -name 'ja*' '!' -name 'fr*' '!' -name 'zh*' '!' -name locale.alias -exec rm -r '{}' ';'
+ sudo chown -R pi:pi /home/pi
+ '[' '!' -f /etc/sudoers.d/010_pi-nopasswd ']'
+ check_defaultpw
+ '[' production = master ']'
+ '[' production = production ']'
+ '[' false = false ']'
+ set +x
/dev/fd/63: line 240: mkpasswd: command not found
The default raspberry pi password was not detected, continuing with installation...
++ git rev-parse --abbrev-ref HEAD
/dev/fd/63: line 259: git: command not found
++ git rev-parse --short HEAD
/dev/fd/63: line 259: git: command not found
++ lsb_release -a
No LSB modules are available.
+ echo -e 'Screenly version: @\nDistributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye'
+ '[' false = false ']'
+ set +x
Installation completed.
You need to reboot the system for the installation to complete. Would you like to reboot now? (y/N)
`
#### Environment

* Raspberry Pi Hardware Version: Zero W
* Raspberry Pi Network Setup: USB Ethernet Adapter
* Screenly OSE Version: Current production version as of 2/6/22

**Comment by extremeskillz** [comment]
Same boat there. Trying to install on Bullseye on a fresh RPI3b+ Build. 

I see there a builds for buster but we need Bullseye too. Thanks!

**Comment by NassimBentarka** [comment]
> Same boat there. Trying to install on Bullseye on a fresh RPI3b+ Build.
> 
> I see there a builds for buster but we need Bullseye too. Thanks!

Thanks for mentioning that Bullseye is not yet supported. Just saved me tons of frustration, I just downgraded to Buster!

**Comment by extremeskillz** [comment]
Yea, so as a public service announcement to all, anyone currently planning to install Screenly by the script please make sure your base PI install is Buster not Bullseye as of this date. Hopefully they have an update and updated script that supports Bullseye coming out soon as I would like to move to Bullseye to keep my PI systems current.

When the update is release that supports Bullseye this issue can be closed.

**Comment by shaqaruden** [comment]
Python 2 is still required for Screenly.

**Comment by semaf** [comment]
The installation script is not anyway compatible to Raspberry Pi 4 and Bullseye. Python2 still used, Docker and all requirements not installed correctly. Even a manually installation is not working very well.

**Comment by vpetersson** [comment]
Closing this out as it has now been resolved.
