### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by shaqaruden** [Screenly/screenly-ose#1570]
@vpetersson  what is the status of this project?

**Comment by BirgirBjornsson** [comment]
Used Screenly for two years now and was happy, but now it is issues with installation on pi4b, catching problems viewing images in website in the browser, it this project to go forward with?

**Comment by vpetersson** [comment]
Long story short -- we were in the process to hire someone to work full time on this but then COVID hit and we had to focus all our resources on the commercial version. 

We are right now in the process of resuming the hiring for this role and hope to have someone in a not too distant future picking things up.
