### ISSUE TITLE
Doubts about manual installation and raspberry PI 4

### ISSUE THREAD

**Issue by fbsanches** [Screenly/screenly-ose#1582]
1) In the Screenly OSE manual installation script, what is the difference, when it asks if the installation will be complete or partial?

"Would you like to perform a full system upgrade as well?"

2) Which version is already compatible with the raspberry pi 4 model B and model B+?

Thanks

**Comment by vpetersson** [comment]
> In the Screenly OSE manual installation script, what is the difference, when it asks if the installation will be complete or partial? "Would you like to perform a full system upgrade as well?"

This question refers to the system update. Not to the Screenly installation. It is recommended that you do upgrade this too.

> Which version is already compatible with the raspberry pi 4 model B and model B+?

The old "production" version has been removed, so there is currently only one version that you can install. It should be compatible with all pi4 boards.
