### ISSUE TITLE
Need help installing Screenplay on Pi4

### ISSUE THREAD

**Issue by Struxur** [Screenly/screenly-ose#1595]
#### When I try to install screenly on Pi4, on reboot it still goes back to Raspian Desktop.

When I install from command prompt in the terminal, the reboot kicks it back to Raspian desktop. i have tried Raspian Lite 32, Lite 64, pretty much all the OS software and still getting the same result. 

All in all Screenly will not boot up on the Pi4

#### Environment

* Raspberry Pi Hardware Version: Raspberry Pi4 4gb
* Raspberry Pi Network Setup: (ex. built-in WiFi, Ethernet, USB WiFi Adapter)
* Screenly OSE Version: 2020-4-4

**Comment by vpetersson** [comment]
The installation should have been fixed now, but you can't use *Raspbian Desktop*, that will break it. Also, only the `experimental` branch works at the moment.
