### ISSUE TITLE
No new releases?

### ISSUE THREAD

**Issue by madsrh** [Screenly/screenly-ose#1608]
Sorry, not really an issue, but why are there no recent disk image releases?

https://github.com/Screenly/screenly-ose/releases

Latest release is from 2020 yet there has been many many commits since 🤷‍♂️

**Comment by ForceConstant** [comment]
Was wondering the same thing, the production branch which is what the releases are based on, hasn't had a commit since 2020.

**Comment by vpetersson** [comment]
There's no release yet. The work has begun to create a new release, but we're overhauling how we do releases to make upgrades easier.

**Comment by madsrh** [comment]
Thank you for the reply @vpetersson
