### ISSUE TITLE
Missing Partition Table

### ISSUE THREAD

**Issue by mikekorncnx** [Screenly/screenly-ose#1620]
The latest image for Screenly OSE for a pi 4 is not a linux image.

When trying to flash the image, this is the error produced in belenaEtcher:

_Missing Partition Table

It looks like this is not a bootable image. The image does not appear to contain a partition table, and might not be recognized or bootable by your device._

The file provided is not a linux image. Any help would be greatly appreciated.

**Comment by vpetersson** [comment]
Duplicate. See https://github.com/Screenly/screenly-ose/issues/1619#issuecomment-1266422518
