### ISSUE TITLE
Fix failing tests in `tests/celery_tasks_test.py`.

### ISSUE THREAD

**Issue by nicomiguelino** [Screenly/screenly-ose#1623]
##### General

- [x] Make unit tests idempotent.

##### Fix the following test cases

- [x] `test_cleanup` (`celery_tasks_test.TestCleanup`)
- `test_result` (`celery_tasks_test.TestUpgradeScreenly`) &ndash; won't fix, `upgrade_screenly` task is not defined
- `test_state` (`celery_tasks_test.TestUpgradeScreenly`) &ndash; won't fix, `upgrade_screenly` task is not defined
- [x] `test_append_usb_assets` (`celery_tasks_test.TestUsbAssets`)
- [x] `test_cleanup_usb_assets` (`celery_tasks_test.TestUsbAssets`)
- [x] `test_remove_usb_assets` (`celery_tasks_test.TestUsbAssets`)

#### Overview of the Issue

```
test_cleanup (celery_tasks_test.TestCleanup) ... ERROR
test_result (celery_tasks_test.TestUpgradeScreenly) ... ERROR
test_state (celery_tasks_test.TestUpgradeScreenly) ... ERROR
test_append_usb_assets (celery_tasks_test.TestUsbAssets) ... /usr/src/app/server.py:139: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  usb_file_settings = yaml.load(yaml_file).get('screenly')
ERROR
test_cleanup_usb_assets (celery_tasks_test.TestUsbAssets) ... ERROR
test_remove_usb_assets (celery_tasks_test.TestUsbAssets) ... ERROR

...

Ran 6 tests in 0.231s

FAILED (errors=6)
```

##### First Time Setup

```bash
docker-compose -f docker-compose.dev.yml build
docker-compose -f docker-compose.dev.yml up -d
docker-compose -f docker-compose.dev.yml exec srly-ose-test bash bin/prepare_test_environment.sh -s
```

##### Running the Tests

```bash
docker-compose -f docker-compose.dev.yml exec srly-ose-test nosetests -v -a 'fixme' tests/celery_tasks_test.py
```

#### Environment

- WSL 2 (Ubuntu 22.04, x86, 64-bit)
- Docker Desktop for Windows (accessible via WSL 2)

#### Logs

- [issue_1623.log](https://github.com/Screenly/screenly-ose/files/9716459/issue_1623.log)

**Comment by nicomiguelino** [comment]
@vpetersson & @rusko124, can `test_result` and `test_update` (from `tests/celery_tasks_test.py`) be removed? These test cases depend on a Celery task that doesn't exist anymore in `server.py`.

**Comment by vpetersson** [comment]
Yeah if the celery tasks are removed, then remove the corresponding test. I don't recall removing any Celery tasks tho.
