### ISSUE TITLE
Broken import "from sh import mplayer" prevents viewer container from starting

### ISSUE THREAD

**Issue by tmeiczin** [Screenly/screenly-ose#1636]
#### Overview of the Issue
The viewer container does not start due to a bad import, which is causing:

`Traceback (most recent call last):
  File "viewer.py", line 21, in <module>
    from lib.diagnostics import get_raspberry_code, get_raspberry_model
  File "/usr/src/app/lib/diagnostics.py", line 6, in <module>
    import utils
  File "/usr/src/app/lib/utils.py", line 20, in <module>
    from sh import mplayer
ImportError: cannot import name mplayer`

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Update a viewer container after Oct 17 or perform an install.
* The view container will be in an restart loop causing a black screen

#### Environment

* Raspberry Pi Hardware Version:
* Raspberry Pi Network Setup: (ex. built-in WiFi, Ethernet, USB WiFi Adapter)
* Screenly OSE Version:

**Comment by nicomiguelino** [comment]
Got it, @vpetersson and @tmeiczin. Thanks!
