### ISSUE TITLE
MP3 files won't upload

### ISSUE THREAD

**Issue by 00ihsan** [Screenly/screenly-ose#1639]
When I try to upload a mp3 as an asset, I get a server error: file not supported. 

Please help.

**Comment by vpetersson** [comment]
This is not supported, and is unlikely to be supported. MP3 is just for audio. Audio is not a supported media type.

**Comment by 00ihsan** [comment]
First of all, thanks for the fast reply!Oh, I saw https://www.screenly.io/blog/2022/09/14/digital-signage-audio-management/ this article. Op 21 okt. 2022 om 10:49 heeft Viktor Petersson ***@***.***> het volgende geschreven:﻿
Closed #1639 as completed.

**Comment by vpetersson** [comment]
Right. That's for a completely different product. Audio is supported in the commercial version of Screenly.

**Comment by 00ihsan** [comment]
Hmmmm. Won't be supported in the OSE anytime soon?

**Comment by vpetersson** [comment]
Unlikely unless anyone writes and contributes the code for it.
