### ISSUE TITLE
Terminal access

### ISSUE THREAD

**Issue by Tharrington86** [Screenly/screenly-ose#1660]
#### Overview of the Issue
With the latest release for RPi4 is there a way to step out of Screenly OSE to the terminal? I have read users having success on older versions by using Ctrl+Alt+F1 but that does not seem to function for my instance. I am trying to configure a static IP for my device but am unable since I cannot reach the terminal.

#### Environment

* Raspberry Pi Hardware Version: RPi 4B
* Raspberry Pi Network Setup:  Ethernet
* Screenly OSE Version: master@f6311f9

**Comment by vpetersson** [comment]
That's expected. You can't use TTY1 as that is occupied by the player. Try Ctrl+Alt+F2.

**Comment by Tharrington86** [comment]
I tried F2 and got a black screen only. F1 resulted in my asset reappearing.

**Comment by institut-agro-ead** [comment]
Hello,
Same problem here with Anthias (pi3) freshly installed on RPI3B via Raspberry Pi Imager.

**Comment by vpetersson** [comment]
That's not a bug. It's expected. If you need terminal access, you need to use the manual installation on raspbian.

**Comment by vpetersson** [comment]
Strange. Please do that installer again and see if any errors show up in the logs. We've tested it and it should work just fine.
