### ISSUE TITLE
Add option to backup

### ISSUE THREAD

**Issue by pifiu** [Screenly/screenly-ose#352]
I run the raspberry pi 24/7 behind a TV using Screenly OSE and ocassionally when there is a power surge, the file system seems to get corrupt and its very time consuming to reinstall, and upload all of the content again.

Is there a way to generate a backup of the config with optionally the content as well? That way if someone just wants to save the configuration (which there is really little to nothing to configure) by itself they can do that, or if they want the configuration + the content they can as well.

It seems like it would make reloading things easier in the case the file system gets corrupt.

**Comment by vpetersson** [comment]
It's an interesting idea. However, for the time being, my recommendation would be to simply backup the SD card directly. If you're on Linux or OS X, you can do that easily using `dd` for instance.

**Comment by vpetersson** [comment]
Maybe we should add this functionality. All we really need to do is to create an archive of: 
* `~/.screenly`
* `~/screenly_assets`

There could however be issues with creating these if there are lots of large assets on disk, so we probably need to have this performed async by some background daemon.

**Comment by krzimmer** [comment]
If I wanted to move all assets from one screenly pi to another, all I would need to do is copy
~/.screenly
~/screenly_assets
to the other device?

**Comment by vpetersson** [comment]
Yup. That should be sufficient, assuming Screenly is properly installed.

**Comment by krzimmer** [comment]
I tried doing this.  After the transfer, Screenly will not launch on the target device.  I used the Screenly Image and verified that the target device was working properly prior to the transfer.  Any suggestions?

**Comment by vpetersson** [comment]
Hard to say without any logs.

**Comment by pifiu** [comment]
so is the /screen_assets/ the only thing needed or is ~/.screenly also required for a backup?

**Comment by vpetersson** [comment]
You need to backup `~/.screenly` as well, as that is where the database and config resides.

**Comment by vpetersson** [comment]
@over64 hold off with this one a bit as we need to think of a good way to store this data such that we can later restore it easily. Right now I'm thinking BSON would be a good format for this.

**Comment by vpetersson** [comment]
Closed in #563.
