### ISSUE TITLE
Settings -> "Use 24-hour clock" not working

### ISSUE THREAD

**Issue by dannykorpan** [Screenly/screenly-ose#438]
Hi,
if i go to the settings and turn the option "Use 24-hour clock" on, then after save the option goes back to off.

**Comment by vpetersson** [comment]
Are you able to reproduce this on the latest branch? (i.e. run the installer and answer Yes to `Would you like to use the development branch? You will get the latest features, but things may break. (y/N)`)

**Comment by vpetersson** [comment]
Closing this out due to lack of response.
