### ISSUE TITLE
Set Start/End Date not correct

### ISSUE THREAD

**Issue by dannykorpan** [Screenly/screenly-ose#439]
Hi,
if I'm set the start/end date of an asset and click save then to the start/end date are automatically removed 2 hours.

**Comment by vpetersson** [comment]
Please try install the latest version (i.e. run the installer and answer `y` to `Would you like to use the development branch? You will get the latest features, but things may break. (y/N)`) and see if you're still able to reproduce this issue.

**Comment by vpetersson** [comment]
Closing this out due to lack of response.
