### ISSUE TITLE
InsecureRequestWarning when displaying SSL secured sites over HTTPS

### ISSUE THREAD

**Issue by nilsbyte** [Screenly/screenly-ose#529]
SSL secured sites are displayed but the log says

`
screenly python[741]: /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
`

I followed the steps at https://urllib3.readthedocs.org/en/latest/security.html but I think you have to change something in the python scripts of Screenly.

**Comment by vpetersson** [comment]
Yeah this is a known issue. Doesn't really cause any issues tho.

**Comment by leonelwilliams** [comment]
One option could be to verify things by default but add a per-asset checkbox to insecurely disable certificate verification if required. (One that I'd keep unchecked but I understand that not everyone has the luxury unfortunately.)

**Comment by leonelwilliams** [comment]
I don't have use for screenly anymore at the moment, unfortunately, but loading resources with no certificate verification isn't really the best practise as there's no guarantee the request or response wasn't viewed or modified.

**Comment by vpetersson** [comment]
@leonelwilliams Agreed. This was partially due to the fact that we had to support older versions of Raspbian. We are now moving to docker, which should help us keep things more up to date.
