### ISSUE TITLE
White Line appearing on Webpage Assets

### ISSUE THREAD

**Issue by madcackler** [Screenly/screenly-ose#537]
With the current release of screenly, when I display a webpage there is a white line that appears at the bottom of the screen, no matter what the webpage source.  If I display an image this white line does not appear.

![white-line](https://cloud.githubusercontent.com/assets/19191016/21995918/2bd2803e-dbed-11e6-9c79-ad471bfe14e5.jpg)

**Comment by vpetersson** [comment]
My best guess is that this is an overscan issue. Try modifying `overscan_bottom` in `config.txt` to see if that solves the issue.

**Comment by madcackler** [comment]
Currently I have overscan disabled.  The key thing is though, this only occurs when I display any webpages, and not just my own; if I display an image, it goes to edge no problem, so I suspect it has something to do with the built in browser's rendering.  My previous builds with screenly have not had this issue.

**Comment by vpetersson** [comment]
@madcackler Are you able to reproduce this on *every* web page? Because images are using the browser as well.

**Comment by madcackler** [comment]
Outside of pages that have a white background (in which it blends in), it appears visible on every page I've tried.
