### ISSUE TITLE
wordpress digital signage

### ISSUE THREAD

**Issue by baelinc** [Screenly/screenly-ose#548]
I have a digital signage system running on wordpress. One of my screens basically shows what events are happening in what room, and that changes every day,

Screenly doesnt seem to be refreshing the page completely at the selected intervals as I come in the next day and the following day's events are still posted. I can pull on the page on my computer and the correct information is displayed.

I have also trying adding useless information to the end of the address ?_page=1 or something similar and added a second screen that show the exact same web page, but with a different ending (ie ?_page=2). But it seems as though that hasnt forced the page to update.

Is there a way to force the page to re cache everyday, or make it force to make the change without rebooting the raspberry pi?

**Comment by vpetersson** [comment]
I would recommend that you check out our new plugin called [Screenly Cast for WordPress](https://github.com/Screenly/Screenly-Cast-for-WordPress). 

In terms of refresh however, you should be able to control that with the duration of the asset. Alternatively, you can insert a different image in between to make sure the cache is cleared (which it should be anyways).
