### ISSUE TITLE
webpage not accessible after update

### ISSUE THREAD

**Issue by thhartung** [Screenly/screenly-ose#575]
Last week I updated two of our screenly clients.
I was able to access the webinterfaces and upload content like before.
Today after a rebbot both clients webinterfaces are not responding anymore, ssh login is still possible.
Quick port scan showed no open ports except the ssh port anymore

**Comment by vpetersson** [comment]
Try upgrading to the development version and let us know if that resolves the issue.

**Comment by thhartung** [comment]
switched to the development branch, same problem

**Comment by vpetersson** [comment]
What do you get from `journalctl --since "24 hours ago"`

**Comment by thhartung** [comment]
Stange enough mothing, doenst semm to be installed
I started the installation once again, here is she output, there seem to be some failures


[Neues Textdokument.txt](https://github.com/Screenly/screenly-ose/files/1080460/Neues.Textdokument.txt)

**Comment by vpetersson** [comment]
Hmm odd. Well, you're on Wheezy. You probably want to upgrade to Jessie anyways, as Wheezy is getting very old by now. I suggest you fetch the latest disk image and use that instead.
