### ISSUE TITLE
Add result of display status to system page

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#585]
As discussed in #108, it's possible to toggle the display power using `vcgencmd`. We should add this status to the settings page.

We can get the display power by running:
```
pi@raspberrypi:~ $ vcgencmd  display_power
display_power=1
```

Let's `1` means that the display power is on, and `0` that it is off.  Let's just add a simple text that says "Display Power: True|False"

**Comment by daniep01** [comment]
@vpetersson I'm working on this in branch display_power
