### ISSUE TITLE
Duration field should be disabled for videos

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#590]
I noticed today when building 0.10 that we have a bug in the asset upload. 

For videos, the duration field should be read-only. It's not:

![image](https://user-images.githubusercontent.com/357664/27826170-0764ecd6-60aa-11e7-9088-9471639ae21e.png)

**Comment by antonmolodykh** [comment]
By the way, I checked version 0.9.1. The duration field for a video is still open.
