### ISSUE TITLE
InsecureRequestWarning

### ISSUE THREAD

**Issue by JacoFourie1** [Screenly/screenly-ose#595]
Hi. When I try to load a site to show a dashboard I get this error

`Jul 24 11:40:09 raspberrypi python[819]: /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
Jul 24 11:40:09 raspberrypi python[819]: InsecureRequestWarning)
Jul 24 11:40:09 raspberrypi python[819]: /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
Jul 24 11:40:09 raspberrypi python[819]: InsecureRequestWarning)
Jul 24 11:40:09 raspberrypi python[819]: Traceback (most recent call last):
Jul 24 11:40:09 raspberrypi python[819]: File "/home/pi/screenly/server.py", line 194, in api_view
Jul 24 11:40:09 raspberrypi python[819]: return make_json_response(view(*args, **kwargs))
Jul 24 11:40:09 raspberrypi python[819]: File "/home/pi/screenly/server.py", line 230, in add_asset
Jul 24 11:40:09 raspberrypi python[819]: raise Exception("Could not retrieve file. Check the asset URL.")
Jul 24 11:40:09 raspberrypi python[819]: Exception: Could not retrieve file. Check the asset URL.
`
It seems it does not like the certificate. I did have a look at the documentation at https://urllib3.readthedocs.org/en/latest/security.html but I am not sure where to add the line of code to switch off the warning.

**Comment by JacoFourie1** [comment]
I am using the pre build image that I downloaded from the site. It is Jessie.

**Comment by vpetersson** [comment]
Can you provide a sample URL where you get this error?

**Comment by vpetersson** [comment]
Closing out due to lack of response.

**Comment by ealmonte32** [comment]
@JacoFourie1 
To stop getting the warning make the change on the `/home/pi/screenly/lib/utils.py` file like this:

![image](https://user-images.githubusercontent.com/24350198/55360848-89cfa500-54a3-11e9-9866-cd769afc5b30.png)
