### ISSUE TITLE
Set GPU memory in NOOBS installer

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#606]
As discussed [here](https://github.com/Screenly/screenly-ose/issues/542#issuecomment-317891026), it is possible to reach an issue when using the NOOBS installer because of lack of GPU memory. 

We need to investigate if there's a way to set this issue in NOOBS.

**Comment by antonmolodykh** [comment]
We need to update `config.txt`, add the `gpu_mem` parameter
