### ISSUE TITLE
Write release notes

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#618]
We need to write release notes for this release. See [the previous release](https://github.com/Screenly/screenly-ose/releases/tag/v0.10) for inspiration.

**Comment by antonmolodykh** [comment]
For detailed changes, see [Sprint 3 milestone](https://github.com/Screenly/screenly-ose/milestone/5).
QA Performed by @antonmolodykh.

## New features

- Adds streaming support for YouTube (#586)
- Adds versioning of API (#587)

## Bugfixes / improvements

- Improves NOOBS image (#578)
- Improves network status detection (#579)
- Adds result of display status to system page (#585)
- Removes unused assets (#581)
- Disabled for duration field of videos (#590)
