### ISSUE TITLE
Screenly Keyboard not working with web interface

### ISSUE THREAD

**Issue by jpburnett** [Screenly/screenly-ose#619]
Running Screenly there are some pages that I need to authenticate for. Doing some googling I found https://stackoverflow.com/questions/38052032/screenly-ose-browser-keyboard-input-disabled
I upgraded to the most recent version, but after rebooting screenly won't even start.

**Comment by vpetersson** [comment]
@jpburnett What error(s) are you getting?

**Comment by vpetersson** [comment]
Closing out ticket due to lack of response.
