### ISSUE TITLE
Add option for default asset display length

### ISSUE THREAD

**Issue by alexstojda** [Screenly/screenly-ose#632]
I would like to suggest a feature which would set a default asset display length. 

For example, I'd like the default display time for an asset to be set at 7 days, so that every time I add an Asset, it will appear for 7 days.

**Comment by vpetersson** [comment]
We're happy to accept a pull request for this, as it seems to make sense.

**Comment by daniep01** [comment]
I have added this to my system and it seems to be working, what should the new option be called? I'm using 'period' but that might not be best. We need something that won't be confused with the existing 'duration' setting.
@skiracerdude @vpetersson

**Comment by skiracerdude** [comment]
How about 'Default Asset Campaign Length' ? I know its kinda long, but it's decently clear. I think it would also help if we add the units being used after the input fields.
Eg. 'Default Duration <input field> (seconds)' 

I think specifying units will also help with the confusion between the two. @danielp01

**Comment by vpetersson** [comment]
I agree with @skiracerdude - 'Default duration' makes sense. Having 'Seconds' would be nice too but it would make it too long. Perhaps we could add a `glyphicon glyphicon-question-sign` and then an explainer text that it's in seconds when hovering over it?

**Comment by daniep01** [comment]
- 'Default duration (seconds)'
- 'Default streaming duration (seconds)'
- 'Default schedule period (days)'
maybe? To me campaign is too advertising specific, not all users will understand this.

**Comment by vpetersson** [comment]
@daniep01 Did you break them out for different asset types? If not I would go with the 'Default duration' and then a helper.

**Comment by daniep01** [comment]
think the request is for the default time period (in days) between the start date and end date to be configurable. This isn't the same as the default time that the asset is displayed (in seconds). 
The split between streaming asset and uploaded asset already exists.

**Comment by vpetersson** [comment]
Oh, yeah you're right. My bad.

In that case, I think we need a proper, like [this](https://github.com/koss-lebedev/bootstrap-duration-picker) for it to work well.

**Comment by skiracerdude** [comment]
@vpetersson Yeah that could work! but maybe just with the days and hours precsions, I don't think its necessary to have minutes and seconds too.

**Comment by vpetersson** [comment]
Agreed.  Hours and days feels sufficient.

**Comment by daniep01** [comment]
I could create a PR now which allows you to configure the period in days using a numeric text box. Adding hours will take me a bit longer.

**Comment by vpetersson** [comment]
Hi @daniep01 - let's hold it until we have the full thing, but feel free to create a PR and then we you can update it when you have that part ready.

**Comment by ptrlv** [comment]
Hi, please consider adding a tickbox option for an indefinite period. ie. unscheduled.

**Comment by vpetersson** [comment]
@ptrlv that doesn't work with this model, but if you only have one asset, that would in reality be more or less the same.

**Comment by netjordanlee** [comment]
Please add an "Always Active" option. This has been a major sticking point for me, there has been a number of times when the end date hasn't been set properly and suddenly our screens are just showing a blank interface...

**Comment by alexstojda** [comment]
@netjordanlee please open a new issue/feature request. Don't hijack an existing one :)
