### ISSUE TITLE
Url screenly xast from my localhost of wordpress

### ISSUE THREAD

**Issue by biniin** [Screenly/screenly-ose#634]
I can't run the utl asset on my raspberry pi, it keep saying url error i am using xampp and the plugins fir screenly cast
Thanks for you help

**Comment by vpetersson** [comment]
I'm not sure I understand the issue. Please create a ticket [here](https://github.com/Screenly/Screenly-Cast-for-WordPress/issues/) with complete details on how it's setup and what isn't working.
