### ISSUE TITLE
Update available notification broken?

### ISSUE THREAD

**Issue by daniep01** [Screenly/screenly-ose#655]
I just built a new Screely using the command line installer, including dev code, and I'm seeing the 'update available' button on the system info page. I think it should it check to see if there really is an update using `{% if not context.up_to_date %}`?

Fix proposed: #656

**Comment by enieuwenhuis** [comment]
Same problem here.

**Comment by vpetersson** [comment]
I can confirm this issue.

**Comment by daniep01** [comment]
@vpetersson, fixed in #656, issue can be closed

**Comment by vpetersson** [comment]
Yup. Forgot to close this one.
