### ISSUE TITLE
Round uptime on info page

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#658]
Right now, the uptime is presented like this:
```
0 days and 10.6736111111 hours
```

Let's just round that to two decimal points.

**Comment by daniep01** [comment]
There is a round function in Jinja, this should work
`<td>{{context.uptime.days}} days and {{ (context.uptime.seconds/3600)|round(2) }} hours</td>`

**Comment by daniep01** [comment]
Change in pr #661
