### ISSUE TITLE
Things become stuck at "INACTIVE ASSETS".

### ISSUE THREAD

**Issue by zsamenfeld-encon** [Screenly/screenly-ose#667]
That's right, I can click the wonderful on and off button all I'd like but it doesn't seem to do anything. ever.
I'm not totally sure what caused this because earlier today the screen still had assets showing. Now it's just the screenly logo faintly in the background. A restart of the pi seems to fix this.

![image](https://user-images.githubusercontent.com/31540804/32195370-7dd75d54-bd93-11e7-9a57-78d861d1c686.png)

**Comment by vpetersson** [comment]
My gut feeling is that there is some issue with the clock. Is this device offline?

**Comment by zsamenfeld-encon** [comment]
Time reads, Tue Aug 8 16:00:15 BST 2017. Clearly wrong.. I wonder how that's happened.

**Comment by vpetersson** [comment]
The Raspberry Pi does not have a built-in real time clock (RTC). Hence, if it is offline and unable to communicate with an NTP server, it will not know what time it is. See [this FAQ entry](https://support.screenly.io/hc/en-us/articles/115002570873-Can-I-use-Screenly-OSE-in-offline-mode-) for more details.

**Comment by zsamenfeld-encon** [comment]
Alright, I've installed a RTC on the raspberry pi, configured it.. etc. Still having inactive asset issue randomly.

**Comment by vpetersson** [comment]
Did you verify that the time was properly set? It's likely you need to do this by hand (or via NTP) the first time.

**Comment by zsamenfeld-encon** [comment]
Yes, I've made sure the time is set properly.

**Comment by vpetersson** [comment]
The next thing then is to look at the logs. Can you post the output of the following commands:

 * `sudo journalctl`
 * `date`
 * `dmesg`

**Comment by zsamenfeld-encon** [comment]
https://gist.github.com/zsamenfeld-encon/a29e3b3252aec9be337fb97c47f68e0a

**Comment by vpetersson** [comment]
Nothing obvious in the logs unfortunately. When was the last time you upgraded?

Also ping @antonmolodykh.

**Comment by zsamenfeld-encon** [comment]
At the time of uploading the logs I wasn't having any issues, I'll report back with logs again when it happens again.
Also we upgrade every Sunday night. So the last update was only a few days ago.
