### ISSUE TITLE
Minor visual glitch on enable/disable toggle

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#676]
Looks like something is wrong with the button in this screenshot.
![screen shot 2017-11-13 at 4 52 47 pm](https://user-images.githubusercontent.com/357664/32737884-3465c4ca-c893-11e7-8edd-758c36fd8b22.png)

**Comment by antonmolodykh** [comment]
I tried to reproduce this in chrome and in firefox, and also tried to understand the possible reasons, but so far unsuccessfully. is there any additional information? in which browser was it seen?

**Comment by vpetersson** [comment]
Strange. I got it in Chrome i believe. Closing out until we can reproduce then.
