### ISSUE TITLE
Install on a Orange PI

### ISSUE THREAD

**Issue by Kynoq** [Screenly/screenly-ose#677]
Is it possible to install Screenly OSE on Orange PI PC+ ?

I tried different method but anyone works.

Thank you !

**Comment by vpetersson** [comment]
In theory, probably, but it will likely require some code changes. We don't have any Orange Pi here so we can't try it, but we'd be happy to accept a (conditional) pull request with fixes if you  want to port it.

**Comment by vpetersson** [comment]
Closing out issue as we have no Orange Pi to test with.
