### ISSUE TITLE
Remove Screenly Network Manager

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#691]
It seems like there has been a fair amount of issues with Screenly Network Manager on Screenly OSE. Let's disable this in favor of #686.

**Comment by vpetersson** [comment]
@antonmolodykh Can you provide instructions for how to disable Screenly Network Manager (the `systemctl` commands) for future references?

**Comment by antonmolodykh** [comment]
To just turn off the service, just enter `systemctl disable screenly-net-manager.service` command

**Comment by antonmolodykh** [comment]
I think that we can not completely abandon this, because as @majorz [said](https://github.com/Screenly/screenly-ose/issues/686#issuecomment-346333810), resin-wifi-connect is now being run on Stretch. so we need to leave support for Jessie.

**Comment by vpetersson** [comment]
@antonmolodykh - I think that's fine. We will just revert to the default method in Raspbian for earlier releases.

**Comment by vpetersson** [comment]
Solved in #715.
