### ISSUE TITLE
API docs are broken when enabling HTTP proxy

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#694]
When enabling HTTP proxy, as with Resin, the local API is broken as it cannot load the content on port 8080.

**Comment by antonmolodykh** [comment]
I checked, it seems this problem is already solved in https://github.com/Screenly/screenly-ose/pull/698

**Comment by vpetersson** [comment]
No, this doesn't work still.

Here's how to reproduce it:

 * Deploy a device on Resin
 * Enable public URL
 * Navigate to the web interface (which works)
 * Go to the API docs (/api/docs) 

Here's an example:
http://d1d0f3806510f478fe4790a02aef8652.resindevice.io/api/docs/
