### ISSUE TITLE
iframe not displaying https content

### ISSUE THREAD

**Issue by qbicdesign** [Screenly/screenly-ose#706]
I followed this guide as a basis to display google spreadsheet content in Screenly.
https://www.screenly.io/use-cases/dashboard/google-calendar/

It works fine on Screenly Pro, but in Screenly OSE the iframe is empty.

Not sure if this an https or iframe issue. Doing some further tests.

Any clues?

**Comment by vpetersson** [comment]
Interesting. Should be the same. What version hardware version of the Raspberry Pi are you using? Also, what version of Screenly OSE?

**Comment by qbicdesign** [comment]
Seems like its a false alarm - closing this thread.
I was using an old version of the page, which had some incorrect code in it :\
Error between chair and computer.
