### ISSUE TITLE
Accept HTTP request from other origin

### ISSUE THREAD

**Issue by muex** [Screenly/screenly-ose#709]
I wanted to write a client in react and connect to my pi via api. But because of CORS it is not allowed. In my research I found that SimpleHTTPServer has no options to support access controls. Any plans to change that server or any ideas for connecting a js client via api?

**Comment by vpetersson** [comment]
We are actually using Flask, which does support CORS. It's rather trivial to add using [Flask-CORS](http://flask-cors.readthedocs.io/en/latest/).

**Comment by vpetersson** [comment]
@muex we can add this to the next sprint. Alternatively, we're happy to accept a PR.

**Comment by muex** [comment]
@vpetersson I closed this issue, because I had an older version on my pi. After your info I updated and I can now work on my ajax frontend. Thank you for this info.
