### ISSUE TITLE
HTTP basic authentication: not possible with credetials

### ISSUE THREAD

**Issue by lazyzero** [Screenly/screenly-ose#720]
Hi,

I use the screenly-ose raspberry pi image with the git branch production. I tried to setup the HTTP basic authentication like described in the Wiki, but I am not able to login afterwards. I tried with removing all whitespace on the password and user name line.

**Comment by vpetersson** [comment]
Did you restart the service after?

**Comment by lazyzero** [comment]
I did it like in the Configuration section of your Wiki 
https://github.com/Screenly/screenly-ose/blob/master/docs/http-basic-authentication.md
after pkill I had to enter the credentials but it failed to authenticate

**Comment by vpetersson** [comment]
@antonmolodykh could you try reproducing this?

**Comment by antonmolodykh** [comment]
@vpetersson I performed the steps from wiki. It work for me

@lazyzero could you show me the output of `cat /home/pi/.screenly/screenly.conf`?

**Comment by lazyzero** [comment]
I could correct the config file by again adding the lines from the wiki with cat.
The default lines that where in the file didn't work for me.

**Comment by vpetersson** [comment]
@lazyzero could you post an example of a snippet that works and one that doesn't work?
