### ISSUE TITLE
Unable to interact with the webpage using the keyboard

### ISSUE THREAD

**Issue by domlwilliams** [Screenly/screenly-ose#721]
I'm unable to interact with the webpage when using the keyboard. I can see the mouse working and know the keyboard is working as it works when the dev tools is open.
I'm trying to view a site which is behind a login and can only think of manually logging in each time the pi is started.

**Comment by vpetersson** [comment]
Not sure about this one. The keyboard should work. @antonmolodykh any ideas here?

**Comment by antonmolodykh** [comment]
I don't know what's the matter, but I confirm that the keyboard does not work

**Comment by vpetersson** [comment]
I want to make this an option that is disabled by default.

**Comment by putneyj** [comment]
I am also seeing this issue. Is there some way of re-enabling keyboard input? I am also trying to access sites that are behind a log-in screen.

**Comment by vpetersson** [comment]
@antonmolodykh do we have a solution for this?

**Comment by antonmolodykh** [comment]
@vpetersson  I have not found a solution for this yet, but I think that it will not matter soon, as we will replace uzbl

**Comment by vpetersson** [comment]
The more I think about this, I think this is the wrong approach. A better solution would be to use VNC or similar instead.

**Comment by jonpfeiler** [comment]
I am still having an issue with this. Is there any way to enable the keyboard when directly accessing screenly on the pi?

**Comment by ediphy-azorab** [comment]
This still appears to be an issue. Any workarounds available?

**Comment by nv2k** [comment]
> The more I think about this, I think this is the wrong approach. A better solution would be to use VNC or similar instead.

I'm having the same problem. Tried VNC and it's not working either.
Any thoughts?
