### ISSUE TITLE
A couple of minor frontend bugs

### ISSUE THREAD

**Issue by darginyegor** [Screenly/screenly-ose#726]
**1. Cursor doesn't react on hovering the assets arrangement icon.**

![2018-01-10 17-31-02](https://user-images.githubusercontent.com/22341230/34771250-17f73e0e-f62e-11e7-9c5d-b443d86b55a0.png)
When you move the cursor over the arrangement icon in the assets list, it stays in arrow mode, which is incorrect from the UI point. I even doubted for a second if trying to drag will lead to any result...

**2. Dragging one of the assets doesn't always make other ones jump to correct positions.**
The simple way to reproduce is:
1. Open [Screenly OSE demo page](http://ose.demo.screenlyapp.com/);
2. Drag the first asset down until the second one jumps up and DON'T release it;
3. Move that same asset all the way back up and see the second one doesn't jump back.

**Comment by vpetersson** [comment]
Good points, @darginyegor. We'll add this into the next sprint.

**Comment by darginyegor** [comment]
**[UPD]** Hovering the link, that says "Get the latest Screenly news..." turns cursor to text mode whaaaat? :slightly_smiling_face:

**Comment by vpetersson** [comment]
Solved in some previous fix as i cannot reproduce it on the [demo site](http://ose.demo.screenlyapp.com/).
