### ISSUE TITLE
Screen stuck in 'Unable to resolve local IP address' (breakout)

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#727]
Sub-ticket to #725.

In short, if the file `.screenly/wifi_set` exists and there is no Ethernet connection, the screen is stuck on "Unable to resolve local IP address indefinitely.

**Comment by kams01** [comment]
Please refer to my comment in issue: https://github.com/Screenly/screenly-ose/issues/725#issuecomment-480512237

I cannot find wifi_set and I am still stuck on the unable screen. Short of reinstalling this, I am stuck! using NOOBS
