### ISSUE TITLE
Playback video portrait mode

### ISSUE THREAD

**Issue by makabar** [Screenly/screenly-ose#736]
Hello,

we are using screenly in portrait mode
`display_rotate=1
framebuffer_width=1080
framebuffer_height=1920
`
in /boot/config.txt
Is there a way to play videos in portrait mode (720x1280; WxH or 1080x1920; WxH)??

**Comment by vpetersson** [comment]
Yes, that should work out-of-the-box. All you should have to do is to add `display_rotate=1` in `/boot/config.txt` and the rest should work. The video should in theory just work if they are in proper format.

**Comment by Larsene** [comment]
It works perfectly here.
