### ISSUE TITLE
Initial Resin WiFi Connect screen not fitting screen

### ISSUE THREAD

**Issue by metalgeekstl** [Screenly/screenly-ose#743]
Hardware: Raspberry Pi Zero W

At first boot, I'm able to see the SSID on my phone created by Resin WiFi Connect, but it's not scaled correctly and I can't see what the passphrase is. 
![img_20180207_083418](https://user-images.githubusercontent.com/13919590/35922228-a09806fc-0be2-11e8-9beb-eabc18ea579d.jpg)

I've tried 3 different displays. All have the same issue.

**Comment by vpetersson** [comment]
What resolution screen are you using?

**Comment by metalgeekstl** [comment]
I have no way of knowing. Plug in TV, plug in Pi, that's what displays on each of the 3 different TVs I've tried.

**Comment by vpetersson** [comment]
But all the monitors are capable of doing 1080p? That is the assumption that Screenly makes.

**Comment by metalgeekstl** [comment]
They should be. Standard TVs. Maybe the Pi isn't sending the TV the correct resolution?

**Comment by metalgeekstl** [comment]
Is there another way to find the passphrase? If I had that I'd be in business.

**Comment by vpetersson** [comment]
you are likely able to scroll using a keyboard. However, I'd try to swap out the HDMI cable (and/or) adaptor as that may cause the issue.

**Comment by metalgeekstl** [comment]
Keyboard or mouse does nothing. I've used different HDMI cables for each TV, and I don't have any other micro HDMI adapter available. This Pi has never had any display resolution issues outside of Screenly OSE. That's the common denominator.

**Comment by vpetersson** [comment]
Screenly doesn't really do anything with the resolution. This is all inherited by Raspbian. As such, there is no Screenly setting to change this. What happens is that in the early boot process, the Raspberry Pi will "negotiate" with the monitor for the supported resolution(s). Adaptors can interfere and break this negotiation. 

There are ways that you can override this through `config.txt` and you can find more documentation about that [here](https://elinux.org/RPiconfig).

**Comment by vpetersson** [comment]
Closing ticket due to lack of response.

**Comment by pletiplot** [comment]
Try connect the raspberry to an ethernet connection and then you can try more things.
