### ISSUE TITLE
Weather webpage not loading correctly

### ISSUE THREAD

**Issue by justinkruit** [Screenly/screenly-ose#749]
Hello,

I've made my own page to display the weather to use in Screenly. Here's a link: https://cdn.justinkruit.me/jkmonitors/weather.html

Although, when I load this into Screenly, this is the result: ![https://i.imgur.com/eFRyXg5.jpg](https://i.imgur.com/eFRyXg5.jpg)

It works absolutely fine on PC though, and the logs are saying nothing about it. Is there something wrong with the player so it won't allow specific code or something?

**Comment by vpetersson** [comment]
Yo might be using HTML/CSS that isn't supported by the browser. The current browser is a bit old (and we're working at replacing it with a more modern one).

**Comment by vpetersson** [comment]
@justinkruit did you try the new experimental branch?
