### ISSUE TITLE
Show multiple photo assets at once

### ISSUE THREAD

**Issue by catsarecool999** [Screenly/screenly-ose#750]
Is it possible to add as a Feature Request the ability to show multiple photos assets at once? Or to scroll photo assets horizontally instead of displaying one at a time?

Thank you!

**Comment by Jir4** [comment]
Do it on a webpage and use this webpage as an asset

**Comment by vpetersson** [comment]
Yes, @Jir4's solution is the only one we got for this right now. I'll add this as a feature request if someone is willing to take on the work.
