### ISSUE TITLE
Mouse Cursor is only show

### ISSUE THREAD

**Issue by WalczakAleksandra** [Screenly/screenly-ose#761]
Hi, I have a trouble. 
I have four Raspberry Pi (different, from B+ to B2), I install raspbian them, and screenly OSE. Everything works fine, but when I restart raspberry, in screen shows only a cursor on black screen. I must go to "raspi-config" and select boot option - on each start! Then, after reboot, everything works perfect again, since I restart raspberry. 
PS. Sorry for my english.

**Comment by vpetersson** [comment]
@WalczakAleksandra - Sounds like something is wrong with the disk image. I would suggest that you use one of the pre-configured disk images [here](https://github.com/Screenly/screenly-ose/releases) instead.
