### ISSUE TITLE
change wifi connection settings

### ISSUE THREAD

**Issue by morituro** [Screenly/screenly-ose#767]
hi,
how can i change the wifi settings? after installation i moved my pi to a different place with different wifi... is there a way to set up multiple wifi connections too? i changed the wpa_supplicant.conf file, but it doesnt work...
greetings!

**Comment by vpetersson** [comment]
Please see #757.

**Comment by antonmolodykh** [comment]
Hi @morituro 
Please run an update (development version). Now if there is no connection, the OSE will prompt you to select a wifi network. If you don't need it (for example you want to run OSE in offline mode), then you can enable offline mode (through a settings in the web interface).
