### ISSUE TITLE
To manage this screen .......

### ISSUE THREAD

**Issue by rhodesmi** [Screenly/screenly-ose#769]
Hi

My Screenly loads up and stays on the 'to manage the content on this screen vist http://......'

It does work fine once in a while.

Its a brand new 8Gb SD HC card (MAPLIN) 

I think this is the issue and it might not be quick enough for the application to load the MP4 it is supposed to play. Is there are a timeout in the app that could prevent it from loading the first Video?

**Comment by antonmolodykh** [comment]
Hi @rhodesmi 
No, the app doesn't have a timeout. Where is this video located? Are there any assets other than this video?

**Comment by rhodesmi** [comment]
The MP4 is located in the default area (uploaded via the WEBUI) its a stand alone Raspberry PI with no network connectivity. It has been working fine for 3 or 4 years, we have started experiencing this issue since the last upgrade earlier this year. It was recommended (via this group) to purchase a new SD card.

**Comment by antonmolodykh** [comment]
okay, can you do `sudo journalctl > foobar.txt` and attach foobar.txt once this happens?

**Comment by rhodesmi** [comment]
here you go - thanks
[foobar.txt](https://github.com/Screenly/screenly-ose/files/1833014/foobar.txt)

**Comment by antonmolodykh** [comment]
Okay, it seems we have already solved this problem. Please run an update (development version) and let me know if there are any problems.

**Comment by rhodesmi** [comment]
great that sound promising i will connect it to the internet and run the update command.

**Comment by rhodesmi** [comment]
interestingly (or not) as soon as i plugged in the network cable she sprung into life. You mentioned (development version) how do i upgrade/patch to that version?

**Comment by antonmolodykh** [comment]
just run bash <(curl -sL https://www.screenly.io/install-ose.sh). You will be asked to select the development version

**Comment by vpetersson** [comment]
Closing out ticket due to inactivity.

**Comment by rhodesmi** [comment]
Hello

Sorry forgot to say thanks for all your help. It's all working really well
now.
