### ISSUE TITLE
Ok really silly question but...

### ISSUE THREAD

**Issue by curbarthedog** [Screenly/screenly-ose#771]
I keep seeing..."fixed it, Please run an update (development version)."

How do I do this? I can't find any simple instructions.

I need the update to get the WiFi working when moving to another hotspot / SSID

**Comment by antonmolodykh** [comment]
just run bash <(curl -sL https://www.screenly.io/install-ose.sh). You will be asked to select the development version

**Comment by vpetersson** [comment]
Alternatively, you can just run `~/screenly/bin/run_upgrade.sh`.
