### ISSUE TITLE
Clock overlay

### ISSUE THREAD

**Issue by JonnyTech** [Screenly/screenly-ose#776]
Is it possible to show the current date/time over the currently playing asset?

**Comment by vpetersson** [comment]
No, this isn't something we support.

**Comment by JonnyTech** [comment]
OK - thanks for considering it as a feature request.

**Comment by vpetersson** [comment]
Technically speaking, it isn't possible to implement in the current viewer unfortunately.

**Comment by JonnyTech** [comment]
Understood - I have a (unreliable) workaround at present.

**Comment by madsrh** [comment]
> ...It will be closed if no further activity occurs

That would be now 😂
