### ISSUE TITLE
Using asset multiple times

### ISSUE THREAD

**Issue by JonnyTech** [Screenly/screenly-ose#779]
I have a lot of images that I want to show, interspaced with a logo:

logo
image1
image2
image3
logo
image4
image5
image6
logo
image7
image8
image9

Currently, I am uploading the logo file multiple times to use it in the playlist

Is it possible to have an asset both as active and in the inactive "pool" so that I can be added multiple times?

**Comment by antonmolodykh** [comment]
No, at the moment this is not supported, and it is not possible without a big changes in the application
