### ISSUE TITLE
Docker-Image not work

### ISSUE THREAD

**Issue by xstable** [Screenly/screenly-ose#787]
If I try to start the Docker-Image with this command: 
`docker run --rm -ti --name=screenly-dev -e 'LISTEN=0.0.0.0' -p 8080:8080 -v $(pwd):/home/pi/screenly screenly/ose-dev-server`
I got this response: 
`docker: Error response from daemon: failed to create endpoint screenly-dev on network bridge: failed to add the host`

How can I fix this?

**Comment by xstable** [comment]
Great, I got it. Thought the screenly-ose docker-image was a full packed container with sources inside. 
Now I've download the sources and run the container... works like a charm.
Thank you.

**Comment by vpetersson** [comment]
> Thought the screenly-ose docker-image was a full packed container with sources inside.

Actually, it is, but it wouldn't make it a very good development environment if you need to edit files inside the docker container.
