### ISSUE TITLE
Error loading google presentation with youtube videos

### ISSUE THREAD

**Issue by nrdroque** [Screenly/screenly-ose#789]
hi i'm testing your version OSE to run google presentations, and some of them need to have youtube videos inserted in some context.
but when loading the youtube it gives me error 5.
i've tested the google presentation over several browsers and computer settings and it work well

**Comment by vpetersson** [comment]
Yes, that will not work. In short, the Raspberry Pi is not powerful enough to do this (at least not using the current browser). Keep an eye on #527 as that could potentially change that.

**Comment by antonmolodykh** [comment]
@nrdroque we published the experimental screenly ose version. one of the major changes is the new browser. To try it follow the steps under 'Manual upgrade' [here](https://www.screenly.io/ose/) and answer yes to the question about experimental version.
We are looking forward to feedback, please let us know about any problems.
