### ISSUE TITLE
PUT - Request to change asset returns 400 - Bad Request

### ISSUE THREAD

**Issue by xstable** [Screenly/screenly-ose#793]
I have setup an local Dev-Enviroment.
I can access screenly backend and the viewer at my pc.
As you can see in the Image, requesting data from Assets works well: 
![auswahl_600](https://user-images.githubusercontent.com/1778068/38558996-21199d66-3cd2-11e8-9c34-4a7f6b1f69ff.jpg)

Then I try to trigger the API to change to next asset with `PUT /api/v1.1/assets/{asset_id}` via POST-Man, because in Postman I can set Action to "PUT", I only got an `error 400 : Bad Request`: 
![auswahl_601](https://user-images.githubusercontent.com/1778068/38559167-93c0f0f8-3cd2-11e8-95a1-152987df2e2e.jpg)

Any Idea why ?

**Comment by xstable** [comment]
If I trigger this PUT-Request in Postman, I got this in the screenly-CLI from server.py:
```
Traceback (most recent call last):
  File "server.py", line 239, in api_view
    return view(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful_swagger_2/swagger.py", line 219, in inner
    return f(self, *args, **kwargs)
  File "server.py", line 496, in put
    return assets_helper.update(conn, asset_id, prepare_asset(request))
  File "server.py", line 166, in prepare_asset
    data = json.loads(req.form['model'])
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
BadRequestKeyError: 400: Bad Request```

**Comment by antonmolodykh** [comment]
It looks like you tried to send a request with an empty body. The reason is that at the moment server.py expects to send all fields of an asset (both for POST request and for PUT request)

**Comment by xstable** [comment]
Ok, your're right. Now I have add a json-result I fetch via `/api/v1.1/assets/` and put this in the "Request-Body":
```JSON
{"asset_id": "b3954fe755984eeb8b8927ed322d8f6f", "mimetype": "webpage", "name": "http://www.test.de", "end_date": "2018-04-17T09:13:00+00:00", "is_enabled": 1, "nocache": 0, "is_active": true, "uri": "http://www.test.de", "duration": "10", "play_order": 0, "start_date": "2018-04-10T09:13:00+00:00", "is_processing": 0}
```

I got an `200 OK` as return value, but nothing happend on screenly. Means even if there is shown the 3rd asset (yahoo.de), and the duration is 30 seconds... and I send the PUT-Method after 5 seconds, there will be no switch to asset 1 (this one I push via PUT.
Am I doing something wrong?

**Comment by xstable** [comment]
I see now. PUT only push one new asset to the stack.
But what I'm searching for is a way to trigger screenly to interrupt current asset and jump to next one (or to a specially pointed asset_id). 
Is there a way to do this?

**Comment by antonmolodykh** [comment]
Yes, you can instantly switch to another asset using `/api/v1/assets/control/{command}` endpoint.
The command to switch will look something like this: `GET /api/v1/assets/control/asset&asset_id`

**Comment by antonmolodykh** [comment]
In addition, there are commands for moving to next and previous asset

**Comment by xstable** [comment]
Great, thanks. This solved my issue.
Did you have a hint... is there a way in Uzbl (which seems to be the viewer-browser-engine) to start youtube-video in fullscreen?

**Comment by vpetersson** [comment]
Unfortunately any form of HTML5 video is a no-go in the current browser. Even with a hardware accelerated browser (like the one we have in Screenly Pro), it's a challenging. You will have a much better result by adding the YouTube asset as a video and use a native player.

**Comment by xstable** [comment]
I got a solution... now my youtube-player is "kind-of-responsive". Anyway, now I have to see if the "live-streaming" in raspberry-pi runs smooth as aspected.
Thank you so far.

**Comment by vpetersson** [comment]
If you're able to use an RTSP feed instead, that will work a lot better than HTML5 video playback (as `omxplayer` supports RTSP feeds natively).

**Comment by xstable** [comment]
Customer has now test the Script I've created on raspberry-pi, and got some errors. 
The Video-Player is shown, and you see the first image. Than the player shows the load-animation and quit with "an error occured".
Maybe your suggestion to use RTSP is worth to try. Do you have a hint, how to get those RTSP-Links?

**Comment by vpetersson** [comment]
> Customer has now test the Script I've created on raspberry-pi, and got some errors.
The Video-Player is shown, and you see the first image. Than the player shows the load-animation and quit with "an error occured".

Yes, that's expected since the browser does not support web playback.

>  Maybe your suggestion to use RTSP is worth to try. Do you have a hint, how to get those RTSP-Links?

If you're talking about regular YouTube videos, I'm fairly confident that they do not support RTSP. It may be supported in YouTube live streams, but I'm not sure to be honest.

**Comment by xstable** [comment]
>  that's expected since the browser does not support web playback.
Mhh, really, don't seems so? In my VM where I''ve installed screenly server & viewer, the Video work like expected. So it seems not to be the browser who have the issue with it.
See this Video which shows it: 

http://screencast-o-matic.com/watch/cFfl18DPk5

So what else could be the issue? How can I figure it out?

**Comment by xstable** [comment]
Ok, I see, but in this way it isn't the Browser, it's caused by the low performance of Rasperry-Pi ?!

So what, If I use PUT to place some new YouTube-Url's as asset (lets say, viewer is currently on asset 2 and I'll place the new youtube-url as asset 5). Will they be parsed and downloaded / cached immediately, so that it will show as asset5 ?

If yes, I could fetch the youtube-playlist with my cron-scheduled script and place the videos in place where I need them (e.g. every second asset).

**Comment by vpetersson** [comment]
> Ok, I see, but in this way it isn't the Browser, it's caused by the low performance of Rasperry-Pi ?!

Well, it's a combination of the two. It largely has to do with the lack of hardware acceleration in the browser for the hardware platform.

> So what, If I use PUT to place some new YouTube-Url's as asset (lets say, viewer is currently on asset 2 and I'll place the new youtube-url as asset 5). Will they be parsed and downloaded / cached immediately, so that it will show as asset5 ?

The process involved for adding a YouTube video involves some back-end processing. However, you could do something like this:

 * Add the YouTube asset
 * Wait for it to finish processing (I think this is exposed over the API - ping @antonmolodykh)
 * Enable the asset

That should in theory allow you to do what you need to do.

**Comment by xstable** [comment]
Now I try to add an new Asset via PHP to the Stack. 
But am I right, that you can only change existing assets via PUT-API-Command?
Because you need to add the asset-id to the request:  
```
/api/v1.1/assets/{asset_id}
```
If I enter an asset_id which not exist, I got an `200 OK`, but no new asset will be created.
Isn't there a way to add a whole new asset to the Stack via API?

**Comment by mflage** [comment]
> * Enable the asset

How do you enable/disable the asset through the API? Which URL is used for that?

**Comment by vpetersson** [comment]
@mflage That should be a PATCH. Looks like we don't have that right now. @rusko124 is this the case?
