### ISSUE TITLE
Videos smooth but webpage animations very choppy/laggy

### ISSUE THREAD

**Issue by jeffdesc** [Screenly/screenly-ose#795]
Yesterday I [installed Screenly OSE on a Raspbian Stretch Lite](https://www.screenly.io/ose/#option-3-install-screenly-ose-yourself) as the last image does not work. However the videos are very smooth and have no issue with at all. But webpages with some animations in it are very choppy or laggy, it is not due to the network connection (gigabit Ethernet).

For instance we tried to show some '[attack maps](http://map.norsecorp.com/)', but it is very laggy. Instead of fluent motions it's a 3 fps slideshow.

Can this be improved due to some Raspbian tweaks/OSE tweaks. Are there some roadmaps to use another viewer as UZBL to improve this kind of pages?

**Comment by vpetersson** [comment]
Yep, see #527. We're making good progress on this and will need testers for it in the near future.

**Comment by jeffdesc** [comment]
@vpetersson Thanks for your fast confirmation. Will this be tested in a closed environment or can we test it as well? Would be happy to take part in it.

**Comment by vpetersson** [comment]
At the moment, we don't have anything to test. @antonmolodykh is working on trying to wrap up the last parts. Once done, we'll most likely create an experimental branch that will use the browser, which will allow users to manually opt in and test.

**Comment by jeffdesc** [comment]
Thanks @vpetersson!
