### ISSUE TITLE
Running without network on 2018-01-19-Screenly_OSE

### ISSUE THREAD

**Issue by BananaAcid** [Screenly/screenly-ose#796]
After boot, when the first of the images should start without network cable on RPI1B,
it just shows a gray background and the console login.

Plugging in the cable and rebooting works fine.

What I did: added 3 Images. Did set their date to something early like the existing examples.
Using 2018-01-19-Screenly_OSE_4GB.img

Edit:
After a few reboots, same happens with cable.

**Comment by vpetersson** [comment]
That's strange. We've made some changes to this. Could you try upgrading to the latest development version to see if that mitigates the problem?

**Comment by BananaAcid** [comment]
How do I do this?

**Comment by vpetersson** [comment]
Please follow the steps under 'Manual upgrade' [here](https://www.screenly.io/ose/) and answer yes to the question about the development version.

**Comment by BananaAcid** [comment]
reboot: console is back..

**Comment by antonmolodykh** [comment]
I think this related to pi1. I'll check and let you know

**Comment by vpetersson** [comment]
@BananaAcid I *think* this might be related to #836. We will be adding more diverse hardware to the testing platform in the near future. Closing out this one for now however.
