### ISSUE TITLE
Assets disabled after update

### ISSUE THREAD

**Issue by morituro** [Screenly/screenly-ose#797]
hi folks,
thx for your fantastic programm. we're using it at our school and it works fine. but after updating screenly with a bash command all assets were disabled and i had to upload them once again. i had the same issue when we gave the pi a new static ip...
thx for your help!

**Comment by antonmolodykh** [comment]
Hi @morituro 
what do you mean "all assets were disabled"? assets completely disappeared from the web interface?

**Comment by morituro** [comment]
thx for your response! i mean they are deactivated - button off.

**Comment by antonmolodykh** [comment]
hmm. if the device has no problems with time, an asset should be active if:
* user did not click "off" in the right column
* asset has not expired (see "start" and "end" columns).
are both conditions met?
