### ISSUE TITLE
Last screenly-ose works on  Pi 2 Model B v1.1 but not on PI 3 Model B +

### ISSUE THREAD

**Issue by dudul08** [Screenly/screenly-ose#799]
HI,
I have a Pi 2 Model B v1. The last version on Screenly-ose works with this PI. 
When i want to use my other  PI 3 Model B +, it doesn't works : on boot, the screen is fixed on a "rainbow"...
Thanks for help.

**Comment by vpetersson** [comment]
@dudul08 Can you be more specific? We have lots of users on Pi 3 Model B so I know that it works.

**Comment by dudul08** [comment]
On boot, the screen is fixed on a "rainbow"...

**Comment by vpetersson** [comment]
Ah! You're talking about the *Raspberry Pi 3 Model B+*. That's a different board. Yes, that is a known issue at the moment. You will have to do the manual installation for now.

**Comment by dudul08** [comment]
Ok !
Thank you for help !

**Comment by victorehi** [comment]
Hey @vpetersson, 
When you say Manual Installation for the Raspberry Pi 3 Model B+ and Screenly Pro 2, what do you mean?

**Comment by vpetersson** [comment]
@victorehi I'm not sure this is relevant to this current issue, but take a look at [Screenly Pro vs OSE](https://www.screenly.io/screenly-ose-vs-pro/) for the difference between OSE and Pro as well as the Option 3 on the [OSE page](https://www.screenly.io/ose/).
