### ISSUE TITLE
Backup/recover for Resin.io

### ISSUE THREAD

**Issue by antonmolodykh** [Screenly/screenly-ose#800]
The backup function does not work in Screenly OSE for Resin.io. The problem is related to the use of this [script](https://github.com/Screenly/screenly-ose/blob/master/ansible/roles/screenly/files/screenly_utils.sh). I think we need to think about a special scenario for this.

#774

**Comment by rusko124** [comment]
Backup and recover was reworked in [Celery](https://github.com/Screenly/screenly-ose/tree/celery) branch(PR https://github.com/Screenly/screenly-ose/pull/987#issuecomment-450341787) and should work in Resin.io

@vpetersson But I think we need to move this issue to Sprint 10, so https://github.com/Screenly/screenly-ose/issues/843 issue currently not resolved.
