### ISSUE TITLE
White flickering screen

### ISSUE THREAD

**Issue by Zer0x17** [Screenly/screenly-ose#801]
Hi,
After I completed my project with the latest sprint of screenly ose and the system started up, only the screen was flickering white. No content was displayed. Can someone help me?

Following the log files.

> 
[syslog.txt](https://github.com/Screenly/screenly-ose/files/1925036/syslog.txt)

**Comment by antonmolodykh** [comment]
Judging by the logs, there is no connection on your device and therefore a known problem arose. We have already solved it in the development branch. To get this, please run ` bash <(curl -sL https://www.screenly.io/install-ose.sh)` and answer yes to the question about the development version.

**Comment by Zer0x17** [comment]
Thanks this helped! Very good work by the way! I ♥ it!
