### ISSUE TITLE
Screenly OSE starts in console mode

### ISSUE THREAD

**Issue by watersb** [Screenly/screenly-ose#807]
Same as #692 -- Clean install, reboot into console to run raspi-config, disable overscan, enable SSH, clean reboot.

Looks like we get a good restart, no obvious problems. But we get a console login screen.

Reboot once more, and we are back to a working Screenly.

Is this the expected behavior?

**Comment by antonmolodykh** [comment]
no, this is not the expected behavior. which Raspberry model do you use?

**Comment by vpetersson** [comment]
Closing due to lack of response.
