### ISSUE TITLE
Asset upload failure.

### ISSUE THREAD

**Issue by Cyberprog** [Screenly/screenly-ose#808]
Hi All,

Had an issue where I ran out of disk space (I'd forgotten to expand the filesystem like a dumbass) and as a result, the uploads failed. However screenly did not clear the rogue .tmp files out, nor did it then attempt to flag a warning in the UI saying "a previous upload of this file, failed, clear temp file?" it just continues to fail.

I think this would be good for usability, and to avoid people having to drop down into the filesystem to remove the files by hand.

Alex

**Comment by antonmolodykh** [comment]
@vpetersson  I confirm script is working
