### ISSUE TITLE
Web Interface fails on Static IP

### ISSUE THREAD

**Issue by Cyberprog** [Screenly/screenly-ose#809]
Using Screenly OSE, if you configure a static IP on the ethernet I note some odd behaviours;

1) Even if there is a link, the splash screen still displays "unable to obtain IP address" (or whatever the wording is!).
2) The web interface returns an error for the main page (/), but /system_info and /settings are available.

Remove the static config and things go back to normal.

**Comment by antonmolodykh** [comment]
I did not encounter such problems. Perhaps you have incorrectly configured a static IP? try it: https://github.com/Screenly/screenly-ose/issues/746#issuecomment-366642078

**Comment by vpetersson** [comment]
@Cyberprog are you able to reproduce this on the development branch?

**Comment by Cyberprog** [comment]
I've not had a chance to do that yet @vpetersson  - I'm out of the office the first few days next week but will have a whirl towards the end.
