### ISSUE TITLE
Question about static IP with Wlan 

### ISSUE THREAD

**Issue by M1rtin** [Screenly/screenly-ose#810]
Hey guys i'm new here and started playing around with this awesome project you have all created from almost a week now . I installed the latest version 0.14 . Thanks to the nice guide [https://github.com/Screenly/screenly-ose/blob/master/docs/http-basic-authentication.md](url) i manage to set a password to the web GUI and with a little research i manage to run ssh (tnx to a txt file named : ssh with no extension) and change its password . So back to my question more than a problem . From what i saw and read if i want to use hidden SSID i should use something like that

`nmcli c add type wifi con-name <connect name> ifname wlan0 ssid <ssid>
nmcli con modify <connect name> wifi-sec.key-mgmt wpa-psk
nmcli con modify <connect name> wifi-sec.psk <password>
nmcli con up <connect name>`

or just use the nmtui for graphic interface . In the moment i have connected it to a visible network . But i want to put a static IP on the WLAN . For now i have managed that from the router itself with mac reservation . I tried from the device with SSH and the nmtui but when i added the 192.168.0.50 ip and restarted i could assess it  from both 192.168.0.50 and the one that was by default given from the router and DHCP 192.168.0.108 . Most likely i will use it in a network with couple of AP's around with the same hidden SSID and i want to make it with static IP from the device so i dont have to use mac reservations . Can someone assist with some information how this can happen and if it is at all possible within the test environment i want to try it with ?

**Comment by vpetersson** [comment]
@M1rtin That sounds like a Network Manager question rather than Screenly. According to [this page](https://wiki.gnome.org/Projects/NetworkManager), you they have both a mailing list and an IRC channel. I suggest you ask there.
