### ISSUE TITLE
Make hotspot and splash page adaptive

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#816]
I have a small screen that I use for testing. It has something like 680x480 resolution. However, when I use this screen, I cannot make out the passphrase for the hotspot. I can see the SSID, but not the SSID.

**Comment by vpetersson** [comment]
Still not adaptive enough: 

![img_1380](https://user-images.githubusercontent.com/357664/41776034-22694f7e-761e-11e8-980e-de87d6abd804.JPG)

**Comment by antonmolodykh** [comment]
![image](https://user-images.githubusercontent.com/25369651/42134026-7da747b8-7d55-11e8-99e5-35e908761d56.png)

**Comment by vpetersson** [comment]
I was wrong. The resolution in the image is 800x480.
