### ISSUE TITLE
upstream: "http://192.168.42.1:9090/"

### ISSUE THREAD

**Issue by josephglass1029** [Screenly/screenly-ose#825]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I am trying to configure Screenly OSE on my Pi, but I keep getting 504 Gateway Time-out. When I go to the /var/log/nginx/error.log I see the following entry: 2018/05/29 23:47:01 [error] 348#348: *3 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.35.5.136, server: , request: "GET / HTTP/1.1", upstream: "http://192.168.42.1:9090/", host: "10.35.5.104"

I don't know what resource it is trying to reach on the 192.168.42.X network, but as you can see I am on the 10.35.5.X network. 

#### Reproduction Steps

bash <(curl -sL https://www.screenly.io/install-ose.sh)
answered no to both the development and full system upgrade
reboot
launched a browser and pointed it to the ip address on the screen.

### Environment

* Raspberry Pi Hardware Version:
Raspberry Pi 2 Model B V1.1
* Screenly OSE Version:

**Comment by vpetersson** [comment]
This error means that Nginx is unable to connect to Resin WiFi Connect ([ref](https://github.com/Screenly/screenly-ose/blob/master/ansible/roles/nginx/files/nginx.conf#L5-L7)).

Check the logs with `journalctl` to see what comes up.

**Comment by vpetersson** [comment]
Closing ticket due to lack of response.
