### ISSUE TITLE
API call for navigate to any asset error

### ISSUE THREAD

**Issue by wwj718** [Screenly/screenly-ose#837]
#### Overview of the Issue
![image](https://user-images.githubusercontent.com/3153878/41762965-23aaa70a-762f-11e8-848e-4b6328fad716.png)

### Environment

* Raspberry Pi 3B
* Screenly OSE Version: commit 62bfe2ff477122ee97bf1b1017e94abffad52013 (Thu May 3 14:53:18 2018)

**Comment by antonmolodykh** [comment]
@wwj718  I think it's in `&` symbol. try something like `curl -s "http://127.0.0.1:8080/api/v1/assets/control/asset&64c9830eae4e484db276e1c6259d2849"`

**Comment by vpetersson** [comment]
Yep. That's not a bug, `&` in Bash has means run the next command (vastly simplified). @antonmolodykh solution above should solve it.

**Comment by wwj718** [comment]
@antonmolodykh @vpetersson Thanks a lot !  it works!
