### ISSUE TITLE
Bug in new environment

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#841]
#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

* Add the asset http://video.blendertestbuilds.de/download.blender.org/peach/trailer_1080p.mov as a URL

You will end up with:

![screenshot from 2018-06-22 13-26-04](https://user-images.githubusercontent.com/357664/41776527-03b6b2f4-7620-11e8-90fc-555edc2e4d76.png)

### Environment

* Raspberry Pi Hardware Version: Raspberry Pi 3 Model B
* Screenly OSE Version: Experimental branch

**Comment by antonmolodykh** [comment]
it seems this link is not valid at this time. however I tested it using another video (http://techslides.com/demos/samples/sample.mov) of the same format and it works fine
