### ISSUE TITLE
Perform facelift

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#842]
The look and feel in OSE is starting to look a bit dated. After we have upgraded Bootstrap in #840, let's switch to a Bootstrap theme. Here's [one candidate](https://hackerthemes.com/bootstrap-themes/growth/).

**Comment by antonmolodykh** [comment]
I applied this theme, but the visible changes are very small. I think OSE needs a more serious redesign
![image](https://user-images.githubusercontent.com/25369651/44133816-990e665c-a083-11e8-9b7a-1ca747c97313.png)
![image](https://user-images.githubusercontent.com/25369651/44133839-b6e2bf34-a083-11e8-8a16-dacb11732e61.png)

**Comment by madsrh** [comment]
This really didn't work out 😆 but since I spent the time working on it, I might as well share it here for conversation.

![image](https://user-images.githubusercontent.com/3986894/49050460-c3d22700-f1e3-11e8-9b69-f7ecf6f30991.png)

> ...but I think that we need a more complex redesign than a simple theme change.

If I can, I would love to give this a try with a few mockups

**Comment by rusko124** [comment]
@madsrh It looks very good, I like it!
@vpetersson What do you think?

**Comment by vpetersson** [comment]
@madsrh Thanks! I'll loop in our staff designer to get his feedback too.

**Comment by L4cko** [comment]
> @madsrh Looks good! We just need to fix the colors.

**Comment by rusko124** [comment]
@vpetersson I would like to see this in Sprint 10
