### ISSUE TITLE
Switch to Balena

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#843]
The experimental branch is currently using Docker. We should switch to using [Balena](https://www.balena.io/) instead as it is written for this particular use case.

**Comment by antonmolodykh** [comment]
At the moment `balena pull` works much slower than `docker pull`. I opened a [ticket](https://github.com/resin-os/balena/issues/86) about it.

**Comment by antonmolodykh** [comment]
In fact, I changed the installation to use Balena, but when testing I could not run Balena on Pi1 and Pi Zero W. I asked about it in the [resin chat](https://gitter.im/resin-io/chat), but I have not received an answer yet.
The current progress on this task is [here](https://github.com/greatfruitomsk/screenly-ose/tree/Switch-to-Balena).

In addition, if we will use Balena, then using `command` module for ansible is not a good idea. It might make sense to write a `balena` module for ansible (something like `docker_container` but for Balena)

**Comment by vpetersson** [comment]
@ealmonte32 you wanna take a stab at this one?

**Comment by ealmonte32** [comment]
@vpetersson 
![image](https://user-images.githubusercontent.com/24350198/55652099-94967c80-57b8-11e9-8ca0-35b474915266.png)

I honestly do want to learn docker(moby)/balena/containers/IoT, etc.., so I have been trying during my free time by messing with different Dockerfile configurations... so I make no promises. =]

**Comment by vpetersson** [comment]
All good, @ealmonte32. Plenty of things to do here once you get to it ;)
