### ISSUE TITLE
Cookie transfer

### ISSUE THREAD

**Issue by StopKickingMe** [Screenly/screenly-ose#858]
Hello there,

I was wondering if there is a way to export cookies from a seperate browser (like Opera) on a seperate computer, and import them onto the Raspberry Pi. I found the path to the cookie files for UZBL, and I know how to find the cookies in Opera, but I was wondering how to bridge the gap between the two. If I could do that, I would be able to load webpages that require user authentication without having to pass through the login screen (why i cant since keyboard input is not accepted in Screenly.

I'm using the latest stable release of Screenly.

**Comment by vpetersson** [comment]
@StopKickingMe There's currently no way to do this, but we'll keep this as a feature request.
