### ISSUE TITLE
Wrong screen resolution on Westinghouse TV

### ISSUE THREAD

**Issue by arothmanmusic** [Screenly/screenly-ose#864]
#### Overview of the Issue

I've set up Screenly OSE on a Raspberry Pi 3. It loads a single asset - a webpage with a full-screen 1920x1080 slideshow. This works perfectly on two Vizio TVs I've tested it with. However, the TV it's supposed to play on is a Westinghouse. On that particular TV, Screenly boots up 480p only. I get black bars down the sides and only the top left corner of the picture. If I boot to the Debian desktop I do get 1080 resolution, so I know the TV and Pi are able to transmit at full size, but it doesn't work with Screenly. I also tried loading a single 1920x1080 photo asset and it also loaded at 480p only.

I'm unable to get to the terminal with CTRL+ALT=F1 on any of the TVs.

### Environment

* Raspberry Pi Hardware Version: 3
* Screenly OSE Version: Latest (installed it this weekend)

**Comment by vpetersson** [comment]
@arothmanmusic That's strange.

When you say "latest" does that mean the latest disk image?

> I'm unable to get to the terminal with CTRL+ALT=F1 on any of the TVs.

That should be ctrl+alt+f1

**Comment by arothmanmusic** [comment]
Yeah, I meant ctrl+alt+f1 - just a typo. :)

"Latest" meant I went into the shell and ran $ bash <(curl -sL https://www.screenly.io/install-ose.sh) that day. I'm not sure what the version number was.

I actually have since overwritten the card and moved on to other methods because I couldn't get it to work within my deadline, so I don't have the details. Sorry about that...

**Comment by vpetersson** [comment]
Closing out due to lack of response.
