### ISSUE TITLE
Wordpress web server heavy usage

### ISSUE THREAD

**Issue by dragonunit** [Screenly/screenly-ose#866]
I have digital signage running on wordpress with Divi Builder pulling a couple of pages from that website. The web server is constantly getting hammered to the point where the external IP of the locations where Screenly is deployed get blocked. 

Is there any way to have screenly cache the pages for a week (they are only updated once weekly)

* Raspberry Pi Hardware Version: Raspi3 B+
* Screenly OSE Version: Paradise City

**Comment by vpetersson** [comment]
No, you can't cache an entire website like that in Screenly. That said, something is probably wrong with the WordPress configuration if that's the case (unless you have thousands of devices hammering it). Try installing a caching plugin on Wordpress to see if that solves the issue.

**Comment by dragonunit** [comment]
Its only 3 devices. I will check with the web host on what the issue is. I have caching plugins, minify and css combination. Weird.

**Comment by vpetersson** [comment]
Interesting. Well, if three devices can take down your web server, something is definitely wrong.

**Comment by vpetersson** [comment]
Closing out this as I'm pretty sure it's unrelated to Screenly.
