### ISSUE TITLE
Stuck on Screenly Splash Screen with experimental update

### ISSUE THREAD

**Issue by bhagemann** [Screenly/screenly-ose#871]
#### Overview of the Issue

Installed a new image of Sprint7 on SD card.  Booted up on RaspPi.  Configured wi-fi and enabled SSH.  Rebooted the Pi via SSH.  Ran the bash line to upgrade the card to the latest everything (experimental version, upgrade system and so on).  Rebooted.  Got blue Screenly screen which it says on.  Doesn't begin any slideshow.  Can't log in with web front end (get ngnix bad gateway message).  CAN connect with SSH, reboot it... does the same thing.

### Environment

* Raspberry Pi Hardware Version:  Tried on 3 and new 3+, exactly same thing happens
Tried with 2 SD cards, different brands
Tried with 2 power supplies

This only started happening about a week ago or so when I had the experimental version running fine mostly, and ran the bash script to see if there were any development updates it would pick up.  Since then I can't get the latest dev/experimental version running.

**Comment by vpetersson** [comment]
@antonmolodykh can you please take a look?

**Comment by netjordanlee** [comment]
+1

Also getting this issue.

**Comment by mscreations** [comment]
I've run into this issue as well. I was trying to see if the experimental version would work on my Pi Zero, and I found that the device boots and I can ssh into it, but none of the docker containers start up automatically. Issuing a `docker start screenly-ose-websocket && docker start screenly-ose-server && docker start screenly-ose-viewer` does take care of it though.

**Comment by vpetersson** [comment]
@mscreations Interesting find. We have a new update for the Pi Zero in the pipeline, but I don't have an ETA for this yet. The other issue is a bit stranger and needs to be investigated.

**Comment by antonmolodykh** [comment]
I confirm the problem. I don't understand why this is happening, because I did not change anything with regard to launching containers. I'll let you know when I fix it

**Comment by mscreations** [comment]
The weird part is after i manually start the containers the first time, it works fine afterwards. I have had no issues with it starting afterwards. I do however have an issue where the whole pi locks up. No ssh, no web server response, and the viewer stops.

**Comment by acruzmx** [comment]
+1 .. Same here, except that when I do docker start screenly-ose-websocket the container does not exist... Any idea?

**Comment by vpetersson** [comment]
@acruzmx Did you try it with the latest changes to the experimental branch?

**Comment by acruzmx** [comment]
Hi, thanks for asking. I was using the latest update. I ended up reinstalling the old one. 
The root problem I was trying to solve is that a couple of klipfolio dashboards are stalling an loosing connection, even though I can get to the console via SSL. I'm then able to reboot, over and over
Thanks again

**Comment by rusko124** [comment]
Hi @acruzmx ! Do you still have this problem? If so, could you give the reproduce steps for this problem?
