### ISSUE TITLE
No screenly.conf file?

### ISSUE THREAD

**Issue by Jonovich** [Screenly/screenly-ose#872]
Built a ScreenlyOSE system using the "My Michelle" 2018-05-04 image v0.15.1 and am trying to implement the basic-authentication and I can't find a screenly.conf file in the /home/pi/screenly folder that the basic-authentication documentation talks about.

Jon.

H/W Raspberry Pi 3 Model B, 8Gb SD.

**Comment by vpetersson** [comment]
@Jonovich The path is `/home/pi/.screenly` not `/home/pi/screenly`. I realize that this might be confusing.

**Comment by Jonovich** [comment]
Doh! I'm a muppet! Thanks muchly.
