### ISSUE TITLE
crontab no available when using resin.io

### ISSUE THREAD

**Issue by dimiclic** [Screenly/screenly-ose#874]
#### Overview of the Issue

Having Screenly OSE running on multiple devices with resin.io
Problem: crontab -e
    service is not installed and can not be installed both in host as in main

* Raspberry Pi Hardware Version: 3B
* Screenly OSE Version: 379c417

**Comment by vpetersson** [comment]
This is expected as there is no crontab running inside the container. @antonmolodykh I think we should probably start moving to Celery or something similar to be able to process background tasks better.

**Comment by dimiclic** [comment]
Are there plans to get crontab working in the near future?

**Comment by vpetersson** [comment]
No, using a crontab in a dockerized environment is not the proper solution. This logic needs to be written with a worker (like Celery).

**Comment by vpetersson** [comment]
Will be fixed in #876.
