### ISSUE TITLE
Deprecate cronjobs in favor of worker

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#876]
As pointed out in #874, some features will not work in resin/dockerized environment. To solve this, we need to introduce a worker that can run inside a docker container.

I suggest that we use [Celery](http://www.celeryproject.org/) and port all cronjobs to run there..

**Comment by Marco-LB** [comment]
Hello, is it possible to have a tutorial? instructions how to create a command to execute on startup? hdmi-cec on startup?

**Comment by vpetersson** [comment]
@Marco-LB sure, take a look [here](https://www.screenly.io/blog/2017/07/02/how-to-automatically-turn-off-and-on-your-monitor-from-your-raspberry-pi/).

**Comment by Marco-LB** [comment]
thanks for the quick reply, but cron and crontab know how to use them, but celery is the problem

**Comment by vpetersson** [comment]
Well, this isn't implemented yet. That's what this ticket is tracking.

**Comment by Marco-LB** [comment]
can this post help? [https://github.com/resin-io-playground/cron-example](url)

**Comment by vpetersson** [comment]
We know how to do it. It's fairly straight forward. We just haven't implemented it yet. It is scheduled for the next sprint.

**Comment by Marco-LB** [comment]
OK, Thanks for your information

**Comment by rusko124** [comment]
This issue was solved in [Celery](https://github.com/Screenly/screenly-ose/tree/celery) branch(PR https://github.com/Screenly/screenly-ose/pull/987#issuecomment-450341787).
The subsequent discussion, I recommend to move here #1081

@vpetersson I think we can close this.
