### ISSUE TITLE
memory leak uzbl-browser 

### ISSUE THREAD

**Issue by pioneer01** [Screenly/screenly-ose#892]
#### Overview of the Issue

uzbl-browser consumes more and more memory (memory leak)

#### Reproduction Steps

Run "top | grep uzbl" while screenly is running.  Memory is increasing over some hours.

### Environment

* Raspberry Pi Hardware Version: Pi 3 Model B
* Screenly OSE Version: latest Screenly OSE

I "solved" the problem with the following workaround: A cronjob restarts the screenly-viewer service every two hours.
Is there a more elegant workaround or bugfix than I found?

Best Regards
Martin

**Comment by vpetersson** [comment]
@pioneer01 There is some logic for that built-in already. However, the *real* solution is found in the experimental branch where we swap out uzbl entirely.
