### ISSUE TITLE
Can I connect to a hidden SSID / WiFi Access Point with Screenly-ose?

### ISSUE THREAD

**Issue by alciomarhollanda** [Screenly/screenly-ose#895]
Can I connect to a hidden SSID / WiFi Access Point with Screenly-ose?

**Comment by vpetersson** [comment]
Yes, but you need to do some command line magic. [This post](https://stackoverflow.com/questions/37312501/how-do-i-detect-and-connect-to-a-hidden-ssid-on-my-raspiberry-pi-3-raspbian) should help point you in the right direction. Alternatively, you can use [nm-cli](https://stackoverflow.com/questions/35476428/how-to-connect-to-hidden-wifi-network-using-nmcli), which is arguably a bit more complicated but recommended.
