### ISSUE TITLE
Add support for live streaming

### ISSUE THREAD

**Issue by SebastianSchildt** [Screenly/screenly-ose#90]
As far as I could see the current implementation for a video stream is "start it and wait until omxplayer is finished", however I think it would be useful to optionally specify a duration, in the case of continuous running livestreams:

Switch to the stream for 5 min, then go on to the next asset. As far as I could see omxplayer does not support this directly, but I guess spawning a shell process and doing a "sleep x; kill <omx_pid>" might do the trick just fine (killall omxplayer probably not a good idea, if omxplayer finishes, crashes before the timeout is reached you might accidentally kill another instance already playing the next asset.).

Maybe I will come around to do this myself later this month, however I just thought of putting it here, in case somebody picks it up before me :)

**Comment by xbmcnut** [comment]
+1. It seems setting the video length is currently not possible, even if you upload your own clip? (2015-02-25). I have the same issue with live streams; they work well but can't be timed. I also tried uploading my own MP4 at 133s and I can't set the video to play for anything less than the full length. Video timings do not seem to 'stick'.

**Comment by colej4586** [comment]
+1
Would like to be able to loop videos at least in their entirety as setting a duration for them does not work.
Any way this could possibly be considered?

**Comment by krzimmer** [comment]
I was able to add an HLS stream asset.  It plays properly with audio for mulitple hours, but continues playing even when the asset has been turned off.  I agree that it would be nice to be able to turn the live stream off and continue to the next asset.  However, this would be a great alernative to installating an IPTV set top box for displays that only play the same TV station 24/7.

**Comment by vpetersson** [comment]
We've added a bounty [here](https://www.bountysource.com/issues/9137902-add-support-for-live-streaming). 

Here's what's required for acceptance:

 * Clear and documented code that follows PEP8
 * Should introduce a new duration setting for the live feed
 * Should support popular feeds in RTSP (`rtsp://...`) and RTMP (`rtmp://...`) and formats (these are the feeds supported by `omxplayer` according to [this](http://elinux.org/Omxplayer#Streaming) page)
  * This needs to be posted as proper
 * Should have tests
