### ISSUE TITLE
Missing visual indicator after successfully uploading image

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#902]
#### Overview of the Issue

There is no visual indicator when you have successfully uploaded an image.

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Press Add Asset
* Select an image file
* Press Save

### Environment

* Raspberry Pi Hardware Version: Local dev enviroment
* Screenly OSE Version: master (2620358)

**Comment by madsrh** [comment]
Shouldn't this issue be closed, since https://github.com/Screenly/screenly-ose/pull/942 has been merged?

**Comment by vpetersson** [comment]
@madsrh Thanks for the house cleaning. Yep. you're absolutely right! :)
