### ISSUE TITLE
Incorrect bootstrap in newest test build

### ISSUE THREAD

**Issue by a2tech** [Screenly/screenly-ose#907]
On the newest available test build the web interface looks for bootstrap.css but bootstrap.min.css is all that exists in screenly/static/css

* Raspberry Pi Hardware Version: 3

**Comment by vpetersson** [comment]
@rusko124 Can you confirm this?

**Comment by rusko124** [comment]
Used only bootstrap.min.css.
@a2tech Can you provide steps to reproduce this issue or screenshots?

**Comment by vpetersson** [comment]
Closing due to lack of response.
