### ISSUE TITLE
Terminal shortcut keys no longer working

### ISSUE THREAD

**Issue by abrenoch** [Screenly/screenly-ose#908]
It appears in the "My Michelle" release the raspbian shortcut to open the terminal (ctrl+alt+F1/F2) no longer works once screenly is loaded. I can get to the terminal for a brief moment during the boot sequence, but not once screenly starts.

To reproduce simply hook up a keyboard and try the shortcut ctrl+alt+F1. This used to work fine as it was how I would resolve networking issues when not accessible via SSH.

I'm running on a pi3 b+, using the 'My Michelle" release as mentioned above.

**Comment by rusko124** [comment]
Hi, @abrenoch !
This behavior is typical for the experimental branch.
Did you make update Screenly-OSE?

**Comment by qbicdesign** [comment]
I have the same issue using the Screen OSE ready-made image. No updates, just vanilla version.
I can use CTRL+ALT+F1 while Screenly is displaying the logon URL, It seems that I can also continue using it (once it's open) as long as my playlist contains only URLs. If there's a video in the playlist, the video is overlayed on top and I can no longer use the console.

**Comment by vpetersson** [comment]
@qbicdesign If you have a video playing, this is expected behavior. You need to use `ssh` instead (which is the recommended method to access the device). 

(The technical reason is that the video rendered takes over the whole screen, so you are unable to see the terminal.)
