### ISSUE TITLE
Add API call for what's currently being played

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#916]
See discussion [here](https://support.screenly.io/hc/en-us/community/posts/360016094294-OSE-API-get-the-current-asset). 

In short, it would be desirable to have an API call to determine what is currently being shown on the screen.

**Comment by rusko124** [comment]
@vpetersson How would you like that would be implemented communication between the server.py and viewer.py? Maybe socket or something else?

**Comment by rusko124** [comment]
This endpoint already in master.
@vpetersson I think we can close this.
