### ISSUE TITLE
ReactJs doesn't work

### ISSUE THREAD

**Issue by damienpeerbolte** [Screenly/screenly-ose#918]
I'm trying to display a webpage with some reactjs included, but the reactjs part of the page doesn't work.

**Comment by damienpeerbolte** [comment]
I already checked "y" for experimental branch at the installation of screenly.

**Comment by damienpeerbolte** [comment]
It does behave the same way on both the branches

**Comment by vpetersson** [comment]
What Raspberry Pi hardware?

Also, we would need the steps to reproduce this in order to look into it.

**Comment by damienpeerbolte** [comment]
It's a raspberry pi 3b

**Comment by damienpeerbolte** [comment]
But if I install Raspbian Stretch(with Desktop) on the Pi and then go into Chromium, the webpage I want to display works. If install screenly directly on the pi(without raspbian) the reactjs part of the webpage won't work.

**Comment by vpetersson** [comment]
Yeah, Chrome does things a bit different. However, if we are able to reprocude, we can look into it.

**Comment by damienpeerbolte** [comment]
that means it's the browser that doesn't accept the reactjs, not the pi, right?

**Comment by vpetersson** [comment]
Not sure. We haven't tested it very closely. Could maybe be some setting.

**Comment by damienpeerbolte** [comment]
Also when I install screenly over raspbian it works, how come it doesn't work on screenly only?

**Comment by damienpeerbolte** [comment]
oh wait, it's installed on lite without a desktop.. makes sense
