### ISSUE TITLE
Add ability to migrate assets to Pro

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#930]
#### Overview of the Issue

We've had a lot of Screenly customers who have inquired about how to migrate assets from Screenly OSE to Screenly Pro. We should provide a tool to do this in a seamless fashion. With the new asset API point in Screenly Pro, this is now possible.

#### Desired workflow

* Launch a Python script
* Ask the user for either the API token or the credentials (which then will be used to get an API token)
* Validate the token
* Create a new folder called "Screenly OSE Uploads"
* Upload all assets on from the local database
  * We need to make sure that the folder name is set to "Screenly OSE Uploads"
  * Make sure that the title is the is properly set
  * If there is a duration set, preserve it
* Make sure there is good feedback to the user about the progress

Some information can be found [here](https://www.screenly.io/blog/2017/12/15/building-intelligent-digital-signage/)

**Comment by vpetersson** [comment]
Screenly Pro's API doesn't currently allow for uploading files, so we need to work around this by serving the files locally using something like [Ngrok](https://ngrok.com).

**Comment by vpetersson** [comment]
[Click](https://click.palletsprojects.com/en/5.x/) looks pretty promising for building out a quick CLI interface.

**Comment by rusko124** [comment]
@vpetersson 
I wrote a script with all the wishes, could you look and say what needs to be changed?
https://github.com/rusko124/screenly-assets-migration
