### ISSUE TITLE
There is no possibility to add a page with requiring js

### ISSUE THREAD

**Issue by rusko124** [Screenly/screenly-ose#933]
#### Overview of the Issue

The problem is described in detail https://support.screenly.io/hc/en-us/community/posts/360017643434-URL-error-for-asset.
I reproduced this problem and can confirm it.
![error](https://user-images.githubusercontent.com/17593028/46716156-b9d08500-cc84-11e8-8a05-141b67b5e2fd.png)
When screenly check on validate this url, send GET request and receive the 404 status code, this is due to the fact that javascript is disabled.
@vpetersson Do we need to solve such situations? If yes, then I can suggest using something like this https://github.com/kennethreitz/requests-html

**Comment by vpetersson** [comment]
I think that overcomplicates things. Basically, that's a bug in the webiste/server rather than in Screenly. It should return a 20X. Perhaps a better option is to add an option for something like "Skip asset check."

**Comment by rusko124** [comment]
Got it!

**Comment by vpetersson** [comment]
Closing out. Please ping the original reporter to ensure it worked.
