### ISSUE TITLE
The assets that added with skip checking are not displayed.

### ISSUE THREAD

**Issue by rusko124** [Screenly/screenly-ose#945]
In this PR #937 was an opportunity to add an asset without checking. But `viewer.py` check asset url before asset was display.
Thus, we have an asset check error.
To avoid this problem, need to add a parameter skip check in the database, but this will lead to problems with users' databases.
@vpetersson What can you recommend?

**Comment by vpetersson** [comment]
> To avoid this problem, need to add a parameter skip check in the database, but this will lead to problems with users' databases.

That's just a typical migration issue. You just need to add that to `/bin/migrate.py`.

**Comment by rusko124** [comment]
Got it, thanks!
