### ISSUE TITLE
Create a Screenly-OSE store with Screenly widgets.

### ISSUE THREAD

**Issue by rusko124** [Screenly/screenly-ose#950]
I don't think it's necessary, but it would be convenient.
At the moment, Screenly has widgets with weather, time and news.
I think this topic can be developed, create widgets for social networks, news, charts, etc.

@vpetersson What do you think about it? Does it make sense?
P.S. I came to this idea when the user on the forum asked about the widget Twitter feed .

**Comment by vpetersson** [comment]
@rusko124 Yes, we have a number of ideas around this and some designs.

**Comment by rusko124** [comment]
That's great!

**Comment by zombodotcom** [comment]
So
