### ISSUE TITLE
502 Bad Gateway when I add password protect

### ISSUE THREAD

**Issue by TheCazz** [Screenly/screenly-ose#958]
Hi
I running the latest Screenly OSE on a old raspberry
Everything works fine but when I add a username and a password in screenly.conf file I get npw a 502 Bad Gateway.

**Comment by vpetersson** [comment]
Try upgrading to the latest release. If you are still having the issue then, please post logs.

**Comment by TheCazz** [comment]
Hmm I did try to upgrade with 
bash <(curl -sL https://www.screenly.io/install-ose.sh)
But I got error, trying now again.

**Comment by TheCazz** [comment]
Ohh now I can set a username and password from web interface. very nice :)
