### ISSUE TITLE
Improve passwords for wifi hotspot

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#963]
When we generate the password for the hotspot, we use letters that are hard to differentiate, such as  I and l (upper case i and lower case l). Let's resolve this. There must be libraries available that solves this.

**Comment by escoand** [comment]
Isn't another font enough?

**Comment by vpetersson** [comment]
No, i don't think that is a good solution as even with a different font it would be hard to make out the difference from a distance.

**Comment by escoand** [comment]
What do you think about this?
https://www.slant.co/topics/10309/viewpoints/4/~password-fonts~source-code-pro
The only problem I see is with zero and upper O.

**Comment by rusko124** [comment]
@vpetersson  Can we close?
