### ISSUE TITLE
Errno 13 permission denied

### ISSUE THREAD

**Issue by klarmacker** [Screenly/screenly-ose#965]
![error](https://user-images.githubusercontent.com/45293944/48952226-be55b200-ef41-11e8-9790-bf1ce619fbca.png)

Hello

Iam quiet new in the Screenly business. i set it up and the first thing i tried was to upload a Picture. 
But i stuck and get the Error in the Picture above.

Can someone help me?

Thanks
chris

**Comment by vpetersson** [comment]
hi @klarmacker - interesting. Is this on the latest disk image?

**Comment by vpetersson** [comment]
I just reproduced it - will issue a fix shortly.

**Comment by vpetersson** [comment]
The temporary solution is to do the following:
 * Login using the default credentials
 * Run `chown -R pi:pi screenly_assets`

**Comment by vpetersson** [comment]
Bug fixed and new disk image is being built (but it will take a few hours).

**Comment by vpetersson** [comment]
This has now been fixed in the latest disk image. Thanks for reporting.

**Comment by klarmacker** [comment]
ok great thanks i will update it on Monday

**Comment by klarmacker** [comment]
Working now thanks for your Service
