### ISSUE TITLE
Add support for displaying the Raspberry Pi version/model in the user interface

### ISSUE THREAD

**Issue by vpetersson** [Screenly/screenly-ose#971]
I'd like to add the ability to display the Raspberry Pi version in the system info under System Info.

We can get the hardware version from here:

```
$ grep Revision /proc/cpuinfo
Revision        : a01041
```

Then we simply need to parse this, and turn it into the model number using [this list](https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md).

**Comment by dig1talmad** [comment]
While you're at it, could you display the version of Screenly in System Info too?

**Comment by vpetersson** [comment]
Good idea @dig1talmad.

**Comment by qbicdesign** [comment]
yay

**Comment by qbicdesign** [comment]
can we get MAC address(es) added too please?

**Comment by vpetersson** [comment]
@qbicdesign Yes shouldn't be very hard. I guess we need to display both for WiFi and Ethernet.

**Comment by rusko124** [comment]
Raspberry Model / Screenly Version / MAC address were added to the system info page.
@vpetersson I think we can close this.
