### ISSUE TITLE
Server Error: database is locked

### ISSUE THREAD

**Issue by Cryjack** [Screenly/screenly-ose#973]
Hi,
we've got the problem shown below while loading the page and even while saving changes. There are 490 active assets used. Is this too much for SQLite? Is there a possibility to change to MySQL or something else?

![image](https://user-images.githubusercontent.com/11329556/49141510-0cc6d000-f2f7-11e8-9933-0c173d1039cc.png)

**Comment by rusko124** [comment]
Hi @Cryjack !
Can you tell which version of Screenly you are using, please?

**Comment by Cryjack** [comment]
Hi rusko124,

yes of course. Sorry.

Just updated today to the latest productive version. But the issue exists even before.

**Comment by vpetersson** [comment]
My guess would be that it's a SD card corruption issue. I'd recommend that you do the following:

 * Export a backup (Settings -> Backup)
 * Get a new SD card
 * Flash out the latest version to the new SD card
 * Restore the backup

**Comment by Cryjack** [comment]
Hi @vpetersson 

the system is working fine, its just the overview of the assets and editing. We have 3 systems and all of them have the same issue. The cards are just 2 months in use so I assume that curruption issues are not the problem.

**Comment by Cryjack** [comment]
Ah, another thing is, that backups don't work with this amount of assets. I assume this could be a setting in webserver (maxfilesize or something).

**Comment by Cryjack** [comment]
The page loads and all assets are shown after an amount of time, but the message is shown every time again.

**Comment by vpetersson** [comment]
Interesting. I'd be keen to solve that. Could you provide some steps to reproduce this?

**Comment by rusko124** [comment]
@vpetersson @Cryjack I will deal with this problem and give you information about it soon

**Comment by Cryjack** [comment]
@rusko124 
Okay great, thank you. If I can do something to help just let me know.

**Comment by rusko124** [comment]
@Cryjack Can you update your Screenly and tell me if this has helped you?

**Comment by Cryjack** [comment]
@rusko124 I've updated on dev-branch and can confirm that the issue is gone. Great job! Thank you very much!
