### ISSUE TITLE
Zoom out a webpage

### ISSUE THREAD

**Issue by TheCazz** [Screenly/screenly-ose#978]
Is it possible to make a page is zoom out a little.
We have a page that is a little to big to show it nice on the TV screen and I like to zoom out a little.
The strange is that I have no problem to show it nice on a web browser on a computer?

**Comment by rusko124** [comment]
I think that's a good idea.
Also about a similar situation says here #981
What do you think about it? @vpetersson 
Could be added as an option to an asset or as a global option(with range 50% to 200% for example).

**Comment by vpetersson** [comment]
I'm not sure I agree. It's a slipper slope. Let's leave this aside for now. Most modern/responsive websites will behave properly and adjust accordingly.
