### ISSUE TITLE
Assets with long URL

### ISSUE THREAD

**Issue by Cryjack** [Screenly/screenly-ose#983]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

URL-Assets with log URLs are not editable because Buttons are overlayed by Inputfields. (TAB works, but Usability...)

Maybe something like "show more" for the URL helps?

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Edit URL Asset with long URL like shown in Screenshot

### Environment

* Raspberry Pi Hardware Version: Pi 3B+
* Screenly OSE Version: latest DEV

Screenshot:
![image](https://user-images.githubusercontent.com/11329556/49430502-750c2a80-f7ab-11e8-9d33-d86d3096407e.png)

**Comment by vpetersson** [comment]
Nice find, @Cryjack. Let's truncate the "Asset Location" field after 25-30 characters.
