### ISSUE TITLE
Tips to play background music

### ISSUE THREAD

**Issue by TheCazz** [Screenly/screenly-ose#989]
I have see some have ask for play background music on the slideshow and I just want to give my solution.
I have activate SSH so from there I have install screen and then create a bash file and add this code
`while true; do for v in ./musicfolder/*; do omxplayer -o hdmi $v; done; done`
then save it and then run `sudo chmod +x file.sh`
Now it run the mp3 file from musicfolder and running that as a loop.
After that I close the screen so it still running when I disconnect the SSH

You can also just run a webradio station like this
`omxplayer -o hdmi addresstoawebradiostation`

**Comment by vpetersson** [comment]
Interesting solution, @TheCazz. I'm not sure if omxplayer will look up the video interface when doing this. If so, it will prevent videos from being used in the playlist. Another issue with the suggested solution is that you will have to break the loop to add more content. Perhaps you can find a better solution using any tools listed in [this article](http://www.tuxarena.com/2011/12/10-console-music-players-for-linux/).
