### ISSUE TITLE
No hotspot when using balenaCloud

### ISSUE THREAD

**Issue by astrodad** [Screenly/screenly-ose#996]
#### Overview of the Issue

I just configured a brand new Application and two devices in balenaCloud, all on ethernet. I disconnected the ethernet and rebooted the devices, expecting Screenly to create the hotspot so that I could configure the wifi. No hotspot appears and Screenly cannot connect. 

### Environment

* Raspberry Pi Hardware Version: Raspberry 3 B+
* Screenly OSE Version: built from Master branch today via balenaCloud

**Comment by ealmonte32** [comment]
I've seen this and experienced it before, this is just one of many possible ways to reset the wifi connection screen..

get into terminal by pressing ctrl+alt+f1 , and once there run:
ls ~/.screenly/
and see if you have a file called wifi_set

if so, delete it by running:
rm -rf ~/.screenly/wifi_set

**Comment by rusko124** [comment]
Hi @astrodad !
In the balenaCloud image settings, you can specify your access point.
Currently, Screenly hotspot is not supported in balenaCloud

![balena](https://user-images.githubusercontent.com/17593028/50760339-b8b5f080-1291-11e9-8241-9b60d8270b43.png)

**Comment by ealmonte32** [comment]
@astrodad can you close this issue if it was resolved by what rusko suggested?

**Comment by ealmonte32** [comment]
@vpetersson - can we close this since user has not replied?

**Comment by astrodad** [comment]
Thanks for the suggestion and the info.
