### ISSUE TITLE
Backup Authentication Bypass

### ISSUE THREAD

**Issue by AngelG-543** [Screenly/screenly-ose#998]
When a screenly instance is setup and running, there is normally authentication if the user chooses to enable it that guards the various functions. A recent discovery has led to being able for an unauthenticated user to bypass the authentication mechanism and retrieve a copy of the backup file.
screenly setup:
Authentication enabled
no ssl enabled

It seems that the link is not active when authentication is disabled. The steps to reproduce are:
setup authentication
save settings
navigate to *host*/static_with_mime/screenly-backup.tar.gz?mime=application/x-tgz using a different browser, machine, or clearing browser data
download begins
![capture](https://user-images.githubusercontent.com/46010693/50380481-1c071800-062e-11e9-9dd4-0a65b72a6124.JPG)

This was also tested using another raspberry pi that had screenly installed on top of raspbian-lite. same results. The way this could be fixed could be to just change the permissions available for the download, or to require authentication when going directly to the link.

The configuration file contains all types of good information such as a SHA-256 password hash and a Cleartext username

Screenly-OSE Version: Disk image download from a week ago, and the Master-branch version
Pi Envrionment: One raspbian-lite based image with Screenly installed on top, and one with screenly disk image flashed straight to the drive, both raspberry pi model 3 b+

**Comment by vpetersson** [comment]
@AngelG-543 Good find. Frankly speaking, I wouldn't recommend using the built-in authentication as it is still pretty rough and should be considered work-in-progress. If you want to secure the device properly, I suggest using basic auth in Nginx instead. That said, we should definitely fix this.

@rusko124 could you try reproducing this?

**Comment by rusko124** [comment]
Confirm the issue above.
Created a PR to resolve this problem.

**Comment by vpetersson** [comment]
@rusko124 Is this fully solved?

**Comment by rusko124** [comment]
@vpetersson I think yes, we can close it.

**Comment by vpetersson** [comment]
@rusko124 can you  just double check to ensure you cannot reproduce it?

**Comment by rusko124** [comment]
> @rusko124 can you just double check to ensure you cannot reproduce it?

@vpetersson 
![backup](https://user-images.githubusercontent.com/17593028/53626076-fcdcc600-3c2e-11e9-965b-66c7d2eb7d46.png)
